Repository IBAMR/IBAMR, pull requests merged in 2018-09, with the labels that each got.

#311 Fix links in top level README.
  README.md
Labels: Documentation

#314 Check for an incompatible libMesh setting.
  configure
  ibtk/configure
  ibtk/m4/configure_libmesh.m4
  m4/configure_libmesh.m4
Labels: Build System, libMesh

#310 Fix unused variable warnings 0.3
  examples/multiphase_flow/ex0/LSLocateCircularInterface.cpp
  examples/multiphase_flow/ex0/SetFluidProperties.cpp
  examples/multiphase_flow/ex1/SetFluidGasSolidDensity.cpp
  examples/multiphase_flow/ex1/SetFluidGasSolidViscosity.cpp
  examples/multiphase_flow/ex2/SetFluidGasSolidDensity.cpp
  examples/multiphase_flow/ex2/SetFluidGasSolidViscosity.cpp
  examples/multiphase_flow/ex3/SetFluidProperties.cpp
  examples/multiphase_flow/ex4/GravityForcing.cpp
  examples/multiphase_flow/ex4/LSLocateLayerInterface.cpp
  examples/multiphase_flow/ex4/SetFluidProperties.cpp
  examples/multiphase_flow/ex5/GravityForcing.cpp
  examples/multiphase_flow/ex5/LSLocateColumnInterface.cpp
  examples/multiphase_flow/ex5/SetFluidProperties.cpp
  examples/multiphase_flow/ex5/TagLSRefinementCells.cpp
  examples/multiphase_flow/ex6/GravityForcing.cpp
  examples/multiphase_flow/ex6/LSLocateFluidInterface.cpp
  examples/multiphase_flow/ex6/SetFluidProperties.cpp
  examples/multiphase_flow/ex6/TagLSRefinementCells.cpp
  examples/multiphase_flow/ex6/VelocityInitialCondition.cpp
  examples/vc_navier_stokes/ex2/GravityForcing.cpp
  examples/vc_navier_stokes/ex2/LSLocateCircularInterface.cpp
  examples/vc_navier_stokes/ex2/SetFluidProperties.cpp
  examples/vc_navier_stokes/ex2/TagLSRefinementCells.cpp
  src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
Labels: Miscellaneous

#309 Fix unused variable warnings
  examples/multiphase_flow/ex0/LSLocateCircularInterface.cpp
  examples/multiphase_flow/ex0/SetFluidProperties.cpp
  examples/multiphase_flow/ex1/SetFluidGasSolidDensity.cpp
  examples/multiphase_flow/ex1/SetFluidGasSolidViscosity.cpp
  examples/multiphase_flow/ex2/SetFluidGasSolidDensity.cpp
  examples/multiphase_flow/ex2/SetFluidGasSolidViscosity.cpp
  examples/multiphase_flow/ex3/SetFluidProperties.cpp
  examples/multiphase_flow/ex4/GravityForcing.cpp
  examples/multiphase_flow/ex4/LSLocateLayerInterface.cpp
  examples/multiphase_flow/ex4/SetFluidProperties.cpp
  examples/multiphase_flow/ex5/GravityForcing.cpp
  examples/multiphase_flow/ex5/LSLocateColumnInterface.cpp
  examples/multiphase_flow/ex5/SetFluidProperties.cpp
  examples/multiphase_flow/ex5/TagLSRefinementCells.cpp
  examples/multiphase_flow/ex6/GravityForcing.cpp
  examples/multiphase_flow/ex6/LSLocateFluidInterface.cpp
  examples/multiphase_flow/ex6/SetFluidProperties.cpp
  examples/multiphase_flow/ex6/TagLSRefinementCells.cpp
  examples/multiphase_flow/ex6/VelocityInitialCondition.cpp
  examples/vc_navier_stokes/ex2/GravityForcing.cpp
  examples/vc_navier_stokes/ex2/LSLocateCircularInterface.cpp
  examples/vc_navier_stokes/ex2/SetFluidProperties.cpp
  examples/vc_navier_stokes/ex2/TagLSRefinementCells.cpp
  src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
Labels: Miscellaneous

#327 Allow versions of PETSc newer than 3.9.
  configure
  ibtk/configure
  ibtk/m4/configure_petsc.m4
  m4/configure_petsc.m4
Labels: Build System

#328 Allow versions of PETSc newer than 3.9: 0.3.0 release
  configure
  ibtk/configure
  ibtk/m4/configure_petsc.m4
  m4/configure_petsc.m4
Labels: Build System
