Repository IBAMR/IBAMR, pull requests merged in 2018-08, with the labels that each got.

#267 Use ternary if in muparser.
  examples/ConstraintIB/impulsively_started_cylinder/input2d
  examples/ConstraintIB/impulsively_started_cylinder/input2d.test
  examples/IB/explicit/ex0/input2d
  examples/IB/explicit/ex0/input2d.shell
  examples/IB/explicit/ex0/input2d.shell_circum_fibers
  examples/IB/explicit/ex0/input2d.test
  examples/IBFE/explicit/ex0/input2d
  examples/IBFE/explicit/ex0/input2d.test
  examples/IBFE/explicit/ex3/input2d
  examples/IBFE/explicit/ex3/input2d.test
  examples/IBFE/explicit/ex6/input2d
  examples/IBFE/explicit/ex6/input2d.test
  examples/IBFE/explicit/ex7/input2d.caseC
  examples/IBFE/explicit/ex7/input2d.caseS2
  examples/IBFE/explicit/ex7/input2d.caseSP
  examples/IBFE/explicit/ex7/input2d.test
  examples/IBFE/explicit/ex8/input2d
  examples/IBFE/explicit/ex8/input2d.test
  examples/navier_stokes/ex1/input2d
  examples/navier_stokes/ex1/input2d.test
  examples/navier_stokes/ex1/input3d
  examples/navier_stokes/ex1/input3d.test
  ibtk/examples/PETScOps/ProlongationMat/input2d
  ibtk/examples/PETScOps/ProlongationMat/input2d.test
  ibtk/examples/PETScOps/ProlongationMat/input3d
  ibtk/examples/PETScOps/ProlongationMat/input3d.test
Labels: Miscellaneous

#271 Fixing ConstraintIB, level set, and vc gtests
  examples/ConstraintIB/falling_sphere/Makefile.am
  examples/ConstraintIB/falling_sphere/Makefile.in
  examples/level_set/ex0/Makefile.am
  examples/level_set/ex0/Makefile.in
  examples/level_set/ex0/test_main.cpp
  examples/level_set/ex1/Makefile.am
  examples/level_set/ex1/Makefile.in
  examples/level_set/ex1/test_main.cpp
  examples/multiphase_flow/ex1/Makefile.am
  examples/multiphase_flow/ex1/Makefile.in
  examples/multiphase_flow/ex1/input2d.test
  ibtk/examples/VCViscousSolver/Makefile.am
  ibtk/examples/VCViscousSolver/Makefile.in
Labels: Tests

#273 Restore compatibility with libMesh 1.0.0.
  configure
  ibtk/configure
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/m4/configure_libmesh.m4
  ibtk/src/lagrangian/FEDataManager.cpp
  m4/configure_libmesh.m4
Labels: libMesh

#270 Convert some pointers to mutable variables.
  ibtk/include/ibtk/muParserRobinBcCoefs.h
  ibtk/src/boundary/physical_boundary/muParserRobinBcCoefs.cpp
Labels: Miscellaneous

#276 Fix compatibility with libMesh 1.3.0.
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
Labels: libMesh

#274 Add libmesh exodus check
  examples/CIBFE/ex0/example.cpp
  examples/CIBFE/ex1/example.cpp
  examples/IBFE/explicit/ex0/example.cpp
  examples/IBFE/explicit/ex1/example.cpp
  examples/IBFE/explicit/ex10/example.cpp
  examples/IBFE/explicit/ex11/example.cpp
  examples/IBFE/explicit/ex2/example.cpp
  examples/IBFE/explicit/ex3/example.cpp
  examples/IBFE/explicit/ex4/example.cpp
  examples/IBFE/explicit/ex5/example.cpp
  examples/IBFE/explicit/ex6/example.cpp
  examples/IBFE/explicit/ex7/example.cpp
  examples/IBFE/explicit/ex8/example.cpp
  examples/IBFE/explicit/ex9/example.cpp
  examples/multiphase_flow/ex2/example.cpp
Labels: libMesh

#277 Fix the adv_diff ex0 3D test.
  examples/adv_diff/ex0/input3d.test
Labels: Bug, Tests

#289 Set write_viz_interval = 0.
  examples/CIB/ex0/input2d.test
Labels: Tests

#293 Fix aborting tests in adv_diff.
  examples/adv_diff/ex1/input2d.test
  examples/adv_diff/ex1/input3d.test
Labels: Bug, Tests

#296 Run one test at stricter tolerances.
  examples/IBFE/explicit/ex0/Makefile.am
  examples/IBFE/explicit/ex0/Makefile.in
  examples/IBFE/explicit/ex0/test_main.cpp
Labels: Tests

#299 Fix a warning regarding initialization order.
  src/IB/IBFEInstrumentPanel.cpp
Labels: Miscellaneous, enhancement

#294 Fix aborting IBFE tests
  examples/IBFE/explicit/ex5/example.cpp
  examples/IBFE/explicit/ex5/input2d
  examples/IBFE/explicit/ex5/input2d.test
  examples/IBFE/explicit/ex5/input3d
  examples/IBFE/explicit/ex5/input3d.test
  examples/IBFE/explicit/ex6/example.cpp
  examples/IBFE/explicit/ex6/input2d.test
Labels: Bug, Tests

#300 Remove some duplicated if statements.
  ibtk/src/boundary/physical_boundary/PhysicalBoundaryUtilities.cpp
Labels: Miscellaneous

#301 Add parentheses suggested by -Wparentheses.
  src/navier_stokes/StaggeredStokesPhysicalBoundaryHelper.cpp
Labels: Miscellaneous

#305 add a VERSION file for the 1.0.0 prerelease.
  VERSION
Labels: Miscellaneous

#306 Disable faulty tests.
  examples/ConstraintIB/flow_past_cylinder_HF/Makefile.am
  examples/ConstraintIB/flow_past_cylinder_HF/Makefile.in
  examples/IBFE/explicit/ex10/Makefile.am
  examples/IBFE/explicit/ex10/Makefile.in
  examples/IBFE/explicit/ex11/Makefile.am
  examples/IBFE/explicit/ex11/Makefile.in
  examples/multiphase_flow/ex2/Makefile.am
  examples/multiphase_flow/ex2/Makefile.in
  examples/navier_stokes/ex1/Makefile.am
  examples/navier_stokes/ex1/Makefile.in
Labels: Tests
