Repository IBAMR/IBAMR, pull requests merged in 2019-08, with the labels that each got.

#655 Removed solve for advection diffusion solver with zero diffusion coefficient
  doc/news/changes/minor/20190730AaronBarrett
  src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
Labels: enhancement

#658 Fix some code to work with surface meshes.
  ibtk/include/ibtk/libmesh_utilities.h
Labels: Bug

#664 Fix a pedantic test warning.
  tests/refine/rt0_refine_01.cpp
Labels: Tests
