Repository IBAMR/IBAMR, pull requests merged in 2019-12, with the labels that each got.

#771 Reformat some files to use Unix line endings.
  examples/CIB/ex3/example.cpp
  include/ibamr/CIBMobilitySolver.h
Labels: Miscellaneous

#770 Add notes on git.
  README.md
  doc/git.md
Labels: Documentation

#766 Add more bbox
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/utilities/libmesh_utilities.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/bounding_boxes_01.cpp
  tests/IBTK/bounding_boxes_01.input
  tests/IBTK/bounding_boxes_01.output
Labels: enhancement

#735 Remove CIBFEMethod
  configure
  configure.ac
  examples/CIBFE/Makefile.am
  examples/CIBFE/Makefile.in
  examples/CIBFE/ex0/Makefile.am
  examples/CIBFE/ex0/Makefile.in
  examples/CIBFE/ex0/README
  examples/CIBFE/ex0/example.cpp
  examples/CIBFE/ex0/input2d
  examples/CIBFE/ex1/Makefile.am
  examples/CIBFE/ex1/Makefile.in
  examples/CIBFE/ex1/Mobility.m
  examples/CIBFE/ex1/README
  examples/CIBFE/ex1/example.cpp
  examples/CIBFE/ex1/input2d
  examples/CIBFE/ex1/input3d
  examples/Makefile.am
  examples/Makefile.in
  include/ibamr/CIBFEMethod.h
  include/ibamr/CIBMethod.h
  lib/Makefile.am
  lib/Makefile.in
  src/IB/CIBFEMethod.cpp
Labels: Miscellaneous

#759 Allow IBAMR to be built with bundled boost when libMesh is enabled with no boost support.
  Makefile.in
  config/IBAMR_config.h.tmp.in
  configure
  doc/news/changes/minor/20191119AaronBarrett
  ibtk/Makefile.in
  ibtk/config/IBTK_config.h.tmp.in
  ibtk/configure
  ibtk/m4/configure_boost.m4
  m4/configure_boost.m4
  m4/configure_libmesh.m4
Labels: Build System

#774 Minor fixes for git.md
  doc/git.md
Labels: Documentation

#777 Add another release task
  doc/release-tasks.md
Labels: Documentation

#780 Remove flow_past_cylinder_HF.
  configure
  configure.ac
  examples/ConstraintIB/Makefile.am
  examples/ConstraintIB/Makefile.in
  examples/ConstraintIB/flow_past_cylinder_HF/HydroForceEval.cpp
  examples/ConstraintIB/flow_past_cylinder_HF/HydroForceEval.h
  examples/ConstraintIB/flow_past_cylinder_HF/Makefile.am
  examples/ConstraintIB/flow_past_cylinder_HF/Makefile.in
  examples/ConstraintIB/flow_past_cylinder_HF/RigidBodyKinematics.cpp
  examples/ConstraintIB/flow_past_cylinder_HF/RigidBodyKinematics.h
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder2d.elem
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder2d.vertex
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder2d_2h.elem
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder2d_2h.ghost
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder2d_3h.elem
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder2d_3h.ghost
  examples/ConstraintIB/flow_past_cylinder_HF/cylinder_gen.m
  examples/ConstraintIB/flow_past_cylinder_HF/example.cpp
  examples/ConstraintIB/flow_past_cylinder_HF/input2d
Labels: Tests

#783 Fix codimension 1 code
  ibtk/include/ibtk/FEMapCache.h
  ibtk/include/ibtk/JacobianCalculator.h
  ibtk/include/ibtk/JacobianCalculatorCache.h
  ibtk/include/ibtk/QuadratureCache.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/JacobianCalculator.cpp
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/explicit_ex5.cpp
  tests/IBFE/explicit_ex5_2d.mpirun=2.input
  tests/IBFE/explicit_ex5_2d.mpirun=2.output
  tests/IBFE/explicit_ex5_3d.mpirun=2.input
  tests/IBFE/explicit_ex5_3d.mpirun=2.output
  tests/IBTK/jacobian_calc_01.cpp
  tests/IBTK/jacobian_calc_01.output
Labels: Bug

#781 Increment FEDataManager::FE_DATA_MANAGER_VERSION.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: Miscellaneous

#785 Fix test partitioning
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4_2d.input
  tests/IBFE/explicit_ex4_2d.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.output
  tests/IBFE/explicit_ex4_2d.postprocessor.input
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.postprocessor.output
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.restart=50.input
  tests/IBFE/explicit_ex4_3d.mpirun=4.input
  tests/IBFE/explicit_ex4_3d.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
Labels: Bug

#786 Fix the bounding box test with libMesh 1.1.0.
  tests/IBTK/bounding_boxes_01.cpp
Labels: Tests

#788 Fix copyright
  examples/complex_fluids/Makefile.am
  examples/complex_fluids/ex0/Makefile.am
  examples/complex_fluids/ex0/example.cpp
  examples/complex_fluids/ex1/Makefile.am
  examples/complex_fluids/ex1/example.cpp
  examples/complex_fluids/ex2/InterpolationUtilities.cpp
  examples/complex_fluids/ex2/InterpolationUtilities.h
  examples/complex_fluids/ex2/Makefile.am
  examples/complex_fluids/ex2/convergence_tester.cpp
  examples/complex_fluids/ex2/example.cpp
  examples/complex_fluids/ex2/plot_sxx.m
  examples/complex_fluids/ex3/Makefile.am
  examples/complex_fluids/ex3/example.cpp
  examples/complex_fluids/ex4/Makefile.am
  examples/complex_fluids/ex4/example.cpp
  ibtk/include/ibtk/JacobianCalculator.h
  ibtk/include/ibtk/JacobianCalculatorCache.h
  ibtk/src/fortran/const.i
  ibtk/src/lagrangian/JacobianCalculator.cpp
  include/ibamr/CFGiesekusRelaxation.h
  include/ibamr/CFINSForcing.h
  include/ibamr/CFOldroydBRelaxation.h
  include/ibamr/CFRelaxationOperator.h
  include/ibamr/CFRoliePolyRelaxation.h
  include/ibamr/CFUpperConvectiveOperator.h
  src/advect/fortran/limitertypes.i
  src/complex_fluids/CFGiesekusRelaxation.cpp
  src/complex_fluids/CFINSForcing.cpp
  src/complex_fluids/CFOldroydBRelaxation.cpp
  src/complex_fluids/CFRelaxationOperator.cpp
  src/complex_fluids/CFRoliePolyRelaxation.cpp
  src/complex_fluids/CFUpperConvectiveOperator.cpp
  src/complex_fluids/Makefile.am
  src/complex_fluids/fortran/Makefile.am
  src/complex_fluids/fortran/div_tensor2d.f.m4
  src/complex_fluids/fortran/div_tensor3d.f.m4
  src/complex_fluids/fortran/log_upper_convective_op2d.f.m4
  src/complex_fluids/fortran/log_upper_convective_op3d.f.m4
  src/complex_fluids/fortran/sqrt_upper_convective_op2d.f.m4
  src/complex_fluids/fortran/sqrt_upper_convective_op3d.f.m4
  src/complex_fluids/fortran/upper_convective_op2d.f.m4
  src/complex_fluids/fortran/upper_convective_op3d.f.m4
  src/fortran/const.i
  src/tools/autostarter.pl
  src/tools/beam_validator3d.pl
  src/tools/includes.pl
  src/tools/regen_viz_input_files.pl
  src/tools/scale_spring_rest_length.pl
  src/tools/scale_spring_stiffness.pl
  src/tools/set_spring_rest_length.pl
  src/tools/set_spring_stiffness.pl
  src/tools/spring_validator3d.pl
  src/tools/target_point_validator3d.pl
  tests/IBTK/bounding_boxes_01.cpp
  tests/IBTK/jacobian_calc_01.cpp
  tests/complex_fluids/Makefile.am
  tests/complex_fluids/cf_forcing_op_01.cpp
  tests/complex_fluids/cf_four_roll_mill.cpp
  tests/complex_fluids/cf_relaxation_op_01.cpp
  tests/navier_stokes/navier_stokes_01.cpp
Labels: Documentation

#789 Remove namespaces.h from a header.
  include/ibamr/AdvDiffWavePropConvectiveOperator.h
  src/adv_diff/AdvDiffWavePropConvectiveOperator.cpp
Labels: Miscellaneous

#787 added some documentation to restart functions
  ibtk/include/ibtk/AppInitializer.h
  include/ibamr/IBFEMethod.h
Labels: Documentation

#790 Define end iterators outside of loops.
  src/IB/IBFEDirectForcingKinematics.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
Labels: libMesh

#792 Get rid of some warnings from hypre headers.
  .clang-format
  ibtk/include/ibtk/CCPoissonHypreLevelSolver.h
  ibtk/include/ibtk/SCPoissonHypreLevelSolver.h
  ibtk/include/ibtk/ibtk_macros.h
  ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
  ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp
Labels: External Libraries, Miscellaneous

#801 Add a hint for a release task.
  doc/release-tasks.md
Labels: Miscellaneous

#805 added restart capabilities to IBFE examples
  doc/news/changes/minor/20191219MarshallDavey
  examples/IBFE/explicit/ex0/example.cpp
  examples/IBFE/explicit/ex1/example.cpp
  examples/IBFE/explicit/ex10/example.cpp
  examples/IBFE/explicit/ex11/example.cpp
  examples/IBFE/explicit/ex2/example.cpp
  examples/IBFE/explicit/ex3/example.cpp
  examples/IBFE/explicit/ex4/example.cpp
  examples/IBFE/explicit/ex5/example.cpp
  examples/IBFE/explicit/ex6/example.cpp
  examples/IBFE/explicit/ex7/example.cpp
  examples/IBFE/explicit/ex8/example.cpp
  examples/IBFE/explicit/ex9/example.cpp
Labels: libMesh

#810 Fix IBFESurfaceMethod's restart load.
  doc/news/changes/minor/20191219DavidWells
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex5.cpp
  tests/IBFE/explicit_ex5_2d.restart=40.mpirun=2.input
  tests/IBFE/explicit_ex5_2d.restart=40.mpirun=2.output
Labels: Bug

#812 Fixing 3D bug for finding distance from surface mesh and 3D rotation …
  src/IB/BrinkmanPenalizationRigidBodyDynamics.cpp
  src/level_set/FESurfaceDistanceEvaluator.cpp
Labels: Bug

#803 Fix clang warnings
  examples/ConstraintIB/moving_plate/RigidBodyKinematics.h
  examples/complex_fluids/ex2/InterpolationUtilities.cpp
  ibtk/include/ibtk/LInitStrategy.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/JacobianCalculator.cpp
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/PETScMFFDJacobianOperator.cpp
  include/ibamr/BrinkmanPenalizationRigidBodyDynamics.h
  include/ibamr/CFINSForcing.h
  include/ibamr/CFRelaxationOperator.h
Labels: Miscellaneous

#813 Fix an unused variable warning.
  src/level_set/FESurfaceDistanceEvaluator.cpp
Labels: Miscellaneous

#814 Collate changelog entries for 0.6.0.
  doc/news/changes/0.5.1-vs-0.6.0.html
  doc/news/changes/incompatibilities/20190710DavidWells
  doc/news/changes/incompatibilities/20190909DavidWells
  doc/news/changes/incompatibilities/20190916DavidWells
  doc/news/changes/incompatibilities/20190919BoyceGriffith
  doc/news/changes/incompatibilities/20191004DavidWells
  doc/news/changes/incompatibilities/20191205DavidWells
  doc/news/changes/major/20190923AaronBarrett
  doc/news/changes/major/20191031DavidWells
  doc/news/changes/major/20191203DavidWells
  doc/news/changes/major/20191218AmneetBhalla
  doc/news/changes/minor/20190730AaronBarretDavidWells
  doc/news/changes/minor/20190730AaronBarrett
  doc/news/changes/minor/20190812DavidWells
  doc/news/changes/minor/20190920DavidWells
  doc/news/changes/minor/20191104DavidWells
  doc/news/changes/minor/20191112AaronBarrett
  doc/news/changes/minor/20191119AaronBarrett
  doc/news/changes/minor/20191122JordanBrown
  doc/news/changes/minor/20191219DavidWells
  doc/news/changes/minor/20191219MarshallDavey
Labels: Documentation

#815 Remove some empty brackets from the changelog.
  doc/news/changes/0.5.1-vs-0.6.0.html
Labels: Documentation
