Repository IBAMR/IBAMR, pull requests merged in 2019-05, with the labels that each got.

#553 fix compilation with libmesh 1.4
  ibtk/src/utilities/libmesh_utilities.cpp
Labels: libMesh

#556 fix line breaks in tester message.
  attest
Labels: Tests

#564 Do not remove an unused patch data index.
  src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
Labels: Bug

#565 fix some warning messages
  ibtk/include/ibtk/HierarchyMathOps.h
  ibtk/include/ibtk/LNodeIndex.h
  ibtk/include/ibtk/libmesh_utilities.h
  include/ibamr/AdvDiffWavePropConvectiveOperator.h
  include/ibamr/INSVCStaggeredPressureBcCoef.h
  include/ibamr/NonbondedForceEvaluator.h
Labels: enhancement

#566 Remove some unnecessary pointers.
  include/ibamr/StaggeredStokesSolver.h
  src/navier_stokes/StaggeredStokesSolver.cpp
Labels: SAMRAI, enhancement

#568 Convert an IBTK example into a new test.
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/poisson_01.cpp
  tests/IBTK/poisson_01_2d.mpirun=4.input
  tests/IBTK/poisson_01_2d.mpirun=4.output
  tests/IBTK/poisson_01_3d.mpirun=4.input
  tests/IBTK/poisson_01_3d.mpirun=4.output
Labels: Tests

#538 create class SAMRAIDataCache to cache allocated Eulerian data
  ibtk/include/ibtk/SAMRAIDataCache.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/utilities/SAMRAIDataCache.cpp
Labels: SAMRAI, enhancement

#574 Add a switch for the vector type for U's RHS.
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/IBFE/interpolate_velocity_01.d.cached.mpirun=4.input
  tests/IBFE/interpolate_velocity_01.d.cached.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.d.ghosted.mpirun=4.input
  tests/IBFE/interpolate_velocity_01.d.ghosted.mpirun=4.output
Labels: libMesh

#571 Actually add the two phase regrid test.
  tests/multiphase_flow/GravityForcing.h
  tests/multiphase_flow/LSLocateCircularInterface.h
  tests/multiphase_flow/LSLocateGasInterface.h
  tests/multiphase_flow/RigidBodyKinematics.h
  tests/multiphase_flow/SetFluidGasSolidDensity.h
  tests/multiphase_flow/SetFluidGasSolidViscosity.h
  tests/multiphase_flow/SetLSProperties.h
  tests/multiphase_flow/TagLSRefinementCells.h
  tests/multiphase_flow/cylinder2d_free_fall.vertex
  tests/multiphase_flow/free_falling_cyl_cib.cpp
  tests/multiphase_flow/free_falling_cyl_cib.mpirun=4.input
  tests/multiphase_flow/free_falling_cyl_cib.mpirun=4.output
Labels: Tests

#570 avoid using raw pointers in IBTK
  ibtk/include/ibtk/CCPoissonHypreLevelSolver.h
  ibtk/include/ibtk/CartCellDoubleLinearCFInterpolation.h
  ibtk/include/ibtk/CartCellDoubleQuadraticCFInterpolation.h
  ibtk/include/ibtk/CartSideDoubleQuadraticCFInterpolation.h
  ibtk/include/ibtk/HierarchyGhostCellInterpolation.h
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/include/ibtk/LaplaceOperator.h
  ibtk/include/ibtk/PoissonFACPreconditionerStrategy.h
  ibtk/include/ibtk/PoissonSolver.h
  ibtk/include/ibtk/SCPoissonHypreLevelSolver.h
  ibtk/src/boundary/HierarchyGhostCellInterpolation.cpp
  ibtk/src/boundary/cf_interface/CartCellDoubleLinearCFInterpolation.cpp
  ibtk/src/boundary/cf_interface/CartCellDoubleQuadraticCFInterpolation.cpp
  ibtk/src/boundary/cf_interface/CartSideDoubleQuadraticCFInterpolation.cpp
  ibtk/src/lagrangian/LSiloDataWriter.cpp
  ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
  ibtk/src/solvers/impls/LaplaceOperator.cpp
  ibtk/src/solvers/impls/PoissonFACPreconditionerStrategy.cpp
  ibtk/src/solvers/impls/PoissonSolver.cpp
  ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/INSVCStaggeredConservativeMassMomentumIntegrator.h
  src/navier_stokes/INSVCStaggeredConservativeMassMomentumIntegrator.cpp
Labels: C++11

#578 Convert an IBTK example into a new test.
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/laplace_01.cpp
  tests/IBTK/laplace_01_2d.mpirun=6.input
  tests/IBTK/laplace_01_2d.mpirun=6.output
  tests/IBTK/laplace_01_3d.mpirun=8.input
  tests/IBTK/laplace_01_3d.mpirun=8.output
Labels: Tests

#562 routines for computing mean flow quantities and turbulent kinetic energy
  doc/news/changes/major/20190507BoyceGriffith
  include/ibamr/INSStaggeredHierarchyIntegrator.h
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
Labels: enhancement

#582 Fix a memory leak in LData.
  ibtk/include/ibtk/LData.h
  ibtk/include/ibtk/private/LData-inl.h
  ibtk/src/lagrangian/LData.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/ldata_01.cpp
  tests/IBTK/ldata_01.input
  tests/IBTK/ldata_01.mpirun=4.input
  tests/IBTK/ldata_01.mpirun=4.output
  tests/IBTK/ldata_01.output
Labels: Tests

#586 Added memory header file.
  ibtk/include/ibtk/HierarchyGhostCellInterpolation.h
Labels: C++11

#567 Allowing for rotation even when translation locked
  Makefile.in
  doc/news/changes/minor/20181022NishantNangia
  src/IB/ConstraintIBKinematics.cpp
  src/IB/ConstraintIBMethod.cpp
  tests/multiphase_flow/LSLocateBargeInterface.h
  tests/multiphase_flow/Makefile.am
  tests/multiphase_flow/Makefile.in
  tests/multiphase_flow/rotating_barge_cib.cpp
  tests/multiphase_flow/rotating_barge_cib.mpirun=4.input
  tests/multiphase_flow/rotating_barge_cib.mpirun=4.output
Labels: enhancement

#596 Guard writing to input files with a rank check.
  tests/multiphase_flow/free_falling_cyl_cib.cpp
  tests/multiphase_flow/rotating_barge_cib.cpp
Labels: Tests

#557 Assemble into ghost regions in interpWeighted.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  src/IB/IBFEMethod.cpp
Labels: libMesh

#603 fixing transposed function arguments
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
Labels: Bug

#605 Add a missing call to PetscFinalize().
  tests/IBTK/ldata_01.cpp
Labels: Tests
