Repository IBAMR/IBAMR, pull requests merged in 2019-11, with the labels that each got.

#733 reuse SAMRAIDataCache objects between FEDataManager instances
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
Labels: enhancement

#736 Convert ibfe ex0 test
  examples/IBFE/explicit/ex0/test_main.cpp
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/explicit_ex0.cpp
  tests/IBFE/explicit_ex0_2d.input
  tests/IBFE/explicit_ex0_2d.output
Labels: Tests

#713 Add optional argument to not draw convected quantities or source terms
  include/ibamr/AdvDiffHierarchyIntegrator.h
  include/ibamr/AdvDiffSemiImplicitHierarchyIntegrator.h
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
  src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
Labels: enhancement

#654 Add ib interaction hierarchy
  doc/news/changes/incompatibilities/20190710DavidWells
  doc/news/changes/major/20191031DavidWells
  doc/news/changes/minor/20191104DavidWells
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.scratch_hier.input
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.scratch_hier.output
Labels: enhancement

#740 Fix test output.
  tests/IBFE/explicit_ex0.cpp
  tests/IBFE/explicit_ex0_2d.output
  tests/IBFE/explicit_ex8.cpp
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
Labels: Tests

#741 Avoid calculating an end iterator in a loop.
  doc/release-tasks.md
  ibtk/src/utilities/libmesh_utilities.cpp
Labels: libMesh

#742 Use array sizes for reductions.
  ibtk/src/lagrangian/LDataManager.cpp
  src/IB/CIBMethod.cpp
  src/IB/ConstraintIBMethod.cpp
  src/IB/IBFEDirectForcingKinematics.cpp
  src/IB/IBFESurfaceMethod.cpp
  src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
Labels: Bug

#745 update header file format
  ibtk/include/ibtk/FECache.h
  ibtk/include/ibtk/FEMapCache.h
  ibtk/include/ibtk/QuadratureCache.h
  include/ibamr/DirectMobilitySolver.h
  include/ibamr/KrylovMobilitySolver.h
  tests/multiphase_flow/LSLocateBargeInterface.h
  tests/multiphase_flow/LSLocateCircularInterface.h
  tests/multiphase_flow/LSLocateGasInterface.h
  tests/multiphase_flow/SetFluidGasSolidDensity.h
  tests/multiphase_flow/SetFluidGasSolidViscosity.h
  tests/multiphase_flow/SetLSProperties.h
Labels: Miscellaneous

#751 Multiple body force functions can be registered with INS integrators.
  doc/news/changes/minor/20191112AaronBarrett
  src/navier_stokes/INSHierarchyIntegrator.cpp
Labels: Bug

#753 Add an excluding regex option to attest.
  Makefile.am
  Makefile.in
  attest
Labels: Tests

#755 Disable OpenMP threading in the test suite.
  attest
Labels: Tests

#756 Improve the scratch hierarchy documentation.
  include/ibamr/IBFEMethod.h
Labels: Documentation

#757 Document some input parameters.
  include/ibamr/IBFEMethod.h
  include/ibamr/IBStrategy.h
Labels: Documentation

#758 Add release tasks
  doc/release-tasks.md
Labels: Documentation, Release

#761 Fix compatibility with libMesh 1.1.0.
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/utilities/libmesh_utilities.cpp
Labels: libMesh

#762 use hier::Index<NDIM> instead of Index<NDIM>
  ibtk/src/boundary/cf_interface/CartCellDoubleQuadraticCFInterpolation.cpp
  ibtk/src/boundary/physical_boundary/CartExtrapPhysBdryOp.cpp
  ibtk/src/boundary/physical_boundary/StaggeredPhysicalBoundaryHelper.cpp
  ibtk/src/boundary/physical_boundary/muParserRobinBcCoefs.cpp
  ibtk/src/coarsen_ops/LMarkerCoarsen.cpp
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/LDataManager.cpp
  ibtk/src/lagrangian/LEInteractor.cpp
  ibtk/src/lagrangian/LIndexSetData.cpp
  ibtk/src/math/PETScMatUtilities.cpp
  ibtk/src/math/PETScVecUtilities.cpp
  ibtk/src/math/PoissonUtilities.cpp
  ibtk/src/refine_ops/CartCellDoubleBoundsPreservingConservativeLinearRefine.cpp
  ibtk/src/refine_ops/CartCellDoubleQuadraticRefine.cpp
  ibtk/src/refine_ops/CartSideDoubleDivPreservingRefine.cpp
  ibtk/src/refine_ops/LMarkerRefine.cpp
  ibtk/src/solvers/impls/CCPoissonBoxRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp
  ibtk/src/utilities/DebuggingUtilities.cpp
  ibtk/src/utilities/LMarkerUtilities.cpp
  ibtk/src/utilities/muParserCartGridFunction.cpp
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  src/IB/IBHydrodynamicForceEvaluator.cpp
  src/IB/IBInstrumentPanel.cpp
  src/IB/IBMethod.cpp
  src/IB/IMPMethod.cpp
  src/IB/NonbondedForceEvaluator.cpp
  src/IB/WallForceEvaluator.cpp
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
  src/adv_diff/AdvDiffPhysicalBoundaryUtilities.cpp
  src/adv_diff/AdvDiffPredictorCorrectorHyperbolicPatchOps.cpp
  src/adv_diff/AdvDiffStochasticForcing.cpp
  src/advect/AdvectorExplicitPredictorPatchOps.cpp
  src/advect/AdvectorPredictorCorrectorHyperbolicPatchOps.cpp
  src/level_set/RelaxationLSBcCoefs.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSCollocatedVelocityBcCoef.cpp
  src/navier_stokes/INSProjectionBcCoef.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredPressureBcCoef.cpp
  src/navier_stokes/INSStaggeredStabilizedPPMConvectiveOperator.cpp
  src/navier_stokes/INSStaggeredStochasticForcing.cpp
  src/navier_stokes/INSStaggeredVelocityBcCoef.cpp
  src/navier_stokes/INSVCStaggeredConservativeMassMomentumIntegrator.cpp
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredPressureBcCoef.cpp
  src/navier_stokes/INSVCStaggeredVelocityBcCoef.cpp
  src/navier_stokes/SpongeLayerForceFunction.cpp
  src/navier_stokes/StaggeredStokesBoxRelaxationFACOperator.cpp
  src/navier_stokes/StaggeredStokesOpenBoundaryStabilizer.cpp
  src/navier_stokes/StaggeredStokesPETScMatUtilities.cpp
  src/navier_stokes/StaggeredStokesPETScVecUtilities.cpp
  src/navier_stokes/StaggeredStokesPhysicalBoundaryHelper.cpp
  src/wave_generation/StokesFirstOrderWaveBcCoef.cpp
  src/wave_generation/StokesSecondOrderWaveBcCoef.cpp
Labels: Miscellaneous

#764 Jacobian Calculator
  Makefile.in
  doc/news/changes/minor/20191122JordanBrown
  ibtk/Makefile.in
  ibtk/include/ibtk/JacobianCalculator.h
  ibtk/include/ibtk/JacobianCalculatorCache.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/JacobianCalculator.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/jacobian_calc_01.cpp
  tests/IBTK/jacobian_calc_01.input
  tests/IBTK/jacobian_calc_01.output
Labels: enhancement, libMesh

#768 Add the developer certificate of origin.
  CONTRIBUTING.md
Labels: Miscellaneous

#769 Add two more notes to release tasks.
  doc/release-tasks.md
Labels: Documentation
