Repository IBAMR/IBAMR, pull requests merged in 2019-02, with the labels that each got.

#457 use PetscVector::get_array_read() to access local form arrays in FEDataManager
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement, libMesh

#461 Refactor data reinitialization in IBFEMethod.
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement

#462 Clear the system dof cache on partitioning.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement

#463 Partitioning 2c
  ibtk/include/ibtk/BoxPartitioner.h
  ibtk/include/ibtk/PartitioningBox.h
  ibtk/include/ibtk/private/PartitioningBox-inl.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/lagrangian/BoxPartitioner.cpp
  ibtk/src/utilities/PartitioningBox.cpp
Labels: SAMRAI, enhancement, libMesh

#467 Partitioning 2d
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement

#475 Clear stale data after repartitioning.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: libMesh

#481 Improve the performance of SystemDofMapCache.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataInterpolation.cpp
  ibtk/src/lagrangian/FEDataManager.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
Labels: enhancement, libMesh

#479 Partitioning 2g
  examples/IBFE/explicit/ex4/example.cpp
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/IBFEMethod.h
  include/ibamr/ibamr_enums.h
  src/IB/IBFEMethod.cpp
  src/IB/IBHierarchyIntegrator.cpp
Labels: enhancement, libMesh

#484 Fix deletion order for some libMesh objects.
  include/ibamr/IBFEInstrumentPanel.h
Labels: Bug

#486 Fix compatibility with libMesh 1.1.
  ibtk/src/lagrangian/BoxPartitioner.cpp
Labels: libMesh

#485 Clean up the libMesh detection scripts a bit.
  configure
  doc/news/changes/minor/20190221DavidWells
  ibtk/configure
  ibtk/m4/configure_libmesh.m4
  m4/configure_libmesh.m4
Labels: Build System

#483 Workload fixes
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: Bug
