Repository IBAMR/IBAMR, pull requests merged in 2019-09, with the labels that each got.

#667 Rename a test to be much shorter.
  tests/physical_boundary/01_2d.cell.dirichlet.linear.input
  tests/physical_boundary/01_2d.cell.dirichlet.linear.output
  tests/physical_boundary/01_2d.cell.dirichlet.quadratic.input
  tests/physical_boundary/01_2d.cell.dirichlet.quadratic.output
  tests/physical_boundary/01_2d.cell.neumann.linear.input
  tests/physical_boundary/01_2d.cell.neumann.linear.output
  tests/physical_boundary/01_2d.cell.neumann.quadratic.input
  tests/physical_boundary/01_2d.cell.neumann.quadratic.output
  tests/physical_boundary/01_2d.side.dirichlet.linear.input
  tests/physical_boundary/01_2d.side.dirichlet.linear.output
  tests/physical_boundary/01_2d.side.dirichlet.quadratic.input
  tests/physical_boundary/01_2d.side.dirichlet.quadratic.output
  tests/physical_boundary/01_2d.side.neumann.linear.input
  tests/physical_boundary/01_2d.side.neumann.linear.output
  tests/physical_boundary/01_2d.side.neumann.quadratic.input
  tests/physical_boundary/01_2d.side.neumann.quadratic.output
  tests/physical_boundary/01_3d.cell.dirichlet.linear.input
  tests/physical_boundary/01_3d.cell.dirichlet.linear.output
  tests/physical_boundary/01_3d.cell.dirichlet.quadratic.input
  tests/physical_boundary/01_3d.cell.dirichlet.quadratic.output
  tests/physical_boundary/01_3d.cell.neumann.linear.input
  tests/physical_boundary/01_3d.cell.neumann.linear.output
  tests/physical_boundary/01_3d.cell.neumann.quadratic.input
  tests/physical_boundary/01_3d.cell.neumann.quadratic.output
  tests/physical_boundary/01_3d.side.dirichlet.linear.input
  tests/physical_boundary/01_3d.side.dirichlet.linear.output
  tests/physical_boundary/01_3d.side.dirichlet.quadratic.input
  tests/physical_boundary/01_3d.side.dirichlet.quadratic.output
  tests/physical_boundary/01_3d.side.neumann.linear.input
  tests/physical_boundary/01_3d.side.neumann.linear.output
  tests/physical_boundary/01_3d.side.neumann.quadratic.input
  tests/physical_boundary/01_3d.side.neumann.quadratic.output
  tests/physical_boundary/Makefile.am
  tests/physical_boundary/Makefile.in
Labels: Tests

#670 Update attest
  attest
Labels: Tests

#666 Silence a bogus boost warning.
  ibtk/include/ibtk/libmesh_utilities.h
Labels: Miscellaneous

#669 Higher order element support in get_max_edge_length
  ibtk/include/ibtk/libmesh_utilities.h
  tests/IBTK/elem_hmax_02.cpp
  tests/IBTK/elem_hmax_02.output
Labels: enhancement, libMesh

#674 Refactor fe data manager 1
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: libMesh

#678 Silence a muParser warning.
  ibtk/contrib/muparser/include/muParserBytecode.h
  ibtk/contrib/muparser/src/muParserBase.cpp
  ibtk/contrib/muparser/src/muParserBytecode.cpp
Labels: External Libraries, enhancement

#680 Make FEDataManager no longer inherit from FEData.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement, libMesh

#681 zero IB forces in the right place
  doc/news/changes/major/20190919BoyceGriffith
  ibtk/src/lagrangian/LDataManager.cpp
Labels: Bug

#688 Add a document describing the release process.
  doc/release-tasks.md
Labels: Documentation

#687 Fix a path fed to rpath.
  configure
  doc/news/changes/minor/20190920DavidWells
  ibtk/configure
  m4/configure_hdf5.m4
  m4/configure_hypre.m4
  m4/configure_petsc.m4
  m4/configure_silo.m4
Labels: Bug, Build System

#692 zero IB forces in the right place
  ibtk/src/lagrangian/LDataManager.cpp
Labels: Release

#694 Add a changelog list for 0.5.1.
  doc/news/changes/0.5.0-vs-0.5.1.html
Labels: Release

#695 Bump version number to 0.5.1
  VERSION
Labels: Release

#689 Remove some debugging messages from configure.
  configure
  ibtk/configure
Labels: Build System

#679 Redo fe cache
  doc/news/changes/incompatibilities/20190916DavidWells
  ibtk/include/ibtk/FECache.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: Bug, enhancement

#699 Create new test with inactivated structure
  Makefile.in
  ibtk/Makefile.in
  tests/IB/Makefile.am
  tests/IB/Makefile.in
  tests/IB/curve2d_64.spring
  tests/IB/curve2d_64.vertex
  tests/IB/explicit_ex1.cpp
  tests/IB/explicit_ex1.input
  tests/IB/explicit_ex1.output
Labels: Tests

#696 Silence a warning from Intel's compiler.
  ibtk/src/math/PETScMatUtilities.cpp
Labels: Miscellaneous

#700 Add restart test
  attest
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBFE/explicit_ex4_2d.restart=50.input
  tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.input
  tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.restart=50.output
Labels: Bug

#701 Actually fix the restart test.
  tests/IBFE/explicit_ex4.cpp
Labels: Bug

#702 Add a new 2D serial test.
  tests/IBFE/explicit_ex4_2d.input
  tests/IBFE/explicit_ex4_2d.mpirun=5.input
  tests/IBFE/explicit_ex4_2d.output
Labels: Tests
