Repository IBAMR/IBAMR, pull requests merged in 2019-10, with the labels that each got.

#703 Add test for IBFECentroidPostProcessor.
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.postprocessor.input
  tests/IBFE/explicit_ex4_2d.postprocessor.output
Labels: Tests

#705 Add FEData::clearCached().
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: Miscellaneous

#708 attest: allow -j (without a number) for all cores.
  attest
Labels: Tests

#709 Fix some pylint complaints about attest.
  attest
Labels: Tests

#706 Include a python script Aaron wrote.
  doc/news/changes/minor/20190730AaronBarretDavidWells
  scripts/make_visit_file.py
Labels: Miscellaneous

#712 Change the default q point weight to 1.0.
  ibtk/include/ibtk/FEDataManager.h
Labels: Miscellaneous

#710 Improve some doxygen formatting and links.
  ibtk/include/ibtk/FEDataManager.h
Labels: Documentation

#704 Allow FEDataManagers to share one FEData object.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.a.postprocessor.input
  tests/IBFE/explicit_ex4_2d.a.postprocessor.output
Labels: enhancement, libMesh

#711 Add a pointer check to FEDataManager.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: Miscellaneous

#673 Consistently check ifstream states.
  doc/news/changes/minor/20190919DavidWells
  doc/news/changes/minor/20190920DavidWells
  examples/ConstraintIB/flow_past_cylinder_HF/HydroForceEval.cpp
  ibtk/src/utilities/LMarkerUtilities.cpp
  include/ibamr/IBStandardInitializer.h
  src/IB/CIBMethod.cpp
  src/IB/IBStandardInitializer.cpp
Labels: enhancement

#718 Update test output following #673.
  tests/IB/explicit_ex1.output
Labels: Tests

#716 Refactor computeActiveElementBoundingBoxes.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/utilities/libmesh_utilities.cpp
Labels: enhancement

#719 Add a parallel postprocessor test.
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
Labels: Tests

#720 Rearrange things to permit the scratch hierarchy.
  include/ibamr/IBFEMethod.h
  src/IB/CIBFEMethod.cpp
  src/IB/IBFEMethod.cpp
Labels: enhancement

#723 account for changes in PETSc 3.12
  ibtk/src/solvers/impls/PETScNewtonKrylovSolver.cpp
Labels: External Libraries

#724 Use a robust partitioner in some libmesh tests.
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
  tests/IBFE/explicit_ex4_3d.mpirun=4.output
  tests/spread/spread_01.cpp
Labels: Tests

#727 Add some tests based on IBFE/explicit/ex8.
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/explicit_ex8.cpp
  tests/IBFE/explicit_ex8_2d.input
  tests/IBFE/explicit_ex8_2d.mpirun=4.input
  tests/IBFE/explicit_ex8_2d.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.output
Labels: Tests

#707 added documentation for the jacobian function in libmesh_utilities.h
  ibtk/include/ibtk/libmesh_utilities.h
Labels: Documentation
