Repository IBAMR/IBAMR, pull requests merged in 2019-03, with the labels that each got.

#489 Replace std::ostringstream with std::to_string (2) Issue #388
  ibtk/src/boundary/physical_boundary/muParserRobinBcCoefs.cpp
  ibtk/src/lagrangian/LDataManager.cpp
  ibtk/src/lagrangian/LSiloDataWriter.cpp
  ibtk/src/solvers/impls/BGaussSeidelPreconditioner.cpp
  ibtk/src/solvers/impls/BJacobiPreconditioner.cpp
  ibtk/src/solvers/impls/CCPoissonBoxRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/CCPoissonLevelRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/SCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/VCSCViscousOpPointRelaxationFACOperator.cpp
  ibtk/src/solvers/interfaces/FACPreconditionerStrategy.cpp
  ibtk/src/utilities/AppInitializer.cpp
  ibtk/src/utilities/muParserCartGridFunction.cpp
Labels: C++11, Miscellaneous

#495 Cache interpolated positions.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement

#497 Fix bug with empty string.
  ibtk/src/utilities/AppInitializer.cpp
Labels: Bug

#498 Add some missing changelog entries.
  doc/news/changes/major/20181012BoyceGriffith
  doc/news/changes/major/20190125DavidWells
  doc/news/changes/major/20190219DavidWells
  doc/news/changes/major/20190321Multiple
Labels: Documentation

#502 Update deprecated lib mesh 0.4
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEPostProcessor.h
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBFEMethod.cpp
Labels: Release

#503 Fix a signed integer comparison warning.
  ibtk/src/lagrangian/BoxPartitioner.cpp
Labels: Release

#504 Fix the previous patch.
  src/IB/IBFEInstrumentPanel.cpp
Labels: Release, libMesh

#511 Don't write some output in 3D.
  examples/IBFE/explicit/ex4/example.cpp
Labels: Release
