Repository IBAMR/IBAMR, pull requests merged in 2019-01, with the labels that each got.

#428 Fix alignment of Eigen objects.
  ibtk/include/ibtk/ibtk_utilities.h
  include/ibamr/CIBMethod.h
  include/ibamr/CIBStrategy.h
  include/ibamr/ConstraintIBMethod.h
  include/ibamr/IBFEDirectForcingKinematics.h
  include/ibamr/IBHydrodynamicForceEvaluator.h
  src/IB/CIBFEMethod.cpp
  src/IB/CIBMethod.cpp
  src/IB/CIBStrategy.cpp
Labels: Miscellaneous

#433 eliminate some calls to NumericVector<T>::close()
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement

#437 Add IBTK::FECache.
  ibtk/include/ibtk/FECache.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement, libMesh
