Repository IBAMR/IBAMR, pull requests merged in 2019-06, with the labels that each got.

#612 Add a missing symbolic link.
  ibtk/m4/configure_petsc.m4
Labels: Build System

#614 Add more interpolation tests.
  tests/IBFE/interpolate_velocity_01.b.bspline-3.input
  tests/IBFE/interpolate_velocity_01.b.bspline-3.output
  tests/IBFE/interpolate_velocity_01.b.bspline-4.input
  tests/IBFE/interpolate_velocity_01.b.bspline-4.output
  tests/IBFE/interpolate_velocity_01.b.bspline-5.input
  tests/IBFE/interpolate_velocity_01.b.bspline-5.output
  tests/IBFE/interpolate_velocity_01.b.bspline-6.input
  tests/IBFE/interpolate_velocity_01.b.bspline-6.output
  tests/IBFE/interpolate_velocity_01.b.ib-3.input
  tests/IBFE/interpolate_velocity_01.b.ib-3.output
  tests/IBFE/interpolate_velocity_01.b.piecewise-cubic.input
  tests/IBFE/interpolate_velocity_01.b.piecewise-cubic.output
  tests/IBFE/interpolate_velocity_01.cpp
Labels: Tests

#616 Avoid using Triangle in the interpolation tests.
  tests/IBFE/interpolate_velocity_01.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.a.output
  tests/IBFE/interpolate_velocity_01.b.bspline-3.output
  tests/IBFE/interpolate_velocity_01.b.bspline-4.output
  tests/IBFE/interpolate_velocity_01.b.bspline-5.output
  tests/IBFE/interpolate_velocity_01.b.bspline-6.output
  tests/IBFE/interpolate_velocity_01.b.ib-3.output
  tests/IBFE/interpolate_velocity_01.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.b.output
  tests/IBFE/interpolate_velocity_01.b.piecewise-cubic.output
  tests/IBFE/interpolate_velocity_01.c.mpirun=4.input
  tests/IBFE/interpolate_velocity_01.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.c.output
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBFE/interpolate_velocity_01.d.cached.mpirun=4.input
  tests/IBFE/interpolate_velocity_01.d.ghosted.mpirun=4.input
  tests/IBFE/interpolate_velocity_01.d.mpirun=4.input
  tests/IBFE/interpolate_velocity_01.d.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.d.output
Labels: Tests, libMesh

#619 Add more spread and interpolation tests.
  tests/IBFE/interpolate_velocity_01_2d.b.discontinuous-linear.input
  tests/IBFE/interpolate_velocity_01_2d.b.discontinuous-linear.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-4-w8.input
  tests/IBFE/interpolate_velocity_01_2d.b.ib-4-w8.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-4.input
  tests/IBFE/interpolate_velocity_01_2d.b.ib-4.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-5.input
  tests/IBFE/interpolate_velocity_01_2d.b.ib-5.output
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-constant.input
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-constant.output
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-linear.input
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-linear.output
  tests/IBFE/interpolate_velocity_01_3d.b.discontinuous-linear.input
  tests/IBFE/interpolate_velocity_01_3d.b.discontinuous-linear.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-4-w8.input
  tests/IBFE/interpolate_velocity_01_3d.b.ib-4-w8.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-4.input
  tests/IBFE/interpolate_velocity_01_3d.b.ib-4.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-5.input
  tests/IBFE/interpolate_velocity_01_3d.b.ib-5.output
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-constant.input
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-constant.output
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-linear.input
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-linear.output
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.bspline_5.input
  tests/spread/spread_01_2d.bspline_5.output
  tests/spread/spread_01_2d.bspline_6.input
  tests/spread/spread_01_2d.bspline_6.output
  tests/spread/spread_01_2d.ib_4_w8.input
  tests/spread/spread_01_2d.ib_4_w8.output
  tests/spread/spread_01_2d.ib_5.input
  tests/spread/spread_01_2d.ib_5.output
  tests/spread/spread_01_3d.bspline_5.input
  tests/spread/spread_01_3d.bspline_5.output
  tests/spread/spread_01_3d.bspline_6.input
  tests/spread/spread_01_3d.bspline_6.output
  tests/spread/spread_01_3d.ib_4_w8.input
  tests/spread/spread_01_3d.ib_4_w8.output
  tests/spread/spread_01_3d.ib_5.input
  tests/spread/spread_01_3d.ib_5.output
Labels: Tests

#624 Add some missing generated code.
  ibtk/config/IBTK_config.h.tmp.in
  ibtk/configure
Labels: Build System

#618 Use F95's FLOOR instead of lagrangian_floor.
  ibtk/src/lagrangian/fortran/lagrangian_delta.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
Labels: enhancement

#623 Verify consistent debug settings.
  configure
  configure.ac
  ibtk/configure
  ibtk/configure.ac
Labels: Build System

#621 Get rid of warnings in clang.
  ibtk/include/ibtk/ibtk_macros.h
Labels: enhancement

#626 NWT: correctly normalize quaternions.
  doc/news/changes/minor/20181210AmneetBhalla
  src/IB/CIBFEMethod.cpp
  src/IB/CIBMethod.cpp
  src/IB/IBFEDirectForcingKinematics.cpp
Labels: Bug

#632 Convert adv_diff tests to the new style.
  configure
  configure.ac
  tests/Makefile.am
  tests/Makefile.in
  tests/adv_diff/Makefile.am
  tests/adv_diff/Makefile.in
  tests/adv_diff/QInit.h
  tests/adv_diff/UFunction.h
  tests/adv_diff/adv_diff_01.cpp
  tests/adv_diff/adv_diff_01_2d.input
  tests/adv_diff/adv_diff_01_2d.output
  tests/adv_diff/adv_diff_01_3d.input
  tests/adv_diff/adv_diff_01_3d.output
  tests/adv_diff/adv_diff_02.cpp
  tests/adv_diff/adv_diff_02_2d.input
  tests/adv_diff/adv_diff_02_2d.output
  tests/adv_diff/adv_diff_02_3d.mpirun=2.input
  tests/adv_diff/adv_diff_02_3d.mpirun=2.output
  tests/adv_diff/adv_diff_02_3d.mpirun=8.input
  tests/adv_diff/adv_diff_02_3d.mpirun=8.output
  tests/adv_diff/adv_diff_03.cpp
  tests/adv_diff/adv_diff_03_2d.input
  tests/adv_diff/adv_diff_03_2d.output
Labels: Tests

#625 NWT: Brinkman
  doc/news/changes/major/20190624AmneetBhalla
  include/ibamr/BrinkmanPenalizationRigidBodyDynamics.h
  include/ibamr/BrinkmanPenalizationStrategy.h
  lib/Makefile.am
  lib/Makefile.in
  src/IB/BrinkmanPenalizationRigidBodyDynamics.cpp
  src/IB/BrinkmanPenalizationStrategy.cpp
Labels: enhancement

#634 fix contrib dir path in ibtk
  ibtk/configure
  ibtk/configure.ac
Labels: Bug, Build System
