Repository IBAMR/IBAMR, pull requests merged in 2020-04, with the labels that each got.

#954 Add more tests for spreading.
  tests/spread/spread_01_2d.square.c.bspline_4.input
  tests/spread/spread_01_2d.square.c.bspline_4.mpirun=4.input
  tests/spread/spread_01_2d.square.c.bspline_4.mpirun=4.output
  tests/spread/spread_01_2d.square.c.bspline_4.output
  tests/spread/spread_01_3d.cube.b.bspline_4.input
  tests/spread/spread_01_3d.cube.b.bspline_4.mpirun=4.input
  tests/spread/spread_01_3d.cube.b.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.b.bspline_4.output
Labels: Tests

#896 all changes for redoing force spreading
  doc/news/changes/major/20200331DavidWells
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=2.output
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=6.output
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=2.output
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=6.output
  tests/IBFE/ib_partitioning_02_2d.quad9.mpirun=2.output
  tests/IBFE/ib_partitioning_02_2d.tri6.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex27.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex8.mpirun=4.output
  tests/IBFE/zero_exterior_values.cpp
  tests/IBFE/zero_exterior_values_2d.input
  tests/IBFE/zero_exterior_values_2d.output
  tests/IBFE/zero_exterior_values_3d.input
  tests/IBFE/zero_exterior_values_3d.output
  tests/spread/spread_01.cpp
Labels: enhancement

#955 Fix tests added in 954.
  tests/spread/spread_01_2d.square.c.bspline_4.mpirun=4.input
  tests/spread/spread_01_2d.square.c.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.b.bspline_4.mpirun=4.input
Labels: Tests

#957 Fix interpolate velocity 01
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBFE/interpolate_velocity_01_2d.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.a.output
  tests/IBFE/interpolate_velocity_01_2d.b.bspline-3.output
  tests/IBFE/interpolate_velocity_01_2d.b.bspline-4.output
  tests/IBFE/interpolate_velocity_01_2d.b.bspline-5.output
  tests/IBFE/interpolate_velocity_01_2d.b.bspline-6.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-3.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-4-w8.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-4.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-5.output
  tests/IBFE/interpolate_velocity_01_2d.b.ib-6.output
  tests/IBFE/interpolate_velocity_01_2d.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.b.output
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-cubic.output
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-linear.output
  tests/IBFE/interpolate_velocity_01_2d.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.c.output
  tests/IBFE/interpolate_velocity_01_2d.d.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.d.output
  tests/IBFE/interpolate_velocity_01_3d.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.a.output
  tests/IBFE/interpolate_velocity_01_3d.b.bspline-3.output
  tests/IBFE/interpolate_velocity_01_3d.b.bspline-4.output
  tests/IBFE/interpolate_velocity_01_3d.b.bspline-5.output
  tests/IBFE/interpolate_velocity_01_3d.b.bspline-6.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-3.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-4-w8.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-4.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-5.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-6.output
  tests/IBFE/interpolate_velocity_01_3d.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.b.output
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-cubic.output
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-linear.output
  tests/IBFE/interpolate_velocity_01_3d.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.c.output
Labels: Bug, Tests

#952 fix nodal interaction
  doc/news/changes/major/20200403BoyceGriffith
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.input
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.input
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.a.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.a.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.a.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.b.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.b.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.b.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.c.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.c.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.c.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.a.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.a.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.a.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.b.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.b.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.b.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.c.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.c.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.c.output
Labels: Bug

#958 Fix test again
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBFE/interpolate_velocity_01_2d.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.d.ghosted.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.d.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.c.cached.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.c.ghosted.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.c.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.a.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.c.mpirun=4.output
Labels: Tests

#959 add support for different time stepping schemes in IBFEMethod
  doc/news/changes/major/20200405BoyceGriffith
  ibtk/include/ibtk/ibtk_utilities.h
  include/ibamr/IBFEMethod.h
  include/ibamr/IBHierarchyIntegrator.h
  src/IB/IBFEMethod.cpp
  src/IB/IBHierarchyIntegrator.cpp
  tests/IBFE/explicit_ex4_2d.FORWARD_EULER.input
  tests/IBFE/explicit_ex4_2d.FORWARD_EULER.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.FORWARD_EULER.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.FORWARD_EULER.output
  tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.input
  tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.output
Labels: High Priority :warning:, enhancement

#961 Implement contravariants
  ibtk/include/ibtk/JacobianCalculator.h
  ibtk/include/ibtk/JacobianCalculatorCache.h
  ibtk/src/lagrangian/JacobianCalculator.cpp
  tests/IBTK/jacobian_calc_01.cpp
Labels: libMesh

#964 Fix a memory consumption bug in SAMRAIGhostDataAccumulator.
  ibtk/src/math/SAMRAIGhostDataAccumulator.cpp
Labels: Bug

#963 Remove most calls to localize.
  doc/news/changes/major/20200408DavidWells
  examples/IBFE/explicit/ex0/example.cpp
  examples/IBFE/explicit/ex1/example.cpp
  examples/IBFE/explicit/ex11/example.cpp
  examples/IBFE/explicit/ex4/example.cpp
  examples/IBFE/explicit/ex5/example.cpp
  examples/IBFE/explicit/ex6/example.cpp
  examples/IBFE/explicit/ex9/example.cpp
  src/IB/IBFECentroidPostProcessor.cpp
  src/IB/IBFEDirectForcingKinematics.cpp
  src/IB/IBFEPostProcessor.cpp
  tests/IBFE/explicit_ex0.cpp
  tests/IBFE/explicit_ex1.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex5.cpp
Labels: Bug, libMesh

#962 allow users to set outflow_bdry_extrap_type in AdvDiffWavePropConvectiveOperator
  doc/news/changes/minor/20200408BoyceGriffith
  src/adv_diff/AdvDiffWavePropConvectiveOperator.cpp
  tests/adv_diff/Makefile.am
  tests/adv_diff/Makefile.in
  tests/adv_diff/adv_diff_convec_opers.cpp
  tests/adv_diff/adv_diff_convec_opers_2d.constant.input
  tests/adv_diff/adv_diff_convec_opers_2d.constant.output
  tests/adv_diff/adv_diff_convec_opers_2d.linear.input
  tests/adv_diff/adv_diff_convec_opers_2d.linear.output
  tests/adv_diff/adv_diff_convec_opers_2d.none.input
  tests/adv_diff/adv_diff_convec_opers_2d.none.output
  tests/adv_diff/adv_diff_convec_opers_2d.quadratic.input
  tests/adv_diff/adv_diff_convec_opers_2d.quadratic.output
  tests/adv_diff/adv_diff_convec_opers_3d.constant.input
  tests/adv_diff/adv_diff_convec_opers_3d.constant.output
  tests/adv_diff/adv_diff_convec_opers_3d.linear.input
  tests/adv_diff/adv_diff_convec_opers_3d.linear.output
  tests/adv_diff/adv_diff_convec_opers_3d.none.input
  tests/adv_diff/adv_diff_convec_opers_3d.none.output
  tests/adv_diff/adv_diff_convec_opers_3d.quadratic.input
  tests/adv_diff/adv_diff_convec_opers_3d.quadratic.output
Labels: enhancement

#967 split LibMeshSystemVectors into base and derived classes
  ibtk/include/ibtk/LibMeshSystemIBVectors.h
  ibtk/include/ibtk/LibMeshSystemVectors.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/utilities/LibMeshSystemIBVectors.cpp
  ibtk/src/utilities/LibMeshSystemVectors.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement, libMesh

#968 factor out L2 projection code into new class FEProjector
  doc/news/changes/minor/20200414BoyceGriffith
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/FEProjector.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/FEProjector.cpp
Labels: enhancement, libMesh

#972 Fix test output related to FEProjector.
  tests/IBFE/explicit_ex4_2d.a.postprocessor.output
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
  tests/IBFE/explicit_ex4_2d.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.output
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.postprocessor.output
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.restart=50.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
Labels: Tests

#971 avoid using FEDataManager in FEDataInterpolation
  doc/news/changes/minor/20200416BoyceGriffith
  ibtk/include/ibtk/FEDataInterpolation.h
  ibtk/src/lagrangian/FEDataInterpolation.cpp
  src/IB/IBFECentroidPostProcessor.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
Labels: enhancement, libMesh

#974 Add compute q points
  ibtk/include/ibtk/FECache.h
  ibtk/include/ibtk/JacobianCalculator.h
  ibtk/include/ibtk/JacobianCalculatorCache.h
  ibtk/src/lagrangian/JacobianCalculator.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/jacobian_calc_01.cpp
  tests/IBTK/mapping_01.cpp
  tests/IBTK/mapping_01.input
  tests/IBTK/mapping_01.output
Labels: libMesh

#975 Fix IBFESurfaceMethod regrid.
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex5_2d.regrid.mpirun=2.input
  tests/IBFE/explicit_ex5_2d.regrid.mpirun=2.output
Labels: Bug

#978 Fix nodal workload
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.input
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.input
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.output
Labels: libMesh

#980 Fix some warnings with clang 10.
  ibtk/include/ibtk/LibMeshSystemVectors.h
  ibtk/src/lagrangian/FEDataManager.cpp
  src/IB/IBFEMethod.cpp
Labels: Miscellaneous

#979 Fix a busy wait problem in attest.
  attest
Labels: Tests

#981 Fix the merging algorithm used by MergingLoadBalancer.
  ibtk/src/utilities/box_utilities.cpp
Labels: Bug
