Repository IBAMR/IBAMR, pull requests merged in 2020-07, with the labels that each got.

#1027 Fix some warnings.
  src/IB/IBMethod.cpp
  src/navier_stokes/INSVCStaggeredConservativeMassMomentumIntegrator.cpp
Labels: Miscellaneous

#1026 Prevent some code from being overoptimized.
  doc/news/changes/minor/20200629DavidWells
  ibtk/include/ibtk/libmesh_utilities.h
Labels: Bug, but definitely not our fault :rage:

#1031 Fix compilation with libMesh 1.1.0.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: Release

#1030 Add another missing header.
  ibtk/include/ibtk/libmesh_utilities.h
Labels: Miscellaneous

#1025 Fix some uninitialized variable warnings.
  src/wave_generation/IrregularWaveBcCoef.cpp
  src/wave_generation/StokesFifthOrderWaveBcCoef.cpp
Labels: Miscellaneous

#1034 Fix an ABI problem in some Fortran code.
  include/ibamr/AdvectorExplicitPredictorPatchOps.h
  src/advect/AdvectorExplicitPredictorPatchOps.cpp
  src/advect/fortran/advect_predictors3d.f.m4
Labels: Fortran, Miscellaneous

#1036 Add and fix some more AMR + FE tests.
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.amr-2.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.amr-2.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.amr.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.amr.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.amr.restart=50.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.amr.restart=50.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.grid-1-amr.xdr
Labels: libMesh

#1037 Remove an extra line from a test
  tests/IBFE/explicit_ex4_2d.amr.restart=50.mpirun=4.output
Labels: Tests

#1035 Move a Fortran function used in IBTK into IBTK.
  ibtk/src/refine_ops/fortran/Makefile.am
  ibtk/src/refine_ops/fortran/Makefile.in
  ibtk/src/refine_ops/fortran/cart_side_helpers.f.m4
  ibtk/src/refine_ops/fortran/cart_side_refine2d.f.m4
  ibtk/src/refine_ops/fortran/cart_side_refine3d.f.m4
  src/advect/fortran/advect_helpers.f.m4
Labels: Fortran, Miscellaneous

#1038 Remove a stray emacs file.
  .dir-locals.el
Labels: Miscellaneous

#1041 Remove CACHED assembly from IBFEMethod.
  doc/news/changes/minor/20200714DavidWells
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/IBFE/interpolate_velocity_01_2d.d.cached.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_2d.d.cached.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.d.ghosted.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_2d.d.ghosted.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.c.cached.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_3d.c.cached.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_3d.c.ghosted.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_3d.c.ghosted.mpirun=4.output
Labels: Bug

#1042 Adding hierarchy callback tests
  include/ibamr/AdvDiffHierarchyIntegrator.h
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/hierarchy_callbacks.cpp
  tests/IBTK/hierarchy_callbacks.input
  tests/IBTK/hierarchy_callbacks.output
Labels: Tests

#1043 Added additional documentation for physical boundary conditions.
  ibtk/include/ibtk/muParserRobinBcCoefs.h
  include/ibamr/AdvDiffHierarchyIntegrator.h
  include/ibamr/INSHierarchyIntegrator.h
Labels: Documentation

#1039 Fix the ghost cell size given to SAMRAIGhostDataAccumulator.
  doc/news/changes/minor/2020713DavidWells
  src/IB/IBFEMethod.cpp
Labels: Bug, SAMRAI

#1044 Use the standard naming scheme for some tests.
  tests/level_set/Makefile.am
  tests/level_set/Makefile.in
  tests/level_set/fe_surface_distance_2d.input
  tests/level_set/fe_surface_distance_2d.mpirun=8.input
  tests/level_set/fe_surface_distance_2d.mpirun=8.output
  tests/level_set/fe_surface_distance_2d.output
  tests/level_set/fe_surface_distance_3d.input
  tests/level_set/fe_surface_distance_3d.mpirun=8.input
  tests/level_set/fe_surface_distance_3d.mpirun=8.output
  tests/level_set/fe_surface_distance_3d.output
  tests/level_set/fe_surface_distance_circle.mpirun=8.input
  tests/level_set/fe_surface_distance_circle.mpirun=8.output
  tests/level_set/fe_surface_distance_sphere.mpirun=8.input
  tests/level_set/fe_surface_distance_sphere.mpirun=8.output
  tests/physical_boundary/01.cpp
  tests/physical_boundary/Makefile.am
  tests/physical_boundary/Makefile.in
Labels: Tests

#1045 Associate exactly one source file per test.
  tests/vc_navier_stokes/Makefile.am
  tests/vc_navier_stokes/Makefile.in
  tests/vc_navier_stokes/vc_navier_stokes_01.cpp
  tests/wave_tank/Makefile.am
  tests/wave_tank/Makefile.in
  tests/wave_tank/SetFluidGasSolidDensity.cpp
  tests/wave_tank/SetFluidGasSolidViscosity.cpp
  tests/wave_tank/nwt_cylinder.cpp
Labels: Build System, Tests

#1048 Fix some warnings with hidden virtual functions.
  include/ibamr/CIBMethod.h
Labels: Miscellaneous

#1049 Fix hanging nodes plus nodal quad
  ibtk/include/ibtk/FEProjector.h
  ibtk/src/lagrangian/FEProjector.cpp
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.output
  tests/IBFE/explicit_ex4_2d.amr.nodal_quadrature.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBFE/interpolate_velocity_01_2d.amr.nodal_quadrature.a.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.tri3.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.tri3.output
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.tri6.input
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.tri6.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.tet10.input
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.tet10.output
  tests/spread/spread_01_2d.nodal_quadrature.a.input
  tests/spread/spread_01_2d.nodal_quadrature.a.mpirun=4.input
  tests/spread/spread_01_2d.nodal_quadrature.a.mpirun=4.output
  tests/spread/spread_01_2d.nodal_quadrature.a.output
Labels: Bug, libMesh

#1052 Use a better algorithm for L2 projection.
  doc/news/changes/major/20200723DavidWells
  ibtk/src/lagrangian/FEProjector.cpp
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.output
  tests/IBFE/explicit_ex4_2d.a.postprocessor.output
  tests/IBFE/explicit_ex4_2d.amr.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.amr.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.amr.restart=50.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
  tests/IBFE/explicit_ex4_2d.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.output
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.postprocessor.output
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.restart=50.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
Labels: enhancement, libMesh

#1054 Permit load balancing also by the number of (duplicated) nodes.
  doc/news/changes/minor/20200724DavidWells
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.output
Labels: enhancement

#1056 Remove the buggy IB6 delta function.
  doc/news/changes/incompatibilities/20200727DavidWells
  ibtk/src/lagrangian/fortran/lagrangian_delta.f.m4
Labels: Miscellaneous

#1055 Create timer manager before everything else.
  doc/news/changes/minor/20200727AaronBarrett
  ibtk/src/utilities/AppInitializer.cpp
Labels: Bug

#1060 Changed default MPI communicator for backwards compatibility
  examples/IB/explicit/ex0/example.cpp
  examples/IBFE/explicit/ex0/example.cpp
  ibtk/src/utilities/IBTK_MPI.cpp
  tests/IB/explicit_ex0.cpp
  tests/IBFE/explicit_ex0.cpp
Labels: Bug

#1059 Fe values fe interpolation
  doc/news/changes/major/20200519DavidWells
  ibtk/include/ibtk/FEDataInterpolation.h
  ibtk/include/ibtk/FEValues.h
  ibtk/src/lagrangian/FEDataInterpolation.cpp
  ibtk/src/lagrangian/FEValues.cpp
  tests/IBTK/fe_values_01.cpp
  tests/IBTK/fe_values_02.cpp
Labels: enhancement, libMesh
