Repository IBAMR/IBAMR, pull requests merged in 2020-06, with the labels that each got.

#1002 Fix the scratch hierarchy with more than two levels.
  doc/news/changes/minor/20200529DavidWells
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
Labels: Bug

#1005 Fix tests on Mac, part 1
  tests/IBFE/explicit_ex1.cpp
  tests/IBFE/explicit_ex1_2d.mpirun=4.output
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
  tests/IBFE/explicit_ex4_2d.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
  tests/IBFE/explicit_ex8.cpp
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
  tests/IBFE/ib_partitioning_01.cpp
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=2.output
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=6.output
  tests/IBFE/ib_partitioning_01_2d.tri3.b.mpirun=8.output
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=2.output
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=2.output
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=2.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=6.output
  tests/IBFE/ib_partitioning_02.cpp
  tests/IBFE/ib_partitioning_02_2d.quad9.mpirun=2.output
  tests/IBFE/ib_partitioning_02_2d.tri3.mpirun=4.output
  tests/IBFE/ib_partitioning_02_2d.tri6.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex27.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex8.mpirun=4.output
  tests/IBFE/interpolate_velocity_01.cpp
Labels: Tests

#1006 Fix tests on mac 2
  ibtk/include/ibtk/StableCentroidPartitioner.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/lagrangian/StableCentroidPartitioner.cpp
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/explicit_ex1.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.FORWARD_EULER.input
  tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.input
  tests/IBFE/explicit_ex4_2d.a.postprocessor.input
  tests/IBFE/explicit_ex4_2d.grid-1.xdr
  tests/IBFE/explicit_ex4_2d.grid-2.xdr
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.input
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
  tests/IBFE/explicit_ex4_2d.input
  tests/IBFE/explicit_ex4_2d.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.postprocessor.input
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.restart=50.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.source_test.input
  tests/IBFE/explicit_ex8.cpp
  tests/IBFE/ib_partitioning_01.cpp
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=6.output
  tests/IBFE/ib_partitioning_01_2d.tri3.b.mpirun=8.output
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=2.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=6.output
  tests/IBFE/ib_partitioning_02.cpp
  tests/IBFE/interpolate_velocity_01.cpp
  tests/adv_diff/Makefile.am
  tests/adv_diff/Makefile.in
  tests/adv_diff/adv_diff_01_2d.input
  tests/adv_diff/adv_diff_01_2d.output
  tests/spread/spread_01.cpp
Labels: Tests

#1004 Update IBFEMethod documentation.
  include/ibamr/IBFEMethod.h
Labels: Documentation

#1010 Fixing restart for IBLevelSet/ex0
  doc/news/changes/minor/20200612AmneetBhalla
  examples/IBLevelSet/ex0/example.cpp
Labels: Bug

#1011 Add some information on restart and input databases.
  doc/input-and-restart-databases.md
  doc/news/changes/major/20200612DavidWells
Labels: Documentation

#1012 Fix detection of newer versions of hypre.
  configure
  ibtk/configure
  m4/configure_hypre.m4
Labels: Build System

#1014 collate changelog entries for 0.7.0
  doc/news/changes/0.6.0-vs-0.7.0.html
  doc/news/changes/incompatibilities/20200131MarshallDavey
  doc/news/changes/incompatibilities/20200227DavidWells
  doc/news/changes/incompatibilities/20200303BoyceGriffith
  doc/news/changes/incompatibilities/20200311DavidWells
  doc/news/changes/incompatibilities/20200324DavidWells
  doc/news/changes/major/20200127DavidWells
  doc/news/changes/major/20200228DavidWells
  doc/news/changes/major/20200331DavidWells
  doc/news/changes/major/20200403BoyceGriffith
  doc/news/changes/major/20200405BoyceGriffith
  doc/news/changes/major/20200408DavidWells
  doc/news/changes/major/20200504BoyceGriffith
  doc/news/changes/major/20200612DavidWells
  doc/news/changes/major/2020127RamakrishnanThirumalaisamy
  doc/news/changes/minor/20200201DavidWells
  doc/news/changes/minor/20200207DavidWells
  doc/news/changes/minor/20200214NishantNangia
  doc/news/changes/minor/20200215DavidWells
  doc/news/changes/minor/20200220DavidWells
  doc/news/changes/minor/20200221AaronBarrett
  doc/news/changes/minor/20200221AaronBarrett_1
  doc/news/changes/minor/20200303AaronBarrett
  doc/news/changes/minor/20200306AaronBarrett
  doc/news/changes/minor/20200311DavidWells
  doc/news/changes/minor/20200312NishantNangia
  doc/news/changes/minor/20200316DavidWells
  doc/news/changes/minor/20200318DavidWells
  doc/news/changes/minor/20200319AaronBarrett
  doc/news/changes/minor/20200330DavidWells
  doc/news/changes/minor/20200408BoyceGriffith
  doc/news/changes/minor/20200414BoyceGriffith
  doc/news/changes/minor/20200416BoyceGriffith
  doc/news/changes/minor/20200523NishantNangia
  doc/news/changes/minor/20200527NishantNangia
  doc/news/changes/minor/20200528NishantNangia
  doc/news/changes/minor/20200529DavidWells
  doc/news/changes/minor/20200605DavidWells
  doc/news/changes/minor/20200612AmneetBhalla
  doc/news/changes/minor/2020121DavidWells
Labels: Documentation, Release

#1013 Minor release fixes
  COPYRIGHT
  examples/multiphase_flow/ex11/LevelSetSolidInitialCondition.cpp
  examples/multiphase_flow/ex11/LevelSetSolidInitialCondition.h
  examples/multiphase_flow/ex12/LevelSetSolidInitialCondition.cpp
  examples/multiphase_flow/ex12/LevelSetSolidInitialCondition.h
  examples/multiphase_flow/ex13/LevelSetGasInitialCondition.cpp
  examples/multiphase_flow/ex13/LevelSetGasInitialCondition.h
  examples/multiphase_flow/ex13/LevelSetSolidInitialCondition.cpp
  examples/multiphase_flow/ex13/LevelSetSolidInitialCondition.h
  examples/multiphase_flow/ex5/LevelSetInitialCondition.cpp
  examples/multiphase_flow/ex5/LevelSetInitialCondition.h
  examples/multiphase_flow/ex6/LevelSetInitialCondition.cpp
  examples/multiphase_flow/ex6/LevelSetInitialCondition.h
  examples/wave_tank/ex1/LevelSetSolidInitialCondition.cpp
  examples/wave_tank/ex1/LevelSetSolidInitialCondition.h
  ibtk/examples/GhostCells/TotalAmountRefineAndCoarsen.cpp
  ibtk/examples/GhostCells/TotalAmountRefineAndCoarsen.h
  ibtk/examples/GhostCells/example.cpp
  ibtk/include/ibtk/AppInitializer.h
  ibtk/include/ibtk/FEMapCache.h
  ibtk/include/ibtk/FEProjector.h
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/include/ibtk/IBTKInit.h
  ibtk/include/ibtk/JacobianCalculatorCache.h
  ibtk/include/ibtk/MergingLoadBalancer.h
  ibtk/include/ibtk/QuadratureCache.h
  ibtk/include/ibtk/StableCentroidPartitioner.h
  ibtk/include/ibtk/box_utilities.h
  ibtk/include/ibtk/private/IBTK_MPI-inl.h
  ibtk/include/ibtk/private/LSet-inl.h
  ibtk/include/ibtk/private/LSetDataIterator-inl.h
  ibtk/src/lagrangian/FEProjector.cpp
  ibtk/src/lagrangian/StableCentroidPartitioner.cpp
  ibtk/src/math/SAMRAIGhostDataAccumulator.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  ibtk/src/utilities/IBTKInit.cpp
  include/ibamr/IBStrategy.h
  include/ibamr/IrregularWaveGenerator.h
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/IB/IBFEPostProcessor.cpp
  src/complex_fluids/CFINSForcing.cpp
  src/wave_generation/IrregularWaveGenerator.cpp
  tests/CIB/cib_double_shell.cpp
  tests/CIB/cib_plate.cpp
  tests/IBTK/ghost_accumulation_01.cpp
  tests/IBTK/ibtk_init.cpp
  tests/adv_diff/adv_diff_convec_opers.cpp
  tests/level_set/fe_surface_distance.cpp
  tests/multiphase_flow/SetFluidProperties.h
  tests/multiphase_flow/VelocityInitialCondition.h
  tests/multiphase_flow/high_density_droplet.cpp
  tests/vc_navier_stokes/SetFluidProperties.cpp
  tests/vc_navier_stokes/SetFluidProperties.h
  tests/vc_navier_stokes/vc_navier_stokes_01.cpp
Labels: Release

#1018 Fix some tests with libMesh 1.2.1.
  tests/IBFE/explicit_ex4_2d.grid-1.xdr
  tests/IBFE/explicit_ex4_2d.grid-2.xdr
Labels: Release, Tests, libMesh

#1017 Fix some tests with libMesh 1.2.1.
  tests/IBFE/explicit_ex4_2d.grid-1.xdr
  tests/IBFE/explicit_ex4_2d.grid-2.xdr
Labels: Tests, libMesh

#1016 Bump version to 0.8.0-pre
  VERSION
Labels: Release

#1019 Fix an automake path.
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
Labels: Build System

#1021 Add a missing header.
  ibtk/src/lagrangian/StableCentroidPartitioner.cpp
Labels: Miscellaneous

#1023 Bug fixes to compute time steps in parallel.
  doc/news/changes/minor/20200626AaronBarrett
  ibtk/include/ibtk/HierarchyIntegrator.h
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
Labels: Bug
