Repository IBAMR/IBAMR, pull requests merged in 2020-01, with the labels that each got.

#817 Improve attest
  attest
Labels: Tests

#825 slight performance improvement.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement

#823 Remove strdup
  ibtk/src/lagrangian/LSiloDataWriter.cpp
Labels: Miscellaneous

#798 Use std::expm1 where appropriate.
  src/wave_generation/WaveDampingFunctions.cpp
  src/wave_generation/WaveGenerationFunctions.cpp
Labels: enhancement

#796 Remove some unused variables.
  ibtk/src/solvers/impls/CCPoissonLevelRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/SCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/VCSCViscousOpPointRelaxationFACOperator.cpp
  src/IB/CIBMethod.cpp
  src/IB/ConstraintIBMethod.cpp
  src/IB/GeneralizedIBMethod.cpp
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
  src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
  src/IB/IBInterpolantMethod.cpp
  src/IB/IBRedundantInitializer.cpp
  src/IB/IBStandardForceGen.cpp
  src/IB/IMPInitializer.cpp
  src/IB/IMPMethod.cpp
  src/complex_fluids/CFGiesekusRelaxation.cpp
  src/complex_fluids/CFINSForcing.cpp
  src/complex_fluids/CFOldroydBRelaxation.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesBlockFactorizationPreconditioner.cpp
  src/navier_stokes/StaggeredStokesFACPreconditionerStrategy.cpp
  src/wave_generation/IrregularWaveBcCoef.cpp
  src/wave_generation/StokesFirstOrderWaveBcCoef.cpp
  src/wave_generation/StokesSecondOrderWaveBcCoef.cpp
Labels: enhancement

#797 Reduce the scope of some variables.
  ibtk/src/math/PETScVecUtilities.cpp
  ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
  ibtk/src/solvers/impls/PETScMFFDJacobianOperator.cpp
  ibtk/src/solvers/impls/PETScNewtonKrylovSolver.cpp
  src/IB/BrinkmanPenalizationRigidBodyDynamics.cpp
  src/IB/CIBMethod.cpp
  src/IB/IBFEDirectForcingKinematics.cpp
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBInterpolantMethod.cpp
  src/IB/IBMethod.cpp
  src/IB/IBRedundantInitializer.cpp
  src/IB/IBStandardForceGen.cpp
  src/IB/PenaltyIBMethod.cpp
  src/IB/StaggeredStokesIBLevelRelaxationFACOperator.cpp
  src/complex_fluids/CFINSForcing.cpp
  src/navier_stokes/INSVCStaggeredPressureBcCoef.cpp
  src/navier_stokes/INSVCStaggeredVelocityBcCoef.cpp
  src/navier_stokes/StaggeredStokesPETScVecUtilities.cpp
Labels: enhancement

#799 Cppcheck 4
  ibtk/include/ibtk/FEDataInterpolation.h
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/PETScLevelSolver.cpp
  src/IB/GeneralizedIBMethod.cpp
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
  src/IB/IBInstrumentPanel.cpp
  src/IB/IBInterpolantHierarchyIntegrator.cpp
  src/IB/IBMethod.cpp
  src/IB/IBStandardForceGen.cpp
  src/IB/IMPMethod.cpp
  src/level_set/RelaxationLSMethod.cpp
  src/navier_stokes/INSStaggeredPressureBcCoef.cpp
  src/navier_stokes/INSVCStaggeredPressureBcCoef.cpp
Labels: enhancement

#826 Add tests for the IB partitioner.
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/ib_partitioning_01.cpp
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=2.input
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=2.output
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=6.input
  tests/IBFE/ib_partitioning_01_2d.quad9.mpirun=6.output
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=2.input
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=2.output
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=6.input
  tests/IBFE/ib_partitioning_01_2d.tri3.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=2.input
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=2.output
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=6.input
  tests/IBFE/ib_partitioning_01_3d.hex27.mpirun=6.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=2.input
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=2.output
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=6.input
  tests/IBFE/ib_partitioning_01_3d.tet4.mpirun=6.output
Labels: Tests

#831 Add missing tests for IB_6
  tests/IBFE/interpolate_velocity_01_2d.b.ib-6.input
  tests/IBFE/interpolate_velocity_01_2d.b.ib-6.output
  tests/IBFE/interpolate_velocity_01_3d.b.ib-6.input
  tests/IBFE/interpolate_velocity_01_3d.b.ib-6.output
  tests/spread/spread_01_2d.ib_6.input
  tests/spread/spread_01_2d.ib_6.output
  tests/spread/spread_01_3d.ib_6.input
  tests/spread/spread_01_3d.ib_6.output
Labels: Tests

#809 Kaustubhk/irregular-wave-gen
  examples/wave_tank/ex0/example.cpp
  examples/wave_tank/ex0/input2d_CaseA_IrregularWave
  include/ibamr/IrregularWaveGenerator.h
  lib/Makefile.am
  lib/Makefile.in
  src/wave_generation/IrregularWaveGenerator.cpp
Labels: enhancement

#834 Fix compilation with libMesh 1.1.
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: libMesh

#833 Cleanup libIBTK
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
Labels: Build System

#838 Add some more files to .gitignore.
  .gitignore
Labels: Miscellaneous

#837 Combine some translation units to improve inlining.
  Makefile.in
  doc/news/changes/minor/2020121DavidWells
  ibtk/Makefile.in
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/lagrangian/fortran/Makefile.am
  ibtk/src/lagrangian/fortran/Makefile.in
  ibtk/src/lagrangian/fortran/lagrangian_delta.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
Labels: Fortran, enhancement

#841 Fix a libMesh version check and clean up the rest.
  doc/release-tasks.md
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/JacobianCalculator.cpp
  src/IB/IBFEInstrumentPanel.cpp
  tests/IBTK/bounding_boxes_01.cpp
Labels: libMesh

#842 More spread tests
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.bspline_3.mpirun=4.input
  tests/spread/spread_01_2d.bspline_3.mpirun=4.output
  tests/spread/spread_01_2d.ib_6.mpirun=4.input
  tests/spread/spread_01_2d.ib_6.mpirun=4.output
  tests/spread/spread_01_3d.ib_6.mpirun=4.input
  tests/spread/spread_01_3d.ib_6.mpirun=4.output
  tests/spread/spread_01_3d.piecewise_linear.mpirun=4.input
  tests/spread/spread_01_3d.piecewise_linear.mpirun=4.output
Labels: Tests

#843 Fix compilation with clang
  ibtk/src/utilities/box_utilities.cpp
  tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
Labels: Bug

#844 Fix a check in a test.
  tests/IBTK/box_utilities_01.cpp
Labels: Tests
