Repository IBAMR/IBAMR, pull requests merged in 2020-02, with the labels that each got.

#849 unique_ptr for HierarchyIntegrator
  doc/news/changes/incompatibilities/20200131MarshallDavey
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/IBHierarchyIntegrator.h
  include/ibamr/IBStrategy.h
  src/IB/IBHierarchyIntegrator.cpp
  src/IB/IBStrategy.cpp
Labels: C++11

#855 Fix compilation with clang.
  ibtk/include/ibtk/HierarchyIntegrator.h
  include/ibamr/IBStrategy.h
Labels: High Priority :warning:

#856 Fix clang warnings 2
  src/IB/ConstraintIBMethod.cpp
  src/IB/IBInstrumentPanel.cpp
  src/IB/IBInterpolantHierarchyIntegrator.cpp
  src/IB/NonbondedForceEvaluator.cpp
  src/complex_fluids/CFRelaxationOperator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesBlockFactorizationPreconditioner.cpp
Labels: Miscellaneous

#860 Get the test suite working without libMesh.
  attest
  doc/news/changes/minor/20200207DavidWells
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/Makefile.am
  tests/Makefile.in
  tests/level_set/Makefile.am
  tests/level_set/Makefile.in
  tests/spread/Makefile.am
  tests/spread/Makefile.in
  tests/wave_tank/Makefile.am
  tests/wave_tank/Makefile.in
Labels: Tests

#862 Fix test compilation.
  tests/Makefile.am
  tests/Makefile.in
Labels: Bug, Tests

#863 Fix restarts on the scratch hierarchy.
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
Labels: Bug

#864 Remove an unused header inclusion.
  include/ibamr/IBRedundantInitializer.h
Labels: Miscellaneous

#861 Updated bundled boost and added configuring checks.
  Makefile.in
  configure
  ibtk/Makefile.in
  ibtk/configure
  ibtk/contrib/boost/boost/math/special_functions/sign.hpp
  ibtk/contrib/boost/boost/math/tools/roots.hpp
  ibtk/contrib/boost/boost/math/tools/toms748_solve.hpp
  ibtk/contrib/boost/boost/math/tools/tuple.hpp
  ibtk/m4/configure_boost.m4
  m4/configure_boost.m4
Labels: Bug, External Libraries

#866 Correctly delete test working directories.
  attest
Labels: Bug, Tests

#867 Add a test for restarting an IB example.
  tests/IB/explicit_ex0.cpp
  tests/IB/explicit_ex0.restart=300.mpirun=4.input
  tests/IB/explicit_ex0.restart=300.mpirun=4.output
Labels: Tests

#858 Add more overloads of FEDataManager::spread().
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement

#870 Fix coarsen specification in non-conservative VC integrator
  configure
  configure.ac
  doc/news/changes/minor/20200214NishantNangia
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  tests/Makefile.am
  tests/Makefile.in
  tests/vc_navier_stokes/Makefile.am
  tests/vc_navier_stokes/Makefile.in
  tests/vc_navier_stokes/SetFluidProperties.cpp
  tests/vc_navier_stokes/SetFluidProperties.h
  tests/vc_navier_stokes/vc_navier_stokes_01.cpp
  tests/vc_navier_stokes/vc_navier_stokes_01_2d.input
  tests/vc_navier_stokes/vc_navier_stokes_01_2d.output
  tests/vc_navier_stokes/vc_navier_stokes_01_3d.input
  tests/vc_navier_stokes/vc_navier_stokes_01_3d.output
Labels: Bug

#875 Add some missing header inclusions.
  ibtk/include/ibtk/BoxPartitioner.h
  ibtk/include/ibtk/FEDataInterpolation.h
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/include/ibtk/LaplaceOperator.h
  ibtk/include/ibtk/PoissonFACPreconditionerStrategy.h
  ibtk/include/ibtk/PoissonSolver.h
  include/ibamr/ConstraintIBMethod.h
  include/ibamr/IBFEMethod.h
  include/ibamr/IBStrategy.h
Labels: Miscellaneous

#846 Add some more surface mesh partitioning tests.
  tests/IBFE/ib_partitioning_02_2d.tri6.mpirun=4.input
  tests/IBFE/ib_partitioning_02_2d.tri6.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex8.mpirun=4.input
  tests/IBFE/ib_partitioning_02_3d.hex8.mpirun=4.output
Labels: Tests

#873 More spread tests 2
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.square.bspline_3.input
  tests/spread/spread_01_2d.square.bspline_3.output
  tests/spread/spread_01_3d.compositecube.bspline_4.mpirun=4.input
  tests/spread/spread_01_3d.compositecube.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.bspline_3.mpirun=4.input
  tests/spread/spread_01_3d.cube.bspline_3.mpirun=4.output
Labels: Tests

#847 Index tests
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/ghost_indices_01.cpp
  tests/IBTK/ghost_indices_01_2d.a.mpirun=2.input
  tests/IBTK/ghost_indices_01_2d.a.mpirun=2.output
  tests/IBTK/ghost_indices_01_2d.b.mpirun=2.input
  tests/IBTK/ghost_indices_01_2d.b.mpirun=2.output
  tests/IBTK/ghost_indices_01_3d.a.mpirun=4.input
  tests/IBTK/ghost_indices_01_3d.a.mpirun=4.output
  tests/IBTK/ghost_indices_01_3d.b.mpirun=4.input
  tests/IBTK/ghost_indices_01_3d.b.mpirun=4.output
  tests/spread/spread_01.cpp
  tests/tests.h
Labels: Tests

#876 Don't use Triangle in the spread tests.
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.bspline_3.mpirun=4.output
  tests/spread/spread_01_2d.bspline_3.output
  tests/spread/spread_01_2d.bspline_4.output
  tests/spread/spread_01_2d.bspline_5.output
  tests/spread/spread_01_2d.bspline_6.output
  tests/spread/spread_01_2d.default.output
  tests/spread/spread_01_2d.discontinuous_linear.output
  tests/spread/spread_01_2d.ib_3.output
  tests/spread/spread_01_2d.ib_4.output
  tests/spread/spread_01_2d.ib_4_w8.output
  tests/spread/spread_01_2d.ib_5.output
  tests/spread/spread_01_2d.ib_6.mpirun=4.output
  tests/spread/spread_01_2d.ib_6.output
  tests/spread/spread_01_2d.piecewise_constant.output
  tests/spread/spread_01_2d.piecewise_cubic.output
  tests/spread/spread_01_2d.piecewise_linear.output
Labels: Tests

#877 Fix with unstable quadrature point placement.
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.bspline_3.mpirun=4.input
  tests/spread/spread_01_2d.bspline_3.mpirun=4.output
  tests/spread/spread_01_2d.bspline_3.output
  tests/spread/spread_01_2d.bspline_4.output
  tests/spread/spread_01_2d.bspline_5.output
  tests/spread/spread_01_2d.bspline_6.output
  tests/spread/spread_01_2d.default.output
  tests/spread/spread_01_2d.discontinuous_linear.output
  tests/spread/spread_01_2d.ib_3.output
  tests/spread/spread_01_2d.ib_4.output
  tests/spread/spread_01_2d.ib_4_w8.output
  tests/spread/spread_01_2d.ib_5.output
  tests/spread/spread_01_2d.ib_6.mpirun=4.input
  tests/spread/spread_01_2d.ib_6.mpirun=4.output
  tests/spread/spread_01_2d.ib_6.output
  tests/spread/spread_01_2d.piecewise_constant.output
  tests/spread/spread_01_2d.piecewise_cubic.output
  tests/spread/spread_01_2d.piecewise_linear.output
  tests/spread/spread_01_2d.square.bspline_3.output
  tests/spread/spread_01_3d.bspline_3.output
  tests/spread/spread_01_3d.bspline_4.output
  tests/spread/spread_01_3d.bspline_5.output
  tests/spread/spread_01_3d.bspline_6.output
  tests/spread/spread_01_3d.compositecube.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.bspline_3.mpirun=4.output
  tests/spread/spread_01_3d.default.output
  tests/spread/spread_01_3d.discontinuous_linear.output
  tests/spread/spread_01_3d.ib_3.output
  tests/spread/spread_01_3d.ib_4.output
  tests/spread/spread_01_3d.ib_4_w8.output
  tests/spread/spread_01_3d.ib_5.output
  tests/spread/spread_01_3d.ib_6.mpirun=4.output
  tests/spread/spread_01_3d.ib_6.output
  tests/spread/spread_01_3d.piecewise_constant.output
  tests/spread/spread_01_3d.piecewise_cubic.output
  tests/spread/spread_01_3d.piecewise_linear.mpirun=4.output
  tests/spread/spread_01_3d.piecewise_linear.output
Labels: Tests

#848 Fix some minor doxygen issues.
  ibtk/include/ibtk/FEDataManager.h
  include/ibamr/IBFEMethod.h
Labels: Documentation, Miscellaneous

#874 Fix the discontinuous linear 3D spread kernel.
  doc/news/changes/minor/20200215DavidWells
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
Labels: Bug, Fortran

#852 Fix IB5
  doc/news/changes/minor/20200201DavidWells
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
  tests/spread/spread_01_3d.ib_5.output
Labels: Bug, Fortran

#882 Consolidated various scripts into scripts directory.
  configure
  configure.ac
  doc/news/changes/minor/20200221AaronBarrett_1
  scripts/IB/README
  scripts/IB/beam_validator3d.pl
  scripts/IB/beam_viewer3d.m
  scripts/IB/scale_spring_rest_length.pl
  scripts/IB/scale_spring_stiffness.pl
  scripts/IB/set_spring_rest_length.pl
  scripts/IB/set_spring_stiffness.pl
  scripts/IB/spring_validator3d.pl
  scripts/IB/spring_viewer3d.m
  scripts/IB/target_point_validator3d.pl
  scripts/IB/target_viewer3d.m
  scripts/IB/vertex_viewer3d.m
  scripts/README
  scripts/code_updates/README
  scripts/code_updates/misc_cpp11_updates.pl
  scripts/formatting/README
  scripts/formatting/check_formatting.sh
  scripts/formatting/reformat.sh
  scripts/formatting/setup_clang_format_precommit_hook.sh
  scripts/project_templates/README
  scripts/project_templates/setup_compile_commands.sh
  scripts/restarts/README
  scripts/restarts/autostarter.pl
  scripts/restarts/make_visit_file.py
  scripts/restarts/modules/ConfigReader/Simple.pm
  scripts/restarts/regen_viz_input_files.pl
  src/Makefile.am
  src/Makefile.in
  src/tools/Makefile.am
  src/tools/Makefile.in
  src/tools/includes.pl
Labels: enhancement

#883 Accumulate forces in some spread tests.
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.square.bspline_3.output
  tests/spread/spread_01_3d.compositecube.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.bspline_3.mpirun=4.output
Labels: Tests

#886 Initialize a variable.
  tests/IBFE/ib_partitioning_01.cpp
Labels: Miscellaneous

#888 Skip copying ghost data when we can.
  src/IB/IBFEMethod.cpp
Labels: enhancement

#887 Fix a bug in FEDataManager::spread().
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.square.b.bspline_3.input
  tests/spread/spread_01_2d.square.b.bspline_3.output
Labels: Bug

#879 Inactivate parts api
  doc/news/changes/minor/20200220DavidWells
  include/ibamr/IBFEMethod.h
  include/ibamr/IBMethod.h
  include/ibamr/IBStrategy.h
  src/IB/IBFEMethod.cpp
  src/IB/IBMethod.cpp
  src/IB/IBStrategy.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.input
  tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.output
Labels: enhancement

#854 Clean up most of the IB kernels.
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
Labels: Fortran, enhancement

#890 Remove some tests that have inconsistent output.
  tests/IBFE/interpolate_velocity_01_2d.b.discontinuous-linear.input
  tests/IBFE/interpolate_velocity_01_2d.b.discontinuous-linear.output
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-constant.input
  tests/IBFE/interpolate_velocity_01_2d.b.piecewise-constant.output
  tests/IBFE/interpolate_velocity_01_3d.b.discontinuous-linear.input
  tests/IBFE/interpolate_velocity_01_3d.b.discontinuous-linear.output
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-constant.input
  tests/IBFE/interpolate_velocity_01_3d.b.piecewise-constant.output
Labels: Tests
