Repository IBAMR/IBAMR, pull requests merged in 2020-05, with the labels that each got.

#982 Fixed namespace issue for Vector in CIBMethod
  src/IB/CIBMethod.cpp
Labels: Miscellaneous

#983 do not use constrain_element_vector() with too many DOFs
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.output
  tests/IBFE/explicit_ex1_2d.nodal_quadrature.output
  tests/IBFE/explicit_ex2.cpp
  tests/IBFE/explicit_ex2_3d.nodal_quadrature.input
  tests/IBFE/explicit_ex2_3d.nodal_quadrature.output
Labels: Bug, High Priority :warning:, libMesh

#984 Fix attest's busy wait again.
  attest
Labels: Tests

#977 Factor mechanics code from IBFEMethod into FEMechanicsBase
  doc/news/changes/major/20200504BoyceGriffith
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataInterpolation.cpp
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/FEMechanicsBase.h
  include/ibamr/IBFEMethod.h
  lib/Makefile.am
  lib/Makefile.in
  src/IB/FEMechanicsBase.cpp
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex1_2d.eliminate_pressure_jumps.input
  tests/IBFE/explicit_ex1_2d.eliminate_pressure_jumps.output
  tests/IBFE/explicit_ex1_2d.impose_pressure_jumps.input
  tests/IBFE/explicit_ex1_2d.impose_pressure_jumps.output
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.source_test.input
  tests/IBFE/explicit_ex4_2d.source_test.output
  tests/IBFE/zero_exterior_values.cpp
Labels: enhancement, libMesh

#988 Suppress some warning messages in a test.
  tests/IBFE/explicit_ex2.cpp
  tests/IBFE/explicit_ex2_3d.nodal_quadrature.output
Labels: Tests

#985 Make the ex5 test more robust.
  tests/IBFE/explicit_ex5.cpp
  tests/IBFE/explicit_ex5_2d.mpirun=2.output
  tests/IBFE/explicit_ex5_2d.regrid.mpirun=2.output
  tests/IBFE/explicit_ex5_2d.restart=40.mpirun=2.output
  tests/IBFE/explicit_ex5_3d.mpirun=2.output
Labels: Tests

#989 avoid unneeded copies in IBFEMethod for multi-part models
  src/IB/IBFEMethod.cpp
Labels: enhancement, libMesh

#990 Add FEValues
  ibtk/include/ibtk/FECache.h
  ibtk/include/ibtk/FEValues.h
  ibtk/include/ibtk/JacobianCalculator.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/lagrangian/FEValues.cpp
  ibtk/src/lagrangian/JacobianCalculator.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/fe_values_01.cpp
  tests/IBTK/fe_values_01.input
  tests/IBTK/fe_values_01.output
Labels: libMesh

#991 Fix some more sign comparison warnings
  ibtk/src/lagrangian/JacobianCalculator.cpp
Labels: libMesh

#997 Revert "Use FEValues in FEDataInterpolation."
  doc/news/changes/major/20200519DavidWells
  ibtk/include/ibtk/FEDataInterpolation.h
  ibtk/src/lagrangian/FEDataInterpolation.cpp
Labels: Bug

#998 Fixing small bug in VC Gauss-Seidel smoothers
  doc/news/changes/minor/20200523NishantNangia
  ibtk/src/solvers/impls/fortran/patchsmoothers3d.f.m4
Labels: Bug

#1001 Fix edge case in HR limiters
  doc/news/changes/minor/20200528NishantNangia
  src/navier_stokes/fortran/navier_stokes_staggered_helpers2d.f.m4
  src/navier_stokes/fortran/navier_stokes_staggered_helpers3d.f.m4
  tests/vc_navier_stokes/vc_navier_stokes_01_2d.output
  tests/vc_navier_stokes/vc_navier_stokes_01_3d.output
Labels: Bug
