Repository IBAMR/IBAMR, pull requests merged in 2020-09, with the labels that each got.

#1090 Remove IBTK::FEMapCache.
  doc/news/changes/incompatibilities/20200901DavidWells
  ibtk/include/ibtk/FEMapCache.h
  ibtk/include/ibtk/libmesh_utilities.h
  tests/IBTK/ghost_accumulation_01.cpp
  tests/IBTK/ghost_indices_01.cpp
  tests/IBTK/jacobian_calc_01.cpp
  tests/IBTK/mapping_01.cpp
  tests/tests.h
Labels: Miscellaneous

#1091 clean up FEProjector
  ibtk/include/ibtk/FEProjector.h
  ibtk/src/lagrangian/FEProjector.cpp
Labels: Miscellaneous, libMesh

#1087 Check for nodes that are inside the domain but outside a patch.
  doc/news/changes/minor/20200826DavidWells
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/ibtk_enums.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement

#1086 Ibfemethod patch elem assoc
  doc/news/changes/major/20200825DavidWells
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4_2d.no-regrid.mpirun=4.input
  tests/IBFE/explicit_ex4_2d.no-regrid.mpirun=4.output
Labels: enhancement

#1092 Fixed CFINSForcing::getVariableIdx() to get the correct patch index.
  doc/news/changes/minor/20200901AaronBarrett
  include/ibamr/CFINSForcing.h
Labels: Bug

#1093 Remove some deprecated stuff in FEDataManager.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFESurfaceMethod.cpp
Labels: libMesh

#1094 Use LibMeshSystemIBVectors in IBFESurfaceMethod, part 1.
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFESurfaceMethod.cpp
Labels: libMesh

#1095 Move setup_system_vector(s) to libmesh_utilities.
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/utilities/libmesh_utilities.cpp
  include/ibamr/FEMechanicsBase.h
  src/IB/FEMechanicsBase.cpp
  src/IB/IBFEMethod.cpp
Labels: Miscellaneous, libMesh

#1096 Slightly improve IBFEMethod's parallel communication.
  src/IB/IBFEMethod.cpp
Labels: Miscellaneous

#1099 Avoid using the preprocessor in sphereGen3d.
  examples/ConstraintIB/falling_sphere/Makefile.am
  examples/ConstraintIB/falling_sphere/Makefile.in
  examples/ConstraintIB/falling_sphere/sphereGen3d.cpp
Labels: Build System

#1100 Merge surface jumps 4
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFESurfaceMethod.cpp
Labels: libMesh

#1101 Use LibMeshSystemIBVectors in IBFESurfaceMethod, part 5.
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFESurfaceMethod.cpp
Labels: libMesh

#1104 Multilevel ibfe 1
  doc/news/changes/incompatibilities/20200910DavidWells
  doc/news/changes/incompatibilities/20200910DavidWells-2
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/FEProjector.cpp
  include/ibamr/IBFEMethod.h
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex4.cpp
Labels: libMesh

#1024 add a static pressure (with optional local projection stabilization) to FEMechanicsBase
  doc/news/changes/major/20200911BoyceGriffith
  include/ibamr/FEMechanicsBase.h
  include/ibamr/IBFEMethod.h
  include/ibamr/ibamr_enums.h
  src/IB/FEMechanicsBase.cpp
  src/IB/IBFEMethod.cpp
Labels: enhancement, libMesh

#1108 Multilevel ibfe 2
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: libMesh

#1113 Multilevel ibfe 3
  attest
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/subdomain_level_translation_01.cpp
  tests/IBTK/subdomain_level_translation_01.expect_error=true.input
  tests/IBTK/subdomain_level_translation_01.expect_error=true.output
  tests/IBTK/subdomain_level_translation_01.input
  tests/IBTK/subdomain_level_translation_01.output
  tests/tests.h
Labels: enhancement, libMesh

#1114 Fix an escaped dollar sign.
  Makefile.am
  Makefile.in
Labels: Bug, Tests

#1115 fix indexing bug in FEMechanicsBase
  src/IB/FEMechanicsBase.cpp
Labels: Bug

#1116 Remove some unused variables.
  src/IB/FEMechanicsBase.cpp
Labels: Miscellaneous

#1117 Fix a libMesh::System cast.
  ibtk/src/utilities/libmesh_utilities.cpp
Labels: Bug

#1118 Fix a problem with printing the partitioning in tests.
  tests/spread/spread_01.cpp
  tests/spread/spread_01_2d.bspline_3.mpirun=4.output
  tests/spread/spread_01_2d.ib_6.mpirun=4.output
  tests/spread/spread_01_2d.nodal_quadrature.a.mpirun=4.output
  tests/spread/spread_01_2d.square.c.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.compositecube.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.b.bspline_4.mpirun=4.output
  tests/spread/spread_01_3d.cube.bspline_3.mpirun=4.output
  tests/spread/spread_01_3d.ib_6.mpirun=4.output
  tests/spread/spread_01_3d.piecewise_linear.mpirun=4.output
  tests/tests.h
Labels: Tests

#1119 Multilevel ibfe 4
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/multilevel_fe_01.cpp
  tests/IBTK/multilevel_fe_01_2d.half.input
  tests/IBTK/multilevel_fe_01_2d.half.output
  tests/IBTK/multilevel_fe_01_2d.input
  tests/IBTK/multilevel_fe_01_2d.output
  tests/IBTK/multilevel_fe_01_3d.input
  tests/IBTK/multilevel_fe_01_3d.output
  tests/IBTK/multilevel_fe_01_3d.quarter.input
  tests/IBTK/multilevel_fe_01_3d.quarter.mpirun=4.input
  tests/IBTK/multilevel_fe_01_3d.quarter.mpirun=4.output
  tests/IBTK/multilevel_fe_01_3d.quarter.output
Labels: enhancement

#1120 Don't link against libhdf5_hl.
  config/IBAMR_config.h.tmp.in
  configure
  doc/news/changes/incompatibilities/20200916DavidWells
  ibtk/config/IBTK_config.h.tmp.in
  ibtk/configure
  m4/configure_hdf5.m4
Labels: Bug, Build System

#1123 Multilevel ibfe 5
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBFE/interpolate_velocity_01_2d.multilevel.a.input
  tests/IBFE/interpolate_velocity_01_2d.multilevel.a.output
  tests/IBFE/interpolate_velocity_01_2d.multilevel.b.input
  tests/IBFE/interpolate_velocity_01_2d.multilevel.b.mpirun=4.input
  tests/IBFE/interpolate_velocity_01_2d.multilevel.b.mpirun=4.output
  tests/IBFE/interpolate_velocity_01_2d.multilevel.b.output
  tests/IBFE/interpolate_velocity_01_2d.multilevel.c.input
  tests/IBFE/interpolate_velocity_01_2d.multilevel.c.output
Labels: enhancement, libMesh

#1126 Multilevel ibfe 6
  doc/news/changes/incompatibilities/20200917DavidWells
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFEPostProcessor.cpp
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex4.cpp
Labels: enhancement

#1125 Improve the documentation of SubdomainToLevelTranslation.
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
  tests/IBTK/subdomain_level_translation_01.cpp
Labels: Documentation

#1127 Multilevel ibfe 7
  examples/complex_fluids/ex2/InterpolationUtilities.h
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/SAMRAIDataCache.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/utilities/SAMRAIDataCache.cpp
  include/ibamr/IBFEMethod.h
  include/ibamr/IBFESurfaceMethod.h
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex4.cpp
Labels: enhancement

#1134 Update some checks and documentation related to the FCH bug.
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/IBFEMethod.h
Labels: Documentation, Miscellaneous
