Repository IBAMR/IBAMR, pull requests merged in 2020-12, with the labels that each got.

#1160 Fischer
  doc/news/changes/major/20201124DavidWells
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/FEProjector.h
  ibtk/include/ibtk/FischerGuess.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/CMakeLists.txt
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/FEProjector.cpp
  ibtk/src/lagrangian/FischerGuess.cpp
  tests/CMakeLists.txt
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/fischer_guess_01.cpp
  tests/IBTK/fischer_guess_01.input
  tests/IBTK/fischer_guess_01.output
Labels: enhancement

#1105 Fix --with-zlib
  config/IBAMR_config.h.tmp.in
  configure
  doc/news/changes/minor/20200910DavidWells
  ibtk/config/IBTK_config.h.tmp.in
  ibtk/configure
  m4/configure_silo.m4
Labels: Bug, Build System

#1174 correct IBHierarchyIntegrator flag for specifying structure based regrid
  src/IB/IBHierarchyIntegrator.cpp
  tests/IBFE/explicit_ex4_2d.displace.mpirun=4.input
Labels: Bug

#1175 add .cache (from clangd) to .gitignore
  .gitignore
Labels: Infrastructure, Miscellaneous

#1176 Updated documentation for LDataManager.
  doc/news/changes/minor/20201207AaronBarrett
  ibtk/include/ibtk/LDataManager.h
Labels: Documentation

#1178 Added functions to check for absolute and relative equality between doubles.
  doc/news/changes/minor/20201208AaronBarrett
  ibtk/include/ibtk/ibtk_utilities.h
  tests/CMakeLists.txt
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/equal_eps.cpp
  tests/IBTK/equal_eps.input
  tests/IBTK/equal_eps.output
Labels: enhancement

#1180 Cmake mac fixes
  CMakeLists.txt
  src/CMakeLists.txt
Labels: Build System

#1185 Add CMake support.
  examples/CMakeLists.txt
  examples/fe_mechanics/CMakeLists.txt
  examples/fe_mechanics/ex0/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build System

#1186 Fix multilevel.d test
  tests/IBFE/explicit_ex4_2d.multilevel.d.input
  tests/IBFE/explicit_ex4_2d.multilevel.d.output
Labels: Tests
