Repository IBAMR/IBAMR, pull requests merged in 2020-03, with the labels that each got.

#894 Improve some comments in a test.
  tests/interpolate/interpolate_01.cpp
Labels: Miscellaneous, Tests

#893 Add ghost accumulator
  doc/news/changes/major/20200228DavidWells
  ibtk/include/ibtk/PETScVecUtilities.h
  ibtk/include/ibtk/SAMRAIGhostDataAccumulator.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/math/SAMRAIGhostDataAccumulator.cpp
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/ghost_accumulation_01.cpp
  tests/IBTK/ghost_accumulation_01_2d.cell.a.input
  tests/IBTK/ghost_accumulation_01_2d.cell.a.mpirun=2.input
  tests/IBTK/ghost_accumulation_01_2d.cell.a.mpirun=2.output
  tests/IBTK/ghost_accumulation_01_2d.cell.a.output
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.a.input
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.a.output
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.b.input
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.b.mpirun=2.input
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.b.mpirun=2.output
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.b.mpirun=4.input
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.b.mpirun=4.output
  tests/IBTK/ghost_accumulation_01_2d.cell.spread.b.output
  tests/IBTK/ghost_accumulation_01_2d.side.input
  tests/IBTK/ghost_accumulation_01_2d.side.mpirun=2.input
  tests/IBTK/ghost_accumulation_01_2d.side.mpirun=2.output
  tests/IBTK/ghost_accumulation_01_2d.side.output
  tests/IBTK/ghost_accumulation_01_2d.side.spread.a.input
  tests/IBTK/ghost_accumulation_01_2d.side.spread.a.output
  tests/IBTK/ghost_accumulation_01_2d.side.spread.b.input
  tests/IBTK/ghost_accumulation_01_2d.side.spread.b.mpirun=2.input
  tests/IBTK/ghost_accumulation_01_2d.side.spread.b.mpirun=2.output
  tests/IBTK/ghost_accumulation_01_2d.side.spread.b.mpirun=4.input
  tests/IBTK/ghost_accumulation_01_2d.side.spread.b.mpirun=4.output
  tests/IBTK/ghost_accumulation_01_2d.side.spread.b.output
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.a.input
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.a.output
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.b.input
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.b.mpirun=2.input
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.b.mpirun=2.output
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.b.mpirun=4.input
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.b.mpirun=4.output
  tests/IBTK/ghost_accumulation_01_3d.cell.spread.b.output
  tests/IBTK/ghost_accumulation_01_3d.side.spread.a.input
  tests/IBTK/ghost_accumulation_01_3d.side.spread.a.output
  tests/IBTK/ghost_accumulation_01_3d.side.spread.b.input
  tests/IBTK/ghost_accumulation_01_3d.side.spread.b.mpirun=2.input
  tests/IBTK/ghost_accumulation_01_3d.side.spread.b.mpirun=2.output
  tests/IBTK/ghost_accumulation_01_3d.side.spread.b.mpirun=4.input
  tests/IBTK/ghost_accumulation_01_3d.side.spread.b.mpirun=4.output
  tests/IBTK/ghost_accumulation_01_3d.side.spread.b.output
Labels: Parallel, SAMRAI, enhancement

#897 store part activity state in IBFEMethod restart database
  src/IB/IBFEMethod.cpp
Labels: Bug

#891 Don't use libMesh's compilation flags.
  configure
  doc/news/changes/incompatibilities/20200227DavidWells
  ibtk/configure
  m4/configure_libmesh.m4
Labels: Build System

#898 Add a test for inactivation + restart
  doc/news/changes/incompatibilities/20200303BoyceGriffith
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.input
  tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
Labels: Tests

#902 Force ghosted assembly
  src/IB/IBFEMethod.cpp
Labels: libMesh

#905 Fix a warning in a test.
  tests/IBFE/ib_partitioning_02.cpp
Labels: Miscellaneous

#904 Fix a warning issued by make.
  Makefile.in
  ibtk/Makefile.in
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
Labels: Bug, Build System

#908 Make ib_partitioning_02 more consistent.
  tests/IBFE/ib_partitioning_02.cpp
  tests/IBFE/ib_partitioning_02_2d.quad9.mpirun=2.output
  tests/IBFE/ib_partitioning_02_2d.tri3.mpirun=4.output
  tests/IBFE/ib_partitioning_02_2d.tri6.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex27.mpirun=4.output
  tests/IBFE/ib_partitioning_02_3d.hex8.mpirun=4.output
Labels: Tests

#911 Change the default settings for libMesh remeshing.
  doc/news/changes/incompatibilities/20200311DavidWells
  include/ibamr/IBFEMethod.h
  include/ibamr/ibamr_enums.h
  src/IB/IBFEMethod.cpp
Labels: Miscellaneous

#909 Add some notes on using MPI.
  doc/mpi.md
Labels: Documentation

#910 Remove call to IBFEMethod::reinitializeFEData().
  doc/news/changes/minor/20200311DavidWells
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement

#912 Slightly improve test suite performance.
  attest
Labels: Tests

#916 Improve fe coupling
  doc/news/changes/minor/20200316DavidWells
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
Labels: enhancement, libMesh

#914 Print IBAMR version and git commit hash in config.log.
  configure
  configure.ac
Labels: Build System, enhancement

#918 Add a template for pull requests.
  .github/pull_request_template.md
  doc/pull_request_template.md
Labels: Miscellaneous

#921 Zero some stored hypre residuals.
  doc/news/changes/minor/20200318DavidWells
  ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
  ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp
Labels: enhancement

#920 Fix some IWYU issues.
  doc/release-tasks.md
  ibtk/include/ibtk/PETScVecUtilities.h
  ibtk/include/ibtk/SAMRAIGhostDataAccumulator.h
  ibtk/src/utilities/SAMRAIDataCache.cpp
  include/ibamr/CFRelaxationOperator.h
  include/ibamr/IBBeamForceSpec.h
  include/ibamr/IBHierarchyIntegrator.h
  include/ibamr/IBInstrumentationSpec.h
  include/ibamr/IBKirchhoffRodForceGen.h
  include/ibamr/IBRodForceSpec.h
  include/ibamr/IBTargetPointForceSpec.h
  include/ibamr/MaterialPointSpec.h
  include/ibamr/private/IBInstrumentationSpec-inl.h
  src/IB/IBFEMethod.cpp
  src/IB/IBFEPostProcessor.cpp
  src/IB/KrylovMobilitySolver.cpp
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
Labels: Bug

#925 add missing include in FEDataManager.cpp
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: Bug, High Priority :warning:, libMesh

#922 Update attest's output.
  attest
Labels: Tests, enhancement

#931 update location of clang++ in setup_compile_commands.sh
  scripts/project_templates/setup_compile_commands.sh
Labels: Miscellaneous

#937 Fix some clang warnings.
  ibtk/src/refine_ops/CartSideDoubleDivPreservingRefine.cpp
  tests/multiphase_flow/SetFluidGasSolidDensity.h
  tests/multiphase_flow/SetFluidGasSolidViscosity.h
  tests/multiphase_flow/SetFluidProperties.h
Labels: Miscellaneous

#928 replace deprecated bind2nd with lambda expressions
  ibtk/src/solvers/impls/CCPoissonBoxRelaxationFACOperator.cpp
  src/IB/IBMethod.cpp
  src/IB/IBStandardForceGen.cpp
Labels: C++11, enhancement

#938 Add LibMeshSystemVectors
  doc/news/changes/incompatibilities/20200324DavidWells
  ibtk/include/ibtk/LibMeshSystemVectors.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/utilities/LibMeshSystemVectors.cpp
  include/ibamr/IBFEMethod.h
  src/IB/IBFEMethod.cpp
  tests/spread/spread_01.cpp
Labels: enhancement, libMesh

#941 Conditionally compile an example that depends on libMesh.
  examples/IBLevelSet/ex0/Makefile.am
  examples/IBLevelSet/ex0/Makefile.in
Labels: Build System

#942 Fix compilation with libMesh 1.1.0
  ibtk/src/utilities/libmesh_utilities.cpp
Labels: libMesh

#924 Can register a callback function with HierarchyIntegrator to allow specialization for HierarchyIntegrator::regridHierarchy()
  doc/news/changes/minor/20200319AaronBarrett
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/src/utilities/HierarchyIntegrator.cpp
Labels: enhancement

#945 Clean up the bootstrap script.
  bootstrap
Labels: Build System

#946 Improve bootstrap a little more.
  bootstrap
Labels: Build System

#948 Fix spreadTransmissionForceDensity() + AMR.
  doc/news/changes/minor/20200330DavidWells
  src/IB/IBFEMethod.cpp
  tests/IBFE/Makefile.am
  tests/IBFE/Makefile.in
  tests/IBFE/explicit_ex1.cpp
  tests/IBFE/explicit_ex1_2d.mpirun=4.input
  tests/IBFE/explicit_ex1_2d.mpirun=4.output
Labels: Bug

#950 Improve stability of CIB tests.
  tests/CIB/cib_double_shell.mpirun=4.output
  tests/CIB/cib_double_shell.output
  tests/CIB/cib_plate.mpirun=4.output
  tests/CIB/cib_plate.restart=5.mpirun=4.output
  tests/CIB/petsc_options.dat
Labels: Tests

#951 lazy initialize IB ghosted DOF indexing
  ibtk/include/ibtk/FEDataManager.h
  ibtk/src/lagrangian/FEDataManager.cpp
Labels: enhancement
