Repository IBAMR/IBAMR, pull requests merged in 2021-07, with the labels that each got.

#1278 Fix the build directory rpath.
  CMakeLists.txt
Labels: Build System

#1279 Combine evaluation of PK1 stress functions.
  doc/news/changes/minor/20210706DavidWells
  ibtk/include/ibtk/libmesh_utilities.h
  src/IB/FEMechanicsBase.cpp
Labels: enhancement, libMesh

#1287 Add a timeout to attest.
  attest
Labels: CI, Tests

#1285 Test build on pull-request and push
  .github/test-build
  .github/workflows/main.yml
  doc/news/changes/minor/20210712DavidThompson
Labels: CI, High Priority :warning:

#1286 Remove some unused includes.
  ibtk/src/solvers/impls/CCPoissonPETScLevelSolver.cpp
  ibtk/src/solvers/impls/PETScLevelSolver.cpp
  ibtk/src/solvers/impls/SCPoissonPETScLevelSolver.cpp
  ibtk/src/solvers/impls/VCSCViscousPETScLevelSolver.cpp
  src/navier_stokes/StaggeredStokesPETScLevelSolver.cpp
Labels: Miscellaneous

#1281 Update our GSL detection to match the convention used elsewhere.
  CMakeLists.txt
  doc/cmake.md
Labels: Build System

#1283 Silence some warnings if Silo isn't present.
  tests/IB/explicit_ex0.cpp
  tests/IB/explicit_ex1.cpp
  tests/IB/ib_body_force.cpp
  tests/IB/ib_body_force_kirchhoff.cpp
Labels: Tests

#1284 Print required and optional CMake paths in different places.
  CMakeLists.txt
Labels: Build System

#1289 Attest cleanup
  attest
  tests/attest.conf.in
Labels: Infrastructure, Tests

#1292 Add some more checks for libMesh features.
  CMakeLists.txt
Labels: Build System

#1294 Make ExodusII optional in the tests.
  tests/fe_mechanics/fe_mechanics_ex0.cpp
  tests/spread/spread_02.cpp
Labels: Tests, libMesh

#1296 Use std::vector::data().
  src/IB/IBBeamForceSpecFactory.cpp
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBRedundantInitializer.cpp
  src/IB/IBStandardInitializer.cpp
  src/utilities/RNG.cpp
Labels: C++

#1297 Submit to a dashboard
  .github/cmake/configure_common.cmake
  .github/cmake/configure_fedora33.cmake
  .github/cmake/configure_sccache.cmake
  .github/cmake/ctest_build.cmake
  .github/cmake/ctest_configure.cmake
  .github/cmake/ctest_exclusions.cmake
  .github/cmake/ctest_submit_multi.cmake
  .github/cmake/ctest_test.cmake
  .github/cmake/github_ci.cmake
  .github/test-build
  .github/workflows/main.yml
  .github/workflows/push-pull.yml
  CMakeLists.txt
  CTestConfig.cmake
  doc/news/changes/minor/20210713DavidThompson
  tests/CMakeLists.txt
Labels: CI

#1303 Export dependency cmake paths
  CMakeLists.txt
  cmake/IBAMRConfig.cmake.in
  doc/cmake.md
Labels: Bug, Build System

#1304 Remove an exported boost preprocessor symbol.
  cmake/IBAMRConfig.cmake.in
Labels: Build System

#1305 Revert attest to require Python 3.5.
  attest
  src/IB/ConstraintIBMethod.cpp
  tests/IBFE/explicit_ex8.cpp
Labels: Tests

#1313 Fix child integrator test that fails in debug mode.
  tests/IBTK/child_integrators.cpp
  tests/IBTK/child_integrators.input
  tests/IBTK/child_integrators.output
Labels: Tests

#1314 Fixed child integrator test that outputs warnings when silo is not present.
  tests/IBTK/child_integrators.cpp
Labels: Tests

#1315 Skip -Wparentheses in external headers.
  ibtk/include/ibtk/config.h.in
Labels: Miscellaneous
