Repository IBAMR/IBAMR, pull requests merged in 2021-06, with the labels that each got.

#1269 Fix some more minor warnings in tests.
  tests/ConstraintIB/oscillating_rigid_cylinder.cpp
  tests/IBTK/child_integrators.cpp
Labels: Miscellaneous

#1270 Fix the CMake flags used in libMesh tests.
  CMakeLists.txt
Labels: Build System

#1271 Fix a problem with overload resolution and the secondary hierarchy.
  ibtk/src/utilities/SecondaryHierarchy.cpp
  tests/IBTK/secondary_hierarchy_01.cpp
Labels: Miscellaneous

#1272 Fix placement of bundled Eigen headers when using CMake install.
  CMakeLists.txt
Labels: Build System

#1268 Computing cell-center and cell index based on grid lower
  doc/news/changes/minor/20210621RamakrishnanThirumalaisamy
  examples/adv_diff/ex3/LevelSetInitialCondition.cpp
  examples/adv_diff/ex3/LevelSetInitialCondition.h
  examples/adv_diff/ex3/example.cpp
  examples/adv_diff/ex3/input2d
  examples/adv_diff/ex4/LevelSetInitialConditionCircle.cpp
  examples/adv_diff/ex4/LevelSetInitialConditionCircle.h
  examples/adv_diff/ex4/LevelSetInitialConditionHexagram.cpp
  examples/adv_diff/ex4/LevelSetInitialConditionHexagram.h
  examples/adv_diff/ex4/example.cpp
  examples/adv_diff/ex4/input2d
  examples/adv_diff/ex5/LevelSetInitialCondition.cpp
  examples/adv_diff/ex5/LevelSetInitialCondition.h
  examples/adv_diff/ex5/example.cpp
  examples/adv_diff/ex5/input2d
  examples/adv_diff/ex6/LevelSetInitialConditionEgg.cpp
  examples/adv_diff/ex6/LevelSetInitialConditionEgg.h
  examples/adv_diff/ex6/LevelSetInitialConditionTorus.cpp
  examples/adv_diff/ex6/LevelSetInitialConditionTorus.h
  examples/adv_diff/ex6/example.cpp
  examples/adv_diff/ex6/input2d
  examples/adv_diff/ex6/input3d
  examples/adv_diff/ex7/LevelSetInitialCondition.cpp
  examples/adv_diff/ex7/LevelSetInitialCondition.h
  examples/adv_diff/ex7/example.cpp
  examples/adv_diff/ex7/input2d
  ibtk/include/ibtk/IndexUtilities.h
  ibtk/include/ibtk/private/IndexUtilities-inl.h
  tests/adv_diff/LevelSetInitialCondition.cpp
  tests/adv_diff/LevelSetInitialCondition.h
  tests/adv_diff/LevelSetInitialConditionHexagram.cpp
  tests/adv_diff/LevelSetInitialConditionHexagram.h
  tests/adv_diff/bp_adv_diff_01.cpp
  tests/adv_diff/bp_adv_diff_01_2d.input
  tests/adv_diff/bp_adv_diff_01_2d.output
  tests/adv_diff/bp_adv_diff_02.cpp
  tests/adv_diff/bp_adv_diff_02_2d.mpirun=8.input
  tests/adv_diff/bp_adv_diff_02_2d.mpirun=8.output
Labels: Bug

#1273 Various cmake fixes
  CMakeLists.txt
  cmake/IBAMRConfig.cmake.in
  include/ibamr/config.h
Labels: Build System

#1275 Refactor scratch hierarchy 9
  ibtk/include/ibtk/SecondaryHierarchy.h
  ibtk/src/utilities/SecondaryHierarchy.cpp
  src/IB/IBFEMethod.cpp
  tests/IBTK/secondary_hierarchy_01.cpp
Labels: Miscellaneous

#1276 Catch all errors for the SVD calculation in FischerGuess.
  ibtk/src/lagrangian/FischerGuess.cpp
Labels: Miscellaneous
