Repository IBAMR/IBAMR, pull requests merged in 2021-03, with the labels that each got.

#1221 Fix the order in which we set some Mat options.
  doc/news/changes/minor/20200301DavidWells
  ibtk/src/lagrangian/FEProjector.cpp
  tests/IBFE/explicit_ex2_3d.mpirun=2.input
  tests/IBFE/explicit_ex2_3d.mpirun=2.output
Labels: Bug

#1225 adding Makefile.in for tests/ConstraintIB
  tests/ConstraintIB/Makefile.in
Labels: Build System

#1220 Adding a simple IBLevetSet example for an oscillating cylinder
  configure
  configure.ac
  doc/news/changes/major/20210304KaustubhKhedkar
  examples/IBLevelSet/CMakeLists.txt
  examples/IBLevelSet/ex1/CMakeLists.txt
  examples/IBLevelSet/ex1/Makefile.am
  examples/IBLevelSet/ex1/Makefile.in
  examples/IBLevelSet/ex1/SetFluidSolidDensity.cpp
  examples/IBLevelSet/ex1/SetFluidSolidDensity.h
  examples/IBLevelSet/ex1/SetFluidSolidViscosity.cpp
  examples/IBLevelSet/ex1/SetFluidSolidViscosity.h
  examples/IBLevelSet/ex1/TagLSRefinementCells.cpp
  examples/IBLevelSet/ex1/TagLSRefinementCells.h
  examples/IBLevelSet/ex1/example.cpp
  examples/IBLevelSet/ex1/input2d_dynamic_mesh
  examples/IBLevelSet/ex1/input2d_static_mesh
Labels: Tutorials, enhancement

#1228 Remove some deprecated libMesh code.
  ibtk/src/lagrangian/FEProjector.cpp
  src/IB/FEMechanicsBase.cpp
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex2.cpp
  tests/IBFE/explicit_ex5.cpp
  tests/IBFE/ib_partitioning_02.cpp
  tests/IBTK/fe_values_02.cpp
  tests/IBTK/jacobian_calc_01.cpp
  tests/level_set/fe_surface_distance.cpp
  tests/wave_tank/nwt_cylinder.cpp
Labels: libMesh
