Repository IBAMR/IBAMR, pull requests merged in 2021-05, with the labels that each got.

#1253 Cmake fixes
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build System

#1252 Fixed export of HDF5 with CMake.
  cmake/IBAMRConfig.cmake.in
Labels: Build System

#1251 Fix some more C++17 stuff.
  examples/IBFE/explicit/ex8/example.cpp
  tests/IBFE/explicit_ex8.cpp
Labels: C++

#1250 Fix compilation with the development version of libMesh.
  examples/IBLevelSet/ex0/example.cpp
  examples/complex_fluids/ex2/example.cpp
  examples/complex_fluids/ex4/example.cpp
Labels: libMesh

#1256 Refactor scratch hierarchy 7
  doc/news/changes/incompatibilities/20210517DavidWells
  doc/news/changes/major/20210517DavidWells
  ibtk/include/ibtk/SecondaryHierarchy.h
  ibtk/src/utilities/SecondaryHierarchy.cpp
  src/IB/IBFEMethod.cpp
  tests/CMakeLists.txt
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/secondary_hierarchy_01.cpp
  tests/IBTK/secondary_hierarchy_01_2d.input
  tests/IBTK/secondary_hierarchy_01_2d.mpirun=4.input
  tests/IBTK/secondary_hierarchy_01_2d.mpirun=4.output
  tests/IBTK/secondary_hierarchy_01_2d.output
Labels: enhancement

#1261 Child integrators are now traversed correctly in regridHierarchy().
  doc/news/changes/minor/20210527AaronBarrett
  ibtk/src/utilities/HierarchyIntegrator.cpp
  tests/CMakeLists.txt
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/child_integrators.cpp
  tests/IBTK/child_integrators_2d.input
  tests/IBTK/child_integrators_2d.output
Labels: Bug

#1262 Avoid printing the initial workload.
  src/IB/IBFEMethod.cpp
  tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.mpirun=4.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.output
  tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
  tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
Labels: Tests

#1238 add support for uniform body forces for IB structures
  .gitignore
  doc/news/changes/major/20210529BoyceGriffith
  include/ibamr/IBKirchhoffRodForceGen.h
  include/ibamr/IBStandardForceGen.h
  src/IB/IBKirchhoffRodForceGen.cpp
  src/IB/IBRedundantInitializer.cpp
  src/IB/IBStandardForceGen.cpp
  tests/CMakeLists.txt
  tests/IB/Makefile.am
  tests/IB/Makefile.in
  tests/IB/ib_body_force.cpp
  tests/IB/ib_body_force.input
  tests/IB/ib_body_force.output
  tests/IB/ib_body_force_kirchhoff.cpp
  tests/IB/ib_body_force_kirchhoff.input
  tests/IB/ib_body_force_kirchhoff.output
Labels: enhancement
