Repository IBAMR/IBAMR, pull requests merged in 2021-01, with the labels that each got.

#1139 Added a functionality to handle variable C coef in CCPoissonPointRela…
  doc/news/changes/minor/20201008RamakrishnanThirumalaisamy
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/SCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/fortran/patchsmoothers2d.f.m4
  ibtk/src/solvers/impls/fortran/patchsmoothers3d.f.m4
  tests/CMakeLists.txt
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/helmholtz.cpp
  tests/IBTK/helmholtz_2d.a.input
  tests/IBTK/helmholtz_2d.a.output
  tests/IBTK/helmholtz_2d.b.input
  tests/IBTK/helmholtz_2d.b.output
  tests/IBTK/helmholtz_2d.c.input
  tests/IBTK/helmholtz_2d.c.output
  tests/IBTK/helmholtz_2d.d.input
  tests/IBTK/helmholtz_2d.d.output
  tests/IBTK/helmholtz_3d.a.mpirun=2.input
  tests/IBTK/helmholtz_3d.a.mpirun=2.output
  tests/IBTK/helmholtz_3d.b.mpirun=2.input
  tests/IBTK/helmholtz_3d.b.mpirun=2.output
  tests/IBTK/helmholtz_3d.c.mpirun=4.input
  tests/IBTK/helmholtz_3d.c.mpirun=4.output
  tests/IBTK/helmholtz_3d.d.mpirun=4.input
  tests/IBTK/helmholtz_3d.d.mpirun=4.output
Labels: enhancement

#1188 enable users to control whether quadrature rules are allowed to use negative weights
  doc/news/changes/minor/20210105BoyceGriffith
  examples/IBFE/explicit/ex0/example.cpp
  examples/IBFE/explicit/ex1/example.cpp
  examples/IBFE/explicit/ex3/example.cpp
  examples/IBFE/explicit/ex4/example.cpp
  ibtk/include/ibtk/FECache.h
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/FEMapping.h
  ibtk/include/ibtk/FEMappingCache.h
  ibtk/include/ibtk/QuadratureCache.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/FEMapping.cpp
  ibtk/src/lagrangian/FEValues.cpp
  ibtk/src/utilities/libmesh_utilities.cpp
  include/ibamr/FEMechanicsBase.h
  src/IB/FEMechanicsBase.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  tests/IBFE/explicit_ex0.cpp
  tests/IBFE/explicit_ex1.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBTK/bounding_boxes_01.cpp
  tests/IBTK/jacobian_calc_01.cpp
  tests/IBTK/mapping_01.cpp
  tests/tests.h
Labels: High Priority :warning:, libMesh

#1197 add input option controlling if negative weights are allowed in IBFE coupling
  src/IB/IBFEMethod.cpp
Labels: libMesh

#1198 Add a missing automake file to configure.ac.
  configure
  configure.ac
Labels: Build System

#1194 Fix gcc warnings
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/utilities/libmesh_utilities.cpp
  include/ibamr/CFUpperConvectiveOperator.h
  include/ibamr/FifthOrderStokesWaveGenerator.h
  include/ibamr/IrregularWaveGenerator.h
  include/ibamr/StaggeredStokesBoxRelaxationFACOperator.h
  src/IB/DirectMobilitySolver.cpp
  src/IB/FEMechanicsExplicitIntegrator.cpp
  src/level_set/FESurfaceDistanceEvaluator.cpp
Labels: Miscellaneous

#1193 Fix some clang warnings.
  examples/ConstraintIB/moving_plate/RigidBodyKinematics.h
  examples/IBLevelSet/ex0/FlowGravityForcing.h
  examples/IBLevelSet/ex0/SetFluidGasSolidDensity.cpp
  examples/IBLevelSet/ex0/SetFluidGasSolidDensity.h
  examples/IBLevelSet/ex0/SetFluidGasSolidViscosity.cpp
  examples/IBLevelSet/ex0/SetFluidGasSolidViscosity.h
  examples/complex_fluids/ex2/InterpolationUtilities.cpp
  examples/complex_fluids/ex4/example.cpp
  examples/wave_tank/ex0/SetFluidProperties.cpp
  examples/wave_tank/ex0/SetFluidProperties.h
  examples/wave_tank/ex1/FlowGravityForcing.h
  examples/wave_tank/ex1/SetFluidGasSolidDensity.cpp
  examples/wave_tank/ex1/SetFluidGasSolidDensity.h
  examples/wave_tank/ex1/SetFluidGasSolidViscosity.cpp
  examples/wave_tank/ex1/SetFluidGasSolidViscosity.h
Labels: Miscellaneous

#1192 Explicitly compile example grid generators with C++11.
  examples/CMakeLists.txt
Labels: Build System

#1191 CMake: improve the MPI check messages.
  CMakeLists.txt
Labels: Build System

#1195 use QNODAL to build lumped mass matrices
  doc/news/changes/minor/20210106BoyceGriffith
  ibtk/include/ibtk/FEProjector.h
  ibtk/src/lagrangian/FEProjector.cpp
  tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.tri6.output
  tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.tet10.output
Labels: libMesh

#1201 Run clang-format
  ibtk/include/ibtk/LDataManager.h
  src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredStabilizedPPMConvectiveOperator.cpp
  src/navier_stokes/INSStaggeredUpwindConvectiveOperator.cpp
  src/utilities/RNG.cpp
  src/wave_generation/IrregularWaveBcCoef.cpp
  src/wave_generation/StokesFifthOrderWaveBcCoef.cpp
  src/wave_generation/StokesFirstOrderWaveBcCoef.cpp
  src/wave_generation/StokesSecondOrderWaveBcCoef.cpp
Labels: Miscellaneous

#1199 Fix some more clang warnings.
  tests/IBTK/bounding_boxes_01.cpp
  tests/IBTK/equal_eps.cpp
  tests/wave_tank/SetFluidProperties.h
Labels: Miscellaneous

#1202 Update copyright for 0.8.0
  COPYRIGHT
  ibtk/CMakeLists.txt
  tests/IBTK/fischer_guess_01.cpp
  tests/IBTK/subdomain_level_translation_01.cpp
Labels: Miscellaneous

#1200 Cppcheck 5
  ibtk/src/boundary/cf_interface/CartCellDoubleQuadraticCFInterpolation.cpp
  ibtk/src/math/PatchMathOps.cpp
  src/IB/IBFEPatchRecoveryPostProcessor.cpp
  src/IB/MobilityFunctions.cpp
Labels: Miscellaneous

#1204 Fix compilation of a test.
  tests/wave_tank/SetFluidProperties.cpp
Labels: Tests

#1206 Generate changelog.
  doc/news/changes/0.7.0-vs-0.8.0.html
  doc/news/changes/incompatibilities/20200425AaronBarrett
  doc/news/changes/incompatibilities/20200623DavidWells
  doc/news/changes/incompatibilities/20200727DavidWells
  doc/news/changes/incompatibilities/20200728DavidWells
  doc/news/changes/incompatibilities/20200803DavidWells
  doc/news/changes/incompatibilities/20200813DavidWells
  doc/news/changes/incompatibilities/20200901DavidWells
  doc/news/changes/incompatibilities/20200910DavidWells
  doc/news/changes/incompatibilities/20200910DavidWells-2
  doc/news/changes/incompatibilities/20200916DavidWells
  doc/news/changes/incompatibilities/20200917DavidWells
  doc/news/changes/major/0701DavidWells
  doc/news/changes/major/20200519DavidWells
  doc/news/changes/major/20200723DavidWells
  doc/news/changes/major/20200825BoyceGriffith
  doc/news/changes/major/20200825DavidWells
  doc/news/changes/major/20200911BoyceGriffith
  doc/news/changes/major/20200928DavidWells
  doc/news/changes/major/20201019DavidWells
  doc/news/changes/major/20201124DavidWells
  doc/news/changes/major/20201218RamakrishnanThirumalaisamy
  doc/news/changes/minor/20200626AaronBarrett
  doc/news/changes/minor/20200629DavidWells
  doc/news/changes/minor/20200714DavidWells
  doc/news/changes/minor/20200724DavidWells
  doc/news/changes/minor/20200727AaronBarrett
  doc/news/changes/minor/20200731DavidWells
  doc/news/changes/minor/20200806DavidWells
  doc/news/changes/minor/20200826DavidWells
  doc/news/changes/minor/20200901AaronBarrett
  doc/news/changes/minor/20200910DavidWells
  doc/news/changes/minor/20201008RamakrishnanThirumalaisamy
  doc/news/changes/minor/20201016DavidWells
  doc/news/changes/minor/20201027DavidWells
  doc/news/changes/minor/20201207AaronBarrett
  doc/news/changes/minor/20201208AaronBarrett
  doc/news/changes/minor/20201215AaronBarrett
  doc/news/changes/minor/2020713DavidWells
  doc/news/changes/minor/20210105BoyceGriffith
  doc/news/changes/minor/20210106BoyceGriffith
  scripts/maintenance/generate-changes.sh
Labels: Miscellaneous

#1208 Fix a version number.
  doc/news/changes/0.7.1-vs-0.8.0.html
Labels: Miscellaneous

#1207 Bump VERSION to 0.9.0-pre
  VERSION
Labels: Discussion

#1210 Fix FEMapping with QNODAL.
  doc/news/changes/minor/20210122DavidWells
  ibtk/include/ibtk/FEMapping.h
  ibtk/src/lagrangian/FEMapping.cpp
  tests/IBTK/jacobian_calc_01.cpp
  tests/IBTK/mapping_01.cpp
Labels: Bug, libMesh

#1211 Convert libMesh::DenseMatrix to Eigen::Matrix.
  ibtk/include/ibtk/FEMapping.h
  ibtk/include/ibtk/FischerGuess.h
  ibtk/src/lagrangian/FEMapping.cpp
  ibtk/src/lagrangian/FischerGuess.cpp
Labels: Miscellaneous, libMesh

#1214 Fix compatibility with Eigen 3.2.
  ibtk/src/lagrangian/FischerGuess.cpp
Labels: External Libraries
