Repository IBAMR/IBAMR, pull requests merged in 2021-09, with the labels that each got.

#1351 Remove a note on std::function.
  include/ibamr/ConstraintIBMethod.h
Labels: Miscellaneous

#1354 Fix mangling
  ibtk/src/refine_ops/CartSideDoubleRT0Refine.cpp
  ibtk/src/refine_ops/CartSideDoubleSpecializedLinearRefine.cpp
  ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
  ibtk/src/solvers/impls/SCPoissonPointRelaxationFACOperator.cpp
  src/adv_diff/AdvDiffCUIConvectiveOperator.cpp
  src/adv_diff/AdvDiffCenteredConvectiveOperator.cpp
  src/adv_diff/AdvDiffPPMConvectiveOperator.cpp
  src/adv_diff/AdvDiffWavePropConvectiveOperator.cpp
  src/complex_fluids/CFUpperConvectiveOperator.cpp
  src/navier_stokes/INSCollocatedCenteredConvectiveOperator.cpp
  src/navier_stokes/INSCollocatedPPMConvectiveOperator.cpp
  src/navier_stokes/INSCollocatedWavePropConvectiveOperator.cpp
  src/navier_stokes/INSStaggeredWavePropConvectiveOperator.cpp
  src/navier_stokes/SurfaceTensionForceFunction.cpp
Labels: Miscellaneous, Fortran

#1352 Cleanup GitHub ci
  .github/cmake/github_ci.cmake
Labels: Infrastructure

#1356 Fix usage of Eigen::Index to work with older versions of Eigen.
  CMakeLists.txt
  src/IB/DirectMobilitySolver.cpp
Labels: Build System, External Libraries

#1360 add #include <memory> to ibtk solver_utilities
  ibtk/src/solvers/solver_utilities.cpp
Labels: Miscellaneous

#1357 Remove some more raw pointers.
  include/ibamr/CFINSForcing.h
  include/ibamr/IBFESurfaceMethod.h
  include/ibamr/INSHierarchyIntegrator.h
  src/IB/IBFESurfaceMethod.cpp
  src/complex_fluids/CFINSForcing.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
Labels: C++, Miscellaneous

#1361 Remove calls to boost::math::round().
  ibtk/include/ibtk/private/IndexUtilities-inl.h
  ibtk/src/lagrangian/LDataManager.cpp
  src/IB/IBFESurfaceMethod.cpp
  src/IB/IBRedundantInitializer.cpp
  src/IB/IMPMethod.cpp
Labels: Miscellaneous
