Repository IBAMR/IBAMR, pull requests merged in 2022-02, with the labels that each got.

#1407 attest: Clean up the expect_error() function.
  attest
Labels: Tests, Infrastructure

#1414 Explicitly remind us to check example compilation.
  doc/release-tasks.md
Labels: Documentation, Infrastructure

#1413 CMake: fix compatibility with 3.15-3.19.
  CMakeLists.txt
Labels: Build System

#1412 CMake: fix compatibility with 3.15-3.19.
  CMakeLists.txt
Labels: Build System

#1415 Update to 0.10.1
  VERSION
  doc/news/changes/0.10.0-vs-0.10.1.html
Labels: Release

#1418 Fix mpi compiler wrapper detection 0.10.1
  CMakeLists.txt
  doc/news/changes/0.10.0-vs-0.10.1.html
Labels: Release, Build System

#1419 Fixing IBLevelSet examples 4 and 5 for some mising Eigen headers requ…
  examples/IBLevelSet/ex4/LevelSetInitialCondition.h
  examples/IBLevelSet/ex5/LevelSetInitialCondition.h
Labels: Bug

#1417 Fix another MPI compiler wrapper case.
  CMakeLists.txt
Labels: Build System

#1422 Iblevelset includes
  examples/IBLevelSet/ex1/example.cpp
  examples/IBLevelSet/ex3/LevelSetInitialCondition.cpp
  examples/IBLevelSet/ex4/LevelSetInitialCondition.cpp
  examples/IBLevelSet/ex4/LevelSetInitialCondition.h
  examples/IBLevelSet/ex4/SetFluidSolidDensity.cpp
  examples/IBLevelSet/ex4/SetFluidSolidViscosity.cpp
  examples/IBLevelSet/ex4/TagLSRefinementCells.cpp
  examples/IBLevelSet/ex4/TagLSRefinementCells.h
  examples/IBLevelSet/ex4/example.cpp
  examples/IBLevelSet/ex5/LevelSetInitialCondition.cpp
  examples/IBLevelSet/ex5/LevelSetInitialCondition.h
  examples/IBLevelSet/ex5/SetFluidSolidDensity.cpp
  examples/IBLevelSet/ex5/SetFluidSolidViscosity.cpp
  examples/IBLevelSet/ex5/TagLSRefinementCells.cpp
  examples/IBLevelSet/ex5/TagLSRefinementCells.h
  examples/IBLevelSet/ex5/example.cpp
Labels: Tutorials

#1424 Mark an example that requires libMesh as such.
  examples/IBLevelSet/ex3/CMakeLists.txt
Labels: Build System

#1421 Fix compilation of examples that depend just on boost.
  examples/CMakeLists.txt
Labels: Build System

#1420 Port changelog entries back to master
  doc/news/changes/0.10.0-vs-0.10.1.html
Labels: Documentation

#1431 Build IBAMR with autotools
  .github/cmake/configure_common.cmake
  .github/workflows/push-pull.yml
Labels: Infrastructure

#1430 Fix documentation in IBStrategy.
  include/ibamr/IBStrategy.h
Labels: Documentation

#1429 Remove ZLIB as an explicit dependency.
  CMakeLists.txt
  doc/cmake.md
  doc/news/changes/minor/20220221DavidWells
Labels: Build System

#1432 Fix sccache population
  .github/workflows/push-pull.yml
Labels: Infrastructure

#1434 CI: Add a build that does not use libMesh.
  .github/cmake/configure_fedora33_no_libmesh.cmake
  .github/workflows/push-pull.yml
Labels: Infrastructure
