Repository IBAMR/IBAMR, pull requests merged in 2022-12, with the labels that each got.

#1498 Fix initialization of director vectors for gIB.
  src/IB/IBRedundantInitializer.cpp
  tests/IB/ib_body_force_kirchhoff.cpp
  tests/IB/ib_body_force_kirchhoff.redundant.input
  tests/IB/ib_body_force_kirchhoff.redundant.output
  tests/IB/ib_body_force_kirchhoff.standard.input
  tests/IB/ib_body_force_kirchhoff.standard.output
Labels: Bug

#1528 Add two minor CMake improvements.
  CMakeLists.txt
Labels: Build System

#1529 IIM: fix const correctness with the latest version of libMesh.
  examples/IIM/ex2/example.cpp
  examples/IIM/ex3/example.cpp
  examples/IIM/ex4/example.cpp
  examples/IIM/ex5/example.cpp
  examples/IIM/ex6/example.cpp
  examples/IIM/ex7/example.cpp
  examples/IIM/ex8/example.cpp
  examples/IIM/ex9/example.cpp
Labels: libMesh

#1532 CMake: clean up link order.
  CMakeLists.txt
Labels: Build System

#1531 Do not recompute libMesh end interators.
  examples/IBFE/explicit/ex8/example.cpp
  examples/IIM/ex3/example.cpp
  examples/IIM/ex4/example.cpp
  examples/IIM/ex5/example.cpp
  examples/IIM/ex6/example.cpp
  examples/IIM/ex7/example.cpp
  examples/IMP/explicit/ex0/main.cpp
Labels: libMesh

#1530 Use hier::Index everywhere to disambiguate from Eigen::Index.
  ibtk/src/lagrangian/LDataManager.cpp
  src/IB/IIMethod.cpp
  src/IB/WallForceEvaluator.cpp
  src/navier_stokes/INSCollocatedVelocityBcCoef.cpp
Labels: Release

#1518 deprecate static system names in the FEMechanicsBase, IBFEMethod, and FEDataManager interfaces
  doc/news/changes/incompatibilities/20221116Griffith
  examples/DLM/ex0/example.cpp
  examples/IBFE/explicit/ex0/example.cpp
  examples/IBFE/explicit/ex1/example.cpp
  examples/IBFE/explicit/ex11/example.cpp
  examples/IBFE/explicit/ex4/example.cpp
  examples/IBFE/explicit/ex5/example.cpp
  examples/IBFE/explicit/ex6/example.cpp
  examples/IBFE/explicit/ex8/example.cpp
  examples/IBFE/explicit/ex9/example.cpp
  examples/IIM/ex6/example.cpp
  examples/IIM/ex7/example.cpp
  examples/IIM/ex8/example.cpp
  examples/IIM/ex9/example.cpp
  examples/Makefile.am
  examples/Makefile.in
  examples/complex_fluids/ex2/example.cpp
  examples/complex_fluids/ex4/example.cpp
  examples/fe_mechanics/ex0/example.cpp
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/ibtk_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  include/ibamr/FEMechanicsBase.h
  include/ibamr/IBFEInstrumentPanel.h
  include/ibamr/IBFEMethod.h
  src/IB/FEMechanicsBase.cpp
  src/IB/FEMechanicsExplicitIntegrator.cpp
  src/IB/IBFECentroidPostProcessor.cpp
  src/IB/IBFEDirectForcingKinematics.cpp
  src/IB/IBFEInstrumentPanel.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFEPostProcessor.cpp
  src/IB/IBFESurfaceMethod.cpp
  src/IB/IIMethod.cpp
  tests/IBFE/explicit_ex0.cpp
  tests/IBFE/explicit_ex1.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex5.cpp
  tests/IBFE/explicit_ex8.cpp
  tests/IBFE/ib_partitioning_01.cpp
  tests/IBFE/ib_partitioning_02.cpp
  tests/IBFE/instrument_panel_01.cpp
  tests/IBFE/interpolate_velocity_01.cpp
  tests/IBTK/multilevel_fe_01.cpp
  tests/fe_mechanics/fe_mechanics_ex0.cpp
  tests/spread/spread_01.cpp
  tests/spread/spread_02.cpp
Labels: enhancement

#1534 increment version to 0.13-pre
  VERSION
Labels: Release
