Repository IBAMR/IBAMR, pull requests merged in 2022-07, with the labels that each got.

#1475 Use consistent Laplacian discretization
  doc/news/changes/minor/20220707AaronBarrettColeGruninger
  include/ibamr/CIBStaggeredStokesOperator.h
  include/ibamr/INSStaggeredHierarchyIntegrator.h
  include/ibamr/StaggeredStokesOperator.h
  include/ibamr/VCStaggeredStokesOperator.h
  src/IB/CIBStaggeredStokesOperator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesOperator.cpp
  src/navier_stokes/StaggeredStokesSolverManager.cpp
  src/navier_stokes/VCStaggeredStokesOperator.cpp
  tests/navier_stokes/navier_stokes_01_2d.output
  tests/navier_stokes/navier_stokes_01_3d.output
  tests/navier_stokes/stokes_operator.cpp
  tests/navier_stokes/stokes_operator_2d.physical.input
  tests/navier_stokes/stokes_operator_2d.physical.output
Labels: Bug

#1472 Fix some minor intel warnings.
  ibtk/src/lagrangian/FEDataInterpolation.cpp
  ibtk/src/lagrangian/FEMapping.cpp
Labels: Miscellaneous

#1473 CI: compile more examples on CENTOS-7.
  .github/workflows/push-pull.yml
Labels: CI

#1479 Run clang-format on everything.
  ibtk/include/ibtk/SecondaryHierarchy.h
  ibtk/src/lagrangian/LEInteractor.cpp
  ibtk/src/utilities/SnapshotCache.cpp
  tests/IBTK/ldata_01.cpp
  tests/IBTK/version_macros.cpp
Labels: Miscellaneous

#1480 Collage changelog entries.
  doc/news/changes/0.10.0-vs-0.11.0.html
  doc/news/changes/incompatibilities/20200426AaronBarrett
  doc/news/changes/incompatibilities/20220317DavidWells
  doc/news/changes/major/20220516ColeGruninger
  doc/news/changes/major/20220629AminKolahdouz
  doc/news/changes/minor/20220121DavidWells
  doc/news/changes/minor/20220208KaustubhAmneet
  doc/news/changes/minor/20220218AaronBarrett
  doc/news/changes/minor/20220221DavidWells
  doc/news/changes/minor/20220307DavidWells
  doc/news/changes/minor/20220308AaronBarrett
  doc/news/changes/minor/20220411DavidWells
  doc/news/changes/minor/20220428DavidWells
  doc/news/changes/minor/20220526AaronBarrett
  doc/news/changes/minor/20220707AaronBarrettColeGruninger
Labels: Release

#1481 increment VERSION
  VERSION
Labels: Release
