Repository IBAMR/IBAMR, pull requests merged in 2022-11, with the labels that each got.

#1499 Implement composite, analytically divergence-free B-spline kernels
  doc/news/changes/major/20221027Griffith
  ibtk/src/lagrangian/LEInteractor.cpp
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
  tests/interpolate/interpolate_01_2d.composite_bspline_32.exact.input
  tests/interpolate/interpolate_01_2d.composite_bspline_32.exact.output
  tests/interpolate/interpolate_01_2d.composite_bspline_32.input
  tests/interpolate/interpolate_01_2d.composite_bspline_32.output
  tests/interpolate/interpolate_01_2d.composite_bspline_43.exact.input
  tests/interpolate/interpolate_01_2d.composite_bspline_43.exact.output
  tests/interpolate/interpolate_01_2d.composite_bspline_43.input
  tests/interpolate/interpolate_01_2d.composite_bspline_43.output
  tests/interpolate/interpolate_01_3d.composite_bspline_32.exact.input
  tests/interpolate/interpolate_01_3d.composite_bspline_32.exact.output
  tests/interpolate/interpolate_01_3d.composite_bspline_32.input
  tests/interpolate/interpolate_01_3d.composite_bspline_32.output
  tests/interpolate/interpolate_01_3d.composite_bspline_43.exact.input
  tests/interpolate/interpolate_01_3d.composite_bspline_43.exact.output
  tests/interpolate/interpolate_01_3d.composite_bspline_43.input
  tests/interpolate/interpolate_01_3d.composite_bspline_43.output
  tests/spread/spread_01_2d.composite_bspline_32.input
  tests/spread/spread_01_2d.composite_bspline_32.mpirun=4.input
  tests/spread/spread_01_2d.composite_bspline_32.mpirun=4.output
  tests/spread/spread_01_2d.composite_bspline_32.output
  tests/spread/spread_01_2d.composite_bspline_43.input
  tests/spread/spread_01_2d.composite_bspline_43.mpirun=4.input
  tests/spread/spread_01_2d.composite_bspline_43.mpirun=4.output
  tests/spread/spread_01_2d.composite_bspline_43.output
  tests/spread/spread_01_3d.composite_bspline_32.input
  tests/spread/spread_01_3d.composite_bspline_32.output
  tests/spread/spread_01_3d.composite_bspline_43.input
  tests/spread/spread_01_3d.composite_bspline_43.output
  tests/spread/spread_01_3d.cube.composite_bspline_32.mpirun=4.input
  tests/spread/spread_01_3d.cube.composite_bspline_32.mpirun=4.output
  tests/spread/spread_01_3d.cube.composite_bspline_43.mpirun=4.input
  tests/spread/spread_01_3d.cube.composite_bspline_43.mpirun=4.output
Labels: enhancement, Fortran

#1511 update algorithm to order perimeter nodes for the meter meshes
  doc/news/changes/minor/20221102GriffithPuelz
  doc/news/changes/minor/20221102GriffithWells
  src/IB/IBFEInstrumentPanel.cpp
  tests/IBFE/instrument_panel_01.cpp
  tests/IBFE/instrument_panel_01_3d.BSPLINE_3.output
  tests/IBFE/instrument_panel_01_3d.mpirun=8.BSPLINE_3.output
  tests/IBFE/instrument_panel_01_3d.mpirun=8.output
  tests/IBFE/instrument_panel_01_3d.output
Labels: enhancement, libMesh

#1512 IBFEInstrumentPanel: add tests with missing nodes.
  tests/IBFE/instrument_panel_01.cpp
  tests/IBFE/instrument_panel_01_3d.skip_nodes.input
  tests/IBFE/instrument_panel_01_3d.skip_nodes.mpirun=4.input
  tests/IBFE/instrument_panel_01_3d.skip_nodes.mpirun=4.output
  tests/IBFE/instrument_panel_01_3d.skip_nodes.output
Labels: Tests, libMesh

#1515 use invalid_level_number instead of "-1"
  ibtk/include/ibtk/CartGridFunction.h
  ibtk/include/ibtk/CartGridFunctionSet.h
  ibtk/include/ibtk/DebuggingUtilities.h
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/HierarchyGhostCellInterpolation.h
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/include/ibtk/HierarchyMathOps.h
  ibtk/include/ibtk/LDataManager.h
  ibtk/include/ibtk/LMarkerUtilities.h
  ibtk/include/ibtk/SAMRAIGhostDataAccumulator.h
  ibtk/include/ibtk/StaggeredPhysicalBoundaryHelper.h
  ibtk/src/boundary/HierarchyGhostCellInterpolation.cpp
  ibtk/src/boundary/physical_boundary/StaggeredPhysicalBoundaryHelper.cpp
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/LDataManager.cpp
  ibtk/src/solvers/impls/PoissonFACPreconditionerStrategy.cpp
  ibtk/src/utilities/CartGridFunction.cpp
  ibtk/src/utilities/CartGridFunctionSet.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  ibtk/src/utilities/LMarkerUtilities.cpp
  include/ibamr/AdvDiffStochasticForcing.h
  include/ibamr/CFINSForcing.h
  include/ibamr/IBHierarchyIntegrator.h
  include/ibamr/IMPInitializer.h
  include/ibamr/INSStaggeredStochasticForcing.h
  include/ibamr/StaggeredStokesPhysicalBoundaryHelper.h
  include/ibamr/SurfaceTensionForceFunction.h
  src/IB/IBEulerianForceFunction.cpp
  src/adv_diff/AdvDiffStochasticForcing.cpp
  src/complex_fluids/CFINSForcing.cpp
  src/navier_stokes/INSStaggeredStochasticForcing.cpp
  src/navier_stokes/StaggeredStokesFACPreconditionerStrategy.cpp
  src/navier_stokes/StaggeredStokesPhysicalBoundaryHelper.cpp
  src/navier_stokes/SurfaceTensionForceFunction.cpp
Labels: enhancement

#1516 use invalid_index instead of "-1"
  ibtk/include/ibtk/EdgeDataSynchronization.h
  ibtk/include/ibtk/FaceDataSynchronization.h
  ibtk/include/ibtk/HierarchyGhostCellInterpolation.h
  ibtk/include/ibtk/HierarchyMathOps.h
  ibtk/include/ibtk/NodeDataSynchronization.h
  ibtk/include/ibtk/ParallelEdgeMap.h
  ibtk/include/ibtk/SideDataSynchronization.h
  ibtk/src/boundary/physical_boundary/ExtendedRobinBcCoefStrategy.cpp
  ibtk/src/math/HierarchyMathOps.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  ibtk/src/utilities/LMarkerUtilities.cpp
  ibtk/src/utilities/ParallelEdgeMap.cpp
  include/ibamr/IBAnchorPointSpec.h
  include/ibamr/IBInstrumentationSpec.h
  include/ibamr/IBSourceSpec.h
  include/ibamr/IBTargetPointForceSpec.h
  include/ibamr/MaterialPointSpec.h
  src/IB/ConstraintIBKinematics.cpp
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/IB/IBHierarchyIntegrator.cpp
  src/IB/IBInterpolantMethod.cpp
  src/IB/IBRedundantInitializer.cpp
  src/IB/IBStandardInitializer.cpp
  src/IB/IMPInitializer.cpp
  src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp
  src/level_set/RelaxationLSBcCoefs.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredConservativeMassMomentumIntegrator.cpp
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesBlockPreconditioner.cpp
  src/navier_stokes/StokesBcCoefStrategy.cpp
Labels: enhancement

#1521 remove broken code for computing flow statistics
  include/ibamr/INSStaggeredHierarchyIntegrator.h
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
Labels: Bug, SAMRAI

#1519 add SSP RK3 time stepping to the explicit FEM solver
  doc/news/changes/minor/20221115Griffith
  examples/fe_mechanics/ex0/example.cpp
  include/ibamr/FEMechanicsBase.h
  include/ibamr/FEMechanicsExplicitIntegrator.h
  src/IB/FEMechanicsExplicitIntegrator.cpp
  tests/fe_mechanics/fe_mechanics_ex0.cpp
  tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK33.input
  tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK33.output
  tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK34.input
  tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK34.output
Labels: enhancement, libMesh

#1520 add real support for damping to explicit FE mechanics solver
  doc/news/changes/minor/20221117Griffith
  include/ibamr/FEMechanicsExplicitIntegrator.h
  src/IB/FEMechanicsExplicitIntegrator.cpp
  tests/fe_mechanics/fe_mechanics_ex0_2d.damping.input
  tests/fe_mechanics/fe_mechanics_ex0_2d.damping.output
Labels: enhancement, libMesh
