Repository IBAMR/IBAMR, pull requests merged in 2022-03, with the labels that each got.

#1435 Switch to using a new docker image.
  .github/cmake/configure_common.cmake
  .github/cmake/configure_fedora33.cmake
  .github/cmake/configure_fedora33_no_libmesh.cmake
  .github/cmake/github_ci.cmake
  .github/workflows/push-pull.yml
Labels: Infrastructure

#1438 Fix staggered stokes operator application at physical boundaries.
  src/navier_stokes/StaggeredStokesOperator.cpp
  tests/CMakeLists.txt
  tests/navier_stokes/Makefile.am
  tests/navier_stokes/Makefile.in
  tests/navier_stokes/stokes_operator.cpp
  tests/navier_stokes/stokes_operator_2d.periodic.input
  tests/navier_stokes/stokes_operator_2d.periodic.output
  tests/navier_stokes/stokes_operator_3d.periodic.input
  tests/navier_stokes/stokes_operator_3d.periodic.output
Labels: Bug

#1439 Test oldest configuration
  .github/cmake/configure_centos7.cmake
  .github/workflows/push-pull.yml
  CMakeLists.txt
  ibtk/contrib/boost/boost/math/policies/policy.hpp
Labels: Infrastructure

#1440 Fix how the advection diffusion integrators output variables with different depths.
  doc/news/changes/minor/20220308AaronBarrett
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
Labels: enhancement

#1441 Fix the 'point outside' check with some other examples.
  src/IB/IBRedundantInitializer.cpp
Labels: Bug

#1442 Docs
  doc/ci.md
  doc/cmake.md
Labels: Documentation

#1312 Cleanup test regex
  tests/CIB/cib_plate.small.mpirun=2.input
  tests/CIB/cib_plate.small.mpirun=2.output
  tests/CMakeLists.txt
  tests/IB/explicit_ex0.quartersquare2.mpirun=4.input
  tests/IB/explicit_ex0.quartersquare2.mpirun=4.output
Labels: Build System
