Repository IBAMR/IBAMR, pull requests merged in 2022-06, with the labels that each got.

#1458 Fix mpi support again
  .github/cmake/configure_archlinux.cmake
  .github/cmake/ctest_build.cmake
  .github/workflows/push-pull.yml
  CMakeLists.txt
  cmake/IBAMRConfig.cmake.in
Labels: Build System

#1349 Start work on CMake + SAMRAI 3.
  CMakeLists.txt
  ibtk/src/CMakeLists.txt
  src/CMakeLists.txt
Labels: SAMRAI 3

#1466 Fix running tests on CI
  .github/cmake/ctest_build.cmake
  .github/workflows/push-pull.yml
  attest
Labels: CI

#1463 CI: pick a better key for the no-libMesh build.
  .github/workflows/push-pull.yml
Labels: CI

#1471 Compile examples with warnings
  .github/workflows/push-pull.yml
Labels: CI

#1462 Update copyright for 0.11
  attest
  examples/IBLevelSet/ex4/CMakeLists.txt
  examples/IBLevelSet/ex4/LevelSetInitialCondition.cpp
  examples/IBLevelSet/ex4/LevelSetInitialCondition.h
  examples/IBLevelSet/ex4/SetFluidSolidDensity.cpp
  examples/IBLevelSet/ex4/SetFluidSolidDensity.h
  examples/IBLevelSet/ex4/SetFluidSolidViscosity.cpp
  examples/IBLevelSet/ex4/SetFluidSolidViscosity.h
  examples/IBLevelSet/ex4/TagLSRefinementCells.cpp
  examples/IBLevelSet/ex4/TagLSRefinementCells.h
  examples/IBLevelSet/ex4/example.cpp
  examples/IBLevelSet/ex5/CMakeLists.txt
  examples/IBLevelSet/ex5/LevelSetInitialCondition.cpp
  examples/IBLevelSet/ex5/LevelSetInitialCondition.h
  examples/IBLevelSet/ex5/SetFluidSolidDensity.cpp
  examples/IBLevelSet/ex5/SetFluidSolidDensity.h
  examples/IBLevelSet/ex5/SetFluidSolidViscosity.cpp
  examples/IBLevelSet/ex5/SetFluidSolidViscosity.h
  examples/IBLevelSet/ex5/TagLSRefinementCells.cpp
  examples/IBLevelSet/ex5/TagLSRefinementCells.h
  examples/IBLevelSet/ex5/example.cpp
  examples/IIM/Makefile.am
  examples/IIM/ex0/example.cpp
  examples/Makefile.am
  ibtk/include/ibtk/FEMapping.h
  ibtk/include/ibtk/IndexUtilities.h
  ibtk/include/ibtk/LInitStrategy.h
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/include/ibtk/private/IndexUtilities-inl.h
  ibtk/src/lagrangian/FEMapping.cpp
  include/ibamr/FESurfaceDistanceEvaluator.h
  include/ibamr/IBRedundantInitializer.h
  include/ibamr/IBStrategy.h
  include/ibamr/IMPInitializer.h
  include/ibamr/INSHierarchyIntegrator.h
  include/ibamr/INSVCStaggeredHierarchyIntegrator.h
  include/ibamr/INSVCStaggeredNonConservativeHierarchyIntegrator.h
  src/IB/FEMechanicsBase.cpp
  src/IB/IBFECentroidPostProcessor.cpp
  src/IB/IBStandardForceGen.cpp
  src/IB/IBStandardSourceGen.cpp
  src/IB/IIMethod.cpp
  src/IB/IMPInitializer.cpp
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesOperator.cpp
  tests/IBTK/ldata_01.cpp
  tests/IIM/flow_past_cylinder.cpp
  tests/IIM/flow_past_sphere.cpp
  tests/IIM/hagen_poiseuille_flow.cpp
  tests/IIM/poiseuille_flow.cpp
  tests/IIM/taylor_couette_2d.cpp
  tests/IIM/taylor_couette_3d.cpp
  tests/Makefile.am
  tests/navier_stokes/Makefile.am
  tests/navier_stokes/stokes_operator.cpp
Labels: Miscellaneous, Release

#1461 Add timers to IIMMethod.
  src/IB/IIMethod.cpp
Labels: Miscellaneous

#1428 Added a snapshot cache that can store snapshots.
  doc/news/changes/minor/20220218AaronBarrett
  ibtk/include/ibtk/SnapshotCache.h
  ibtk/include/ibtk/snapshot_utilities.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/CMakeLists.txt
  ibtk/src/utilities/SnapshotCache.cpp
  ibtk/src/utilities/snapshot_utilities.cpp
  tests/CMakeLists.txt
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
  tests/IBTK/snapshot_cache_01.cpp
  tests/IBTK/snapshot_cache_01_2d.dynamic_hierarchy.input
  tests/IBTK/snapshot_cache_01_2d.dynamic_hierarchy.mpirun=4.input
  tests/IBTK/snapshot_cache_01_2d.dynamic_hierarchy.mpirun=4.output
  tests/IBTK/snapshot_cache_01_2d.dynamic_hierarchy.output
  tests/IBTK/snapshot_cache_01_2d.static_hierarchy.input
  tests/IBTK/snapshot_cache_01_2d.static_hierarchy.mpirun=4.input
  tests/IBTK/snapshot_cache_01_2d.static_hierarchy.mpirun=4.output
  tests/IBTK/snapshot_cache_01_2d.static_hierarchy.mpirun=4.restart=1.input
  tests/IBTK/snapshot_cache_01_2d.static_hierarchy.mpirun=4.restart=1.output
  tests/IBTK/snapshot_cache_01_2d.static_hierarchy.output
Labels: enhancement

#1468 Clean up some CMake comments.
  CMakeLists.txt
  cmake/IBAMRConfig.cmake.in
  src/CMakeLists.txt
Labels: Build System, Documentation
