Repository IBAMR/IBAMR, pull requests merged in 2022-04, with the labels that each got.

#1433 CI: error out on warnings.
  .github/cmake/configure_common.cmake
  .github/workflows/push-pull.yml
  CMakeLists.txt
  ibtk/contrib/boost/boost/math/quadrature/gauss.hpp
  ibtk/contrib/boost/boost/math/quadrature/gauss_kronrod.hpp
  ibtk/contrib/muparser/src/muParserBase.cpp
  src/IB/IBRedundantInitializer.cpp
  tests/IBTK/ldata_01.cpp
Labels: Infrastructure

#1449 Add capture variables to function pointers in IBRedundantInitializer.
  doc/news/changes/incompatibilities/20200426AaronBarrett
  examples/IB/explicit/ex0/example.cpp
  examples/IBLevelSet/ex0/example.cpp
  include/ibamr/IBRedundantInitializer.h
  src/IB/IBRedundantInitializer.cpp
  tests/IB/explicit_ex0.cpp
  tests/IB/ib_body_force.cpp
  tests/IB/ib_body_force_kirchhoff.cpp
  tests/IBTK/child_integrators.cpp
  tests/wave_tank/nwt_cylinder.cpp
Labels: enhancement

#1452 Add a timer for FEMechanicsBase::assembleInteriorForceDensityRHS().
  src/IB/FEMechanicsBase.cpp
Labels: Miscellaneous, libMesh

#1451 Switch to using CG for FE projections.
  doc/news/changes/minor/20220428DavidWells
  ibtk/src/lagrangian/FEProjector.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IIM/flow_past_cylinder.cpp
  tests/IIM/flow_past_sphere.cpp
  tests/IIM/hagen_poiseuille_flow.cpp
  tests/IIM/poiseuille_flow.cpp
  tests/IIM/taylor_couette_2d.cpp
  tests/IIM/taylor_couette_3d.cpp
  tests/IIM/taylor_couette_3d.mpirun=2.output
Labels: enhancement, libMesh
