Repository IBAMR/IBAMR, pull requests merged in 2023-05, with the labels that each got.

#1583 Markers
  doc/news/changes/major/20230421DavidWells
  ibtk/include/ibtk/MarkerPatchHierarchy.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/CMakeLists.txt
  ibtk/src/utilities/MarkerPatchHierarchy.cpp
  tests/CMakeLists.txt
  tests/IBTK/marker_points_01.cpp
  tests/IBTK/marker_points_01_2d.input
  tests/IBTK/marker_points_01_2d.output
  tests/IBTK/marker_points_02.cpp
  tests/IBTK/marker_points_02_2d.input
  tests/IBTK/marker_points_02_2d.mpirun=4.input
  tests/IBTK/marker_points_02_2d.mpirun=4.output
  tests/IBTK/marker_points_02_2d.output
  tests/IBTK/marker_points_02_2d.outside.input
  tests/IBTK/marker_points_02_2d.outside.mpirun=4.input
  tests/IBTK/marker_points_02_2d.outside.mpirun=4.output
  tests/IBTK/marker_points_02_2d.outside.output
  tests/IBTK/marker_points_02_2d.set_velocity.input
  tests/IBTK/marker_points_02_2d.set_velocity.mpirun=4.input
  tests/IBTK/marker_points_02_2d.set_velocity.mpirun=4.output
  tests/IBTK/marker_points_02_2d.set_velocity.output
  tests/IBTK/marker_points_02_2d.threelevel.input
  tests/IBTK/marker_points_02_2d.threelevel.mpirun=6.input
  tests/IBTK/marker_points_02_2d.threelevel.mpirun=6.output
  tests/IBTK/marker_points_02_2d.threelevel.output
  tests/IBTK/marker_points_02_2d.timestep_1.input
  tests/IBTK/marker_points_02_2d.timestep_1.mpirun=4.input
  tests/IBTK/marker_points_02_2d.timestep_1.mpirun=4.output
  tests/IBTK/marker_points_02_2d.timestep_1.output
  tests/IBTK/marker_points_02_2d.timestep_periodic.input
  tests/IBTK/marker_points_02_2d.timestep_periodic.mpirun=4.input
  tests/IBTK/marker_points_02_2d.timestep_periodic.mpirun=4.output
  tests/IBTK/marker_points_02_2d.timestep_periodic.output
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.input
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.output
  tests/IBTK/marker_points_02_2d.twolevel.input
  tests/IBTK/marker_points_02_2d.twolevel.output
Labels: enhancement

#1584 Markers 2
  ibtk/include/ibtk/MarkerPatchHierarchy.h
  ibtk/src/utilities/MarkerPatchHierarchy.cpp
  tests/IBTK/marker_points_02.cpp
  tests/IBTK/marker_points_02_2d.timestep.collect.input
  tests/IBTK/marker_points_02_2d.timestep.collect.mpirun=2.input
  tests/IBTK/marker_points_02_2d.timestep.collect.mpirun=2.output
  tests/IBTK/marker_points_02_2d.timestep.collect.output
  tests/IBTK/marker_points_02_2d.timestep.h5part.input
  tests/IBTK/marker_points_02_2d.timestep.h5part.mpirun=2.input
  tests/IBTK/marker_points_02_2d.timestep.h5part.mpirun=2.output
  tests/IBTK/marker_points_02_2d.timestep.h5part.output
  tests/IBTK/marker_points_02_2d.timestep_periodic.collect.input
  tests/IBTK/marker_points_02_2d.timestep_periodic.collect.mpirun=4.input
  tests/IBTK/marker_points_02_2d.timestep_periodic.collect.mpirun=4.output
  tests/IBTK/marker_points_02_2d.timestep_periodic.collect.output
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.BACKWARD_EULER.input
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.BACKWARD_EULER.output
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.FORWARD_EULER.input
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.FORWARD_EULER.output
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.TRAPEZOIDAL_RULE.input
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.TRAPEZOIDAL_RULE.output
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.restart=4.input
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.restart=4.mpirun=2.input
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.restart=4.mpirun=2.output
  tests/IBTK/marker_points_02_2d.timestep_periodic_0.restart=4.output
Labels: enhancement

#1587 Markers 3
  doc/news/changes/major/20230501DavidWells
  examples/IBFE/explicit/ex4/CMakeLists.txt
  examples/IBFE/explicit/ex4/Makefile.am
  examples/IBFE/explicit/ex4/Makefile.in
  examples/IBFE/explicit/ex4/example.cpp
  examples/IBFE/explicit/ex4/input2d.markers
  ibtk/src/utilities/MarkerPatchHierarchy.cpp
  include/ibamr/IBExplicitHierarchyIntegrator.h
  include/ibamr/IBHierarchyIntegrator.h
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/IB/IBHierarchyIntegrator.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.latemarkers.mpirun=2.input
  tests/IBFE/explicit_ex4_2d.latemarkers.mpirun=2.output
  tests/IBFE/explicit_ex4_2d.latemarkers.mpirun=2.restart=80.input
  tests/IBFE/explicit_ex4_2d.latemarkers.mpirun=2.restart=80.output
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.BACKWARD_EULER.input
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.BACKWARD_EULER.output
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.FORWARD_EULER.input
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.FORWARD_EULER.output
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.TRAPEZOIDAL_RULE.input
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.TRAPEZOIDAL_RULE.output
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.input
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.output
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.restart=80.input
  tests/IBFE/explicit_ex4_2d.markers.mpirun=2.restart=80.output
  tests/IBTK/Makefile.am
  tests/IBTK/Makefile.in
Labels: enhancement

#1590 Remove LMarker et al.
  doc/news/changes/incompatibilities/20230506DavidWells
  ibtk/include/ibtk/LMarker.h
  ibtk/include/ibtk/LMarkerCoarsen.h
  ibtk/include/ibtk/LMarkerRefine.h
  ibtk/include/ibtk/LMarkerSet.h
  ibtk/include/ibtk/LMarkerSetData.h
  ibtk/include/ibtk/LMarkerSetDataFactory.h
  ibtk/include/ibtk/LMarkerSetDataIterator.h
  ibtk/include/ibtk/LMarkerSetVariable.h
  ibtk/include/ibtk/LMarkerTransaction.h
  ibtk/include/ibtk/LMarkerUtilities.h
  ibtk/include/ibtk/LSet.h
  ibtk/include/ibtk/LSetData.h
  ibtk/include/ibtk/LSetDataFactory.h
  ibtk/include/ibtk/LTransaction.h
  ibtk/include/ibtk/private/LMarker-inl.h
  ibtk/lib/Makefile.am
  ibtk/lib/Makefile.in
  ibtk/src/CMakeLists.txt
  ibtk/src/coarsen_ops/LMarkerCoarsen.cpp
  ibtk/src/lagrangian/LMarker.cpp
  ibtk/src/lagrangian/LSetData.cpp
  ibtk/src/lagrangian/LSetDataFactory.cpp
  ibtk/src/lagrangian/LSetVariable.cpp
  ibtk/src/lagrangian/LTransaction.cpp
  ibtk/src/refine_ops/LMarkerRefine.cpp
  ibtk/src/utilities/LMarkerUtilities.cpp
Labels: Miscellaneous

#1593 Fix some more marker bugs.
  src/IB/IBExplicitHierarchyIntegrator.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.vanishingmarkers.mpirun=2.input
  tests/IBFE/explicit_ex4_2d.vanishingmarkers.mpirun=2.output
Labels: Bug

#1523 Nodal pressure
  doc/news/changes/incompatibilities/20230509DavidWells
  doc/news/changes/minor/20230509DavidWells
  ibtk/include/ibtk/HierarchyMathOps.h
  ibtk/src/math/HierarchyMathOps.cpp
  ibtk/src/math/PatchMathOps.cpp
  ibtk/src/math/fortran/interp3d.f.m4
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  tests/IBTK/nodal_interpolation_01.cpp
  tests/IBTK/nodal_interpolation_01_2d.cell.cf.input
  tests/IBTK/nodal_interpolation_01_2d.cell.cf.output
  tests/IBTK/nodal_interpolation_01_2d.cell.input
  tests/IBTK/nodal_interpolation_01_2d.cell.output
  tests/IBTK/nodal_interpolation_01_3d.cell.input
  tests/IBTK/nodal_interpolation_01_3d.cell.output
Labels: enhancement

#1605 Fix a bunch of dead links.
  README.md
Labels: Documentation

#1589 Vector RAII
  doc/news/changes/minor/20230504DavidWells
  ibtk/include/ibtk/FACPreconditioner.h
  ibtk/include/ibtk/SAMRAIScopedVectorCopy.h
  ibtk/include/ibtk/SAMRAIScopedVectorDuplicate.h
  ibtk/include/ibtk/ibtk_utilities.h
  ibtk/include/ibtk/private/SAMRAIScopedVectorCopy-inl.h
  ibtk/include/ibtk/private/SAMRAIScopedVectorDuplicate-inl.h
  ibtk/src/solvers/impls/BGaussSeidelPreconditioner.cpp
  ibtk/src/solvers/impls/FACPreconditioner.cpp
  ibtk/src/solvers/interfaces/GeneralOperator.cpp
  ibtk/src/solvers/interfaces/LinearOperator.cpp
  tests/IBTK/laplace_01.cpp
  tests/IBTK/laplace_01_2d.copied_vector.input
  tests/IBTK/laplace_01_2d.copied_vector.output
  tests/IBTK/laplace_01_2d.duplicated_vector.input
  tests/IBTK/laplace_01_2d.duplicated_vector.output
Labels: enhancement, SAMRAI

#1586 ensure that regridHierarchyConfiguration is called when expected
  doc/news/changes/minor/20230320AmneetBhalla
  doc/news/changes/minor/20230501AmneetBhalla
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/src/solvers/impls/CCLaplaceOperator.cpp
  ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
  ibtk/src/solvers/impls/PETScMFFDJacobianOperator.cpp
  ibtk/src/solvers/impls/PETScNewtonKrylovSolver.cpp
  ibtk/src/solvers/impls/PoissonFACPreconditionerStrategy.cpp
  ibtk/src/solvers/impls/SCLaplaceOperator.cpp
  ibtk/src/solvers/impls/VCSCViscousOperator.cpp
  ibtk/src/solvers/wrappers/PETScMatLOWrapper.cpp
  ibtk/src/solvers/wrappers/PETScPCLSWrapper.cpp
  ibtk/src/solvers/wrappers/PETScSAMRAIVectorReal.cpp
  ibtk/src/solvers/wrappers/PETScSNESFunctionGOWrapper.cpp
  ibtk/src/solvers/wrappers/PETScSNESJacobianJOWrapper.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/AdvDiffHierarchyIntegrator.h
  include/ibamr/AdvDiffSemiImplicitHierarchyIntegrator.h
  src/IB/CIBSaddlePointSolver.cpp
  src/IB/CIBStaggeredStokesOperator.cpp
  src/IB/ConstraintIBMethod.cpp
  src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
  src/IB/KrylovMobilitySolver.cpp
  src/adv_diff/AdvDiffHierarchyIntegrator.cpp
  src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesFACPreconditionerStrategy.cpp
  src/navier_stokes/StaggeredStokesOperator.cpp
  tests/unfinished-tests/Stokes-IB/test0/main.cpp
Labels: enhancement, SAMRAI

#1607 put mpi link in correct place in CMakeLists.txt
  CMakeLists.txt
Labels: Bug, Build System
