Repository IBAMR/IBAMR, pull requests merged in 2023-06, with the labels that each got.

#1608 Fix missing include in SAMRAIScopedVectorDuplicate.
  ibtk/include/ibtk/SAMRAIScopedVectorDuplicate.h
Labels: Bug

#1556 Discontinuous (in local coordinates) FE families for IIM quantities
  doc/news/changes/major/20230606AminKolahdouz
  examples/IIM/ex0/example.cpp
  examples/IIM/ex0/input2d
  examples/IIM/ex1/README
  examples/IIM/ex1/example.cpp
  examples/IIM/ex1/input2d
  examples/IIM/ex1/input3d
  examples/IIM/ex2/example.cpp
  examples/IIM/ex2/input3d
  examples/IIM/ex3/README
  examples/IIM/ex3/example.cpp
  examples/IIM/ex3/input2d
  examples/IIM/ex4/README
  examples/IIM/ex4/input2d.LMred
  examples/IIM/ex4/input2d.SMred
  examples/IIM/ex6/example.cpp
  examples/IIM/ex6/input2d
  examples/IIM/ex7/input2d
  examples/IIM/ex8/README
  examples/IIM/ex8/input2d
  examples/IIM/ex9/example.cpp
  examples/IIM/ex9/input3d
  ibtk/src/lagrangian/FEProjector.cpp
  include/ibamr/IIMethod.h
  src/IB/IIMethod.cpp
  tests/IIM/flow_past_cylinder.cpp
  tests/IIM/flow_past_cylinder.dg.mpirun=2.input
  tests/IIM/flow_past_cylinder.dg.mpirun=2.output
  tests/IIM/flow_past_sphere.cpp
  tests/IIM/flow_past_sphere.dg.mpirun=4.input
  tests/IIM/flow_past_sphere.dg.mpirun=4.output
Labels: enhancement, libMesh

#1609 Document the (minor) solver incompatibility.
  doc/news/changes/incompatibilities/20230524DavidWells
Labels: Documentation

#1617 Update copyright to 2023.
  COPYRIGHT
Labels: Release

#1614 Fix some clang-15 warnings.
  ibtk/include/ibtk/LMesh.h
  ibtk/src/lagrangian/LMesh.cpp
  ibtk/src/utilities/box_utilities.cpp
Labels: Release

#1613 GCC 13 warning fixes
  CMakeLists.txt
  ibtk/config/config.h.tmp
  ibtk/include/ibtk/config.h.in
  ibtk/include/ibtk/libmesh_utilities.h
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/FEValues.cpp
Labels: Release

#1618 Remove sprintf().
  include/ibamr/IBInstrumentPanel.h
  src/IB/IBInstrumentPanel.cpp
Labels: Release

#1573 update convective operators for the advection-diffusion solver
  doc/news/changes/minor/20230413BoyceGriffith
  include/ibamr/AdvDiffCUIConvectiveOperator.h
  include/ibamr/AdvDiffCenteredConvectiveOperator.h
  include/ibamr/AdvDiffPPMConvectiveOperator.h
  include/ibamr/CellConvectiveOperator.h
  lib/Makefile.am
  lib/Makefile.in
  src/CMakeLists.txt
  src/adv_diff/AdvDiffCUIConvectiveOperator.cpp
  src/adv_diff/AdvDiffCenteredConvectiveOperator.cpp
  src/adv_diff/AdvDiffPPMConvectiveOperator.cpp
  src/utilities/CellConvectiveOperator.cpp
Labels: enhancement, SAMRAI, High Priority :warning:
