Repository IBAMR/IBAMR, pull requests merged in 2023-11, with the labels that each got.

#1642 Document and test the coarse fine interpolation.
  ibtk/include/ibtk/CartCellDoubleQuadraticCFInterpolation.h
  ibtk/include/ibtk/CartSideDoubleQuadraticCFInterpolation.h
  tests/CMakeLists.txt
  tests/IBTK/cf_interface.cpp
  tests/IBTK/cf_interface_2d.cell.input
  tests/IBTK/cf_interface_2d.cell.output
  tests/IBTK/cf_interface_2d.side.input
  tests/IBTK/cf_interface_2d.side.output
  tests/IBTK/cf_interface_3d.cell.input
  tests/IBTK/cf_interface_3d.cell.output
  tests/IBTK/cf_interface_3d.side.input
  tests/IBTK/cf_interface_3d.side.output
Labels: Documentation

#1638 Remove some unused variables.
  ibtk/src/math/PoissonUtilities.cpp
  ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
  src/IB/BrinkmanAdvDiffBcHelper.cpp
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp
Labels: Miscellaneous

#1653 Fix the NWT mpirun=8 test.
  tests/wave_tank/nwt_cylinder.mpirun=8.input
  tests/wave_tank/nwt_cylinder.mpirun=8.output
Labels: Tests

#1652 Add an API for getting the CFL number.
  doc/news/changes/incompatibilities/20231114DavidWells
  include/ibamr/INSHierarchyIntegrator.h
  src/IB/IBHierarchyIntegrator.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
  tests/IBTK/child_integrators.2_hierarchies.output
  tests/IBTK/child_integrators.output
Labels: enhancement
