Repository IBAMR/IBAMR, pull requests merged in 2024-06, with the labels that each got.

#1718 changed the time the boundary data was evaluated for consistent plott…
  doc/news/changes/minor/20250626ColeGruninger
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
Labels: Bug

#1714 Deallocate and remove an unused data index.
  ibtk/src/math/SAMRAIGhostDataAccumulator.cpp
Labels: enhancement, SAMRAI

#1719 Fix some minor warnings.
  include/ibamr/StaggeredStokesBlockPreconditioner.h
  tests/IBTK/curl_01.cpp
  tests/IBTK/snapshot_cache_01.cpp
  tests/adv_diff/SetFluidProperties.cpp
  tests/complex_fluids/cf_four_roll_mill.cpp
Labels: Miscellaneous

#1720 Don't save workload data in the restart database.
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/IBStrategy.h
  src/IB/IBFEMethod.cpp
  src/IB/IBStrategy.cpp
Labels: enhancement

#1705 Set up the CI to error-out on Fortran warnings.
  .github/cmake/configure_archlinux.cmake
  .github/cmake/configure_centos7.cmake
  .github/cmake/configure_fedora33.cmake
  .github/cmake/configure_fedora33_no_libmesh.cmake
Labels: CI, Fortran

#1721 Fix a level number check.
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
Labels: Bug

#1698 Add IndexUtilities::getCellCenter().
  doc/news/changes/minor/20240319DavidWells
  ibtk/include/ibtk/IndexUtilities.h
  ibtk/include/ibtk/config.h.in
  ibtk/include/ibtk/private/IndexUtilities-inl.h
  tests/CMakeLists.txt
  tests/IBTK/index_utilities.cpp
  tests/IBTK/index_utilities_2d.input
  tests/IBTK/index_utilities_2d.output
  tests/IBTK/index_utilities_3d.input
  tests/IBTK/index_utilities_3d.output
  tests/tests.h
Labels: enhancement
