Repository IBAMR/IBAMR, pull requests merged in 2024-01, with the labels that each got.

#1665 Fix an invalid memory reference.
  tests/adv_diff/adv_diff_regridding.cpp
Labels: Bug, Tests

#1669 Remove some unused variables.
  ibtk/src/lagrangian/FEDataManager.cpp
  src/IB/IIMethod.cpp
Labels: Miscellaneous

#1668 Fix a new GCC warning.
  ibtk/include/ibtk/config.h.in
Labels: Miscellaneous

#1674 Cleanup basic inheritance
  ibtk/include/ibtk/LDataManager.h
  include/ibamr/ConstraintIBKinematics.h
  include/ibamr/IBFEDirectForcingKinematics.h
Labels: Miscellaneous

#1670 Prevent in-source builds.
  CMakeLists.txt
Labels: Build System

#1667 Marker restart bug
  doc/news/changes/minor/20240104DavidWells
  examples/IBFE/explicit/ex4/example.cpp
  include/ibamr/IBExplicitHierarchyIntegrator.h
  src/IB/IBExplicitHierarchyIntegrator.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/explicit_ex4_2d.markers.regrid.mpirun=2.restart=70.input
  tests/IBFE/explicit_ex4_2d.markers.regrid.mpirun=2.restart=70.output
Labels: Bug

#1671 Introduce doIntegrateHierarchy() virtual function.
  doc/news/changes/incompatibilities/20240123AaronBarrett
  examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.cpp
  examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.h
  ibtk/include/ibtk/HierarchyIntegrator.h
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/AdvDiffPredictorCorrectorHierarchyIntegrator.h
  include/ibamr/AdvDiffSemiImplicitHierarchyIntegrator.h
  include/ibamr/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.h
  include/ibamr/IBExplicitHierarchyIntegrator.h
  include/ibamr/IBImplicitStaggeredHierarchyIntegrator.h
  include/ibamr/IBInterpolantHierarchyIntegrator.h
  include/ibamr/INSCollocatedHierarchyIntegrator.h
  include/ibamr/INSStaggeredHierarchyIntegrator.h
  include/ibamr/INSVCStaggeredConservativeHierarchyIntegrator.h
  include/ibamr/INSVCStaggeredNonConservativeHierarchyIntegrator.h
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
  src/IB/IBInterpolantHierarchyIntegrator.cpp
  src/adv_diff/AdvDiffPredictorCorrectorHierarchyIntegrator.cpp
  src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
  src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  tests/IBTK/child_integrators.2_hierarchies.output
  tests/IBTK/child_integrators.cpp
  tests/IBTK/child_integrators.output
Labels: enhancement

#1675 Make things work with IBSAMRAI2 version 2024.
  ibtk/src/utilities/IBTKInit.cpp
  ibtk/src/utilities/IBTK_MPI.cpp
Labels: Miscellaneous, Release

#1677 Run clang-format on everything.
  examples/ConstraintIB/moving_plate/RigidBodyKinematics.cpp
  examples/adv_diff/ex8/SetFluidProperties.h
  examples/adv_diff/ex8/example.cpp
  ibtk/include/ibtk/FEDataManager.h
  ibtk/include/ibtk/ibtk_enums.h
  ibtk/include/ibtk/private/PartitioningBox-inl.h
  ibtk/src/lagrangian/BoxPartitioner.cpp
  ibtk/src/lagrangian/FEDataManager.cpp
  ibtk/src/lagrangian/LEInteractor.cpp
  ibtk/src/lagrangian/LMesh.cpp
  ibtk/src/lagrangian/StableCentroidPartitioner.cpp
  ibtk/src/math/HierarchyMathOps.cpp
  ibtk/src/utilities/HierarchyIntegrator.cpp
  ibtk/src/utilities/MarkerPatchHierarchy.cpp
  ibtk/src/utilities/SnapshotCache.cpp
  ibtk/src/utilities/snapshot_utilities.cpp
  include/ibamr/ibamr_enums.h
  src/IB/BrinkmanPenalizationStrategy.cpp
  src/IB/ConstraintIBKinematics.cpp
  src/IB/FEMechanicsBase.cpp
  src/IB/IBExplicitHierarchyIntegrator.cpp
  src/IB/IBFEMethod.cpp
  src/IB/IBFESurfaceMethod.cpp
  src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
  src/IB/IBInterpolantMethod.cpp
  src/IB/IBMethod.cpp
  src/IB/IBStrategy.cpp
  src/IB/IIMethod.cpp
  src/IB/IMPInitializer.cpp
  src/IB/IMPMethod.cpp
  src/IB/KrylovMobilitySolver.cpp
  src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp
  src/level_set/FESurfaceDistanceEvaluator.cpp
  src/level_set/LSInitStrategy.cpp
  src/navier_stokes/INSHierarchyIntegrator.cpp
  src/navier_stokes/MarangoniSurfaceTensionForceFunction.cpp
  src/navier_stokes/SurfaceTensionForceFunction.cpp
  tests/IBFE/explicit_ex4.cpp
  tests/IBFE/instrument_panel_01.cpp
  tests/IBTK/cf_interface.cpp
  tests/IBTK/equal_eps.cpp
  tests/adv_diff/SetFluidProperties.h
  tests/adv_diff/adv_diff_convec_opers.cpp
  tests/refine/rt0_refine_01.cpp
Labels: Miscellaneous, Release

#1678 Collate changelog entries for 0.14.
  doc/news/changes/0.13.0-vs-0.14.0.html
  doc/news/changes/incompatibilities/20231114DavidWells
  doc/news/changes/incompatibilities/20240123AaronBarrett
  doc/news/changes/minor/20230413BoyceGriffith
  doc/news/changes/minor/20230911Ramakrishnan
  doc/news/changes/minor/20231127Ramakrishnan
  doc/news/changes/minor/20240103Ramakrishnan
  doc/news/changes/minor/20240104DavidWells
Labels: Release, Documentation

#1680 add additional composite B-spline kernel functions
  doc/news/changes/minor/20240129BoyceGriffith
  ibtk/src/lagrangian/LEInteractor.cpp
  ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
  ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
  tests/interpolate/interpolate_01.cpp
  tests/interpolate/interpolate_01_2d.composite_bspline_54.exact.input
  tests/interpolate/interpolate_01_2d.composite_bspline_54.exact.output
  tests/interpolate/interpolate_01_2d.composite_bspline_54.input
  tests/interpolate/interpolate_01_2d.composite_bspline_54.output
  tests/interpolate/interpolate_01_2d.composite_bspline_65.exact.input
  tests/interpolate/interpolate_01_2d.composite_bspline_65.exact.output
  tests/interpolate/interpolate_01_2d.composite_bspline_65.input
  tests/interpolate/interpolate_01_2d.composite_bspline_65.output
  tests/interpolate/interpolate_01_3d.composite_bspline_54.exact.input
  tests/interpolate/interpolate_01_3d.composite_bspline_54.exact.output
  tests/interpolate/interpolate_01_3d.composite_bspline_54.input
  tests/interpolate/interpolate_01_3d.composite_bspline_54.output
  tests/interpolate/interpolate_01_3d.composite_bspline_65.exact.input
  tests/interpolate/interpolate_01_3d.composite_bspline_65.exact.output
  tests/interpolate/interpolate_01_3d.composite_bspline_65.input
  tests/interpolate/interpolate_01_3d.composite_bspline_65.output
  tests/spread/spread_01_2d.composite_bspline_43.mpirun=4.output
  tests/spread/spread_01_2d.composite_bspline_54.input
  tests/spread/spread_01_2d.composite_bspline_54.mpirun=4.input
  tests/spread/spread_01_2d.composite_bspline_54.mpirun=4.output
  tests/spread/spread_01_2d.composite_bspline_54.output
  tests/spread/spread_01_2d.composite_bspline_65.input
  tests/spread/spread_01_2d.composite_bspline_65.mpirun=4.input
  tests/spread/spread_01_2d.composite_bspline_65.mpirun=4.output
  tests/spread/spread_01_2d.composite_bspline_65.output
  tests/spread/spread_01_3d.composite_bspline_54.input
  tests/spread/spread_01_3d.composite_bspline_54.output
  tests/spread/spread_01_3d.composite_bspline_65.input
  tests/spread/spread_01_3d.composite_bspline_65.output
  tests/spread/spread_01_3d.cube.composite_bspline_54.mpirun=4.input
  tests/spread/spread_01_3d.cube.composite_bspline_54.mpirun=4.output
  tests/spread/spread_01_3d.cube.composite_bspline_65.mpirun=4.input
  tests/spread/spread_01_3d.cube.composite_bspline_65.mpirun=4.output
Labels: enhancement, Fortran

#1679 Increment version to 0.15.0-pre
  VERSION
Labels: Release
