Repository IBAMR/IBAMR, pull requests merged in 2024-05, with the labels that each got.

#1707 Only compute vorticity when we need it.
  doc/news/changes/minor/20240515DavidWells
  ibtk/src/utilities/HierarchyIntegrator.cpp
  include/ibamr/INSCollocatedHierarchyIntegrator.h
  include/ibamr/INSHierarchyIntegrator.h
  include/ibamr/INSStaggeredHierarchyIntegrator.h
  include/ibamr/INSVCStaggeredHierarchyIntegrator.h
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
  tests/navier_stokes/navier_stokes_01_2d.collocated.input
  tests/navier_stokes/navier_stokes_01_2d.collocated.output
Labels: enhancement

#1703 More ci cleanup
  .github/workflows/push-pull.yml
Labels: CI

#1706 Fix a fortran bug related to accidental commenting a variable in leve…
  src/level_set/fortran/levelsetops2d.f.m4
  tests/level_set/relaxation_ls_2d.weno5.mpirun=4.input
  tests/level_set/relaxation_ls_2d.weno5.mpirun=4.output
Labels: Fortran
