Repository IBAMR/IBAMR, pull requests merged in 2025-01, with the labels that each got.

#1547 Cmake fixes + bump silo version
  CMakeLists.txt
  cmake/IBAMRConfig.cmake.in
  configure
  ibtk/configure
  m4/configure_silo.m4
Labels: Build System

#1688 Make get functions public in IBMethod.
  ibtk/include/ibtk/ibtk_enums.h
  include/ibamr/IBMethod.h
  src/IB/IBMethod.cpp
Labels: enhancement

#1778 Add a second new CI runner with updated dependencies.
  .github/workflows/push-pull.yml
Labels: Release, CI

#1776 Add a new CI runner with updated dependencies.
  .github/workflows/push-pull.yml
Labels: Release, CI

#1779 Fix some out-of-date autotools files.
  Makefile.in
  examples/IBLevelSet/ex6/Makefile.in
  ibtk/Makefile.in
Labels: Release, Build System

#1780 Consolidate CI runners.
  .github/workflows/push-pull.yml
Labels: CI

#1781 Require libMesh 1.7 or newer.
  CMakeLists.txt
  configure
  doc/news/changes/major/20250129DavidWells
  ibtk/configure
  m4/configure_libmesh.m4
Labels: Release, Build System, libMesh

#1783 Add the changelog for 0.16.
  doc/news/changes/0.15.0-vs-0.16.0.html
  doc/news/changes/incompatibilities/20240720BoyceGriffith
  doc/news/changes/incompatibilities/20250109DavidWells
  doc/news/changes/major/20240819BoyceGriffith
  doc/news/changes/major/20250129DavidWells
  doc/news/changes/minor/20240319DavidWells
  doc/news/changes/minor/20240907BoyceGriffith
  doc/news/changes/minor/20250626ColeGruninger
  scripts/maintenance/generate-changes.sh
Labels: Release
