Repository IBAMR/IBAMR, pull requests merged in 2025-09, with the labels that each got.

#1725 change the velocity interpolation correction term.
  doc/news/changes/minor/20250609QiSun
  src/IB/IIMethod.cpp
  tests/IIM/flow_past_cylinder.dg.mpirun=2.output
  tests/IIM/flow_past_cylinder.mpirun=2.output
  tests/IIM/flow_past_sphere.dg.mpirun=4.output
  tests/IIM/flow_past_sphere.mpirun=4.output
  tests/IIM/flow_past_sphere.mpirun=4.restart=5.output
  tests/IIM/hagen_poiseuille_flow.mpirun=2.output
  tests/IIM/poiseuille_flow.mpirun=2.output
  tests/IIM/taylor_couette_2d.mpirun=2.output
  tests/IIM/taylor_couette_3d.mpirun=2.output
Labels: enhancement, C++

#1766 conditionally register force for restart even if it is not being output
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  tests/ConstraintIB/oscillating_rigid_cylinder.restart=40.input
  tests/ConstraintIB/oscillating_rigid_cylinder.restart=40.output
Labels: Bug

#1632 fix examples/IB/explicit/ex6
  examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.cpp
Labels: Bug

#1837 CI: turn on more warnings in the macOS runner.
  .github/workflows/push-pull.yml
  CMakeLists.txt
  config/config.h.tmp
  configure
  configure.ac
  ibtk/config/IBTK_config.h.tmp.in
  ibtk/config/config.h.tmp
  ibtk/configure
  ibtk/configure.ac
  ibtk/contrib/boost/boost/type_traits/intrinsics.hpp
  ibtk/include/ibtk/config.h.in
  ibtk/include/ibtk/muParserCartGridFunction.h
  ibtk/include/ibtk/muParserRobinBcCoefs.h
  ibtk/src/boundary/physical_boundary/muParserRobinBcCoefs.cpp
  ibtk/src/utilities/muParserCartGridFunction.cpp
  include/ibamr/AdvDiffStochasticForcing.h
  include/ibamr/NonbondedForceEvaluator.h
  include/ibamr/Wall.h
  src/adv_diff/AdvDiffStochasticForcing.cpp
  tests/IBTK/version_macros.cpp
Labels: CI

#1538 Fix restarts with the DLM example.
  examples/DLM/ex0/example.cpp
Labels: Bug, libMesh

#1603 CI: add some simple header checks.
  .github/workflows/push-pull.yml
  ibtk/include/ibtk/private/LDataManager-inl.h
  include/ibamr/LevelSetUtilities.h
  include/ibamr/SurfaceTensionForceFunction.h
  include/ibamr/private/IBInstrumentationSpec-inl.h
Labels: CI
