Repository IBAMR/IBAMR, pull requests merged in 2025-04, with the labels that each got.

#1790 CI: combine two more runners.
  .github/workflows/push-pull.yml
Labels: CI

#1792 Remove old CI scripts.
  .github/cmake/configure_archlinux.cmake
  .github/cmake/configure_ccache.cmake
  .github/cmake/configure_common.cmake
  .github/cmake/configure_fedora33.cmake
  .github/cmake/configure_fedora33_no_libmesh.cmake
  .github/cmake/ctest_configure.cmake
  .github/cmake/ctest_exclusions.cmake
  .github/cmake/ctest_test.cmake
  .github/cmake/github_ci.cmake
Labels: CI

#1791 Cleanup CI caching
  .github/workflows/push-master.yml
  .github/workflows/push-pull.yml
Labels: CI

#1797 avoid some synchs
  include/ibamr/INSStaggeredHierarchyIntegrator.h
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
Labels: enhancement

#1793 avoid some copies
  ibtk/include/ibtk/CCLaplaceOperator.h
  ibtk/include/ibtk/SCLaplaceOperator.h
  ibtk/src/solvers/impls/CCLaplaceOperator.cpp
  ibtk/src/solvers/impls/SCLaplaceOperator.cpp
  ibtk/src/solvers/impls/VCSCViscousOperator.cpp
  include/ibamr/StaggeredStokesOperator.h
  src/IB/CIBStaggeredStokesOperator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/StaggeredStokesOperator.cpp
  src/navier_stokes/VCStaggeredStokesOperator.cpp
Labels: enhancement

#1799 Fix CI caching
  .github/workflows/push-master.yml
  .github/workflows/push-pull.yml
Labels: CI

#1800 fix EE viz output in INSStaggeredHierarchyIntegrator
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  tests/navier_stokes/navier_stokes_01_2d.input
  tests/navier_stokes/navier_stokes_01_2d.output
Labels: Bug, Tests

#1795 standardize spelling of nullspace in the library
  doc/news/changes/incompatibilities/20250414BoyceGriffith
  ibtk/examples/VCViscousSolver/example.cpp
  ibtk/include/ibtk/LinearSolver.h
  ibtk/include/ibtk/PETScKrylovLinearSolver.h
  ibtk/include/ibtk/PETScLevelSolver.h
  ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
  ibtk/src/solvers/impls/PETScLevelSolver.cpp
  ibtk/src/solvers/interfaces/LinearSolver.cpp
  include/ibamr/CIBSaddlePointSolver.h
  include/ibamr/IBImplicitStaggeredHierarchyIntegrator.h
  include/ibamr/KrylovLinearSolverStaggeredStokesSolverInterface.h
  include/ibamr/KrylovMobilitySolver.h
  include/ibamr/StaggeredStokesBlockPreconditioner.h
  include/ibamr/StaggeredStokesFACPreconditioner.h
  include/ibamr/StaggeredStokesFACPreconditionerStrategy.h
  include/ibamr/StaggeredStokesSolver.h
  src/IB/CIBSaddlePointSolver.cpp
  src/IB/ConstraintIBMethod.cpp
  src/IB/KrylovMobilitySolver.cpp
  src/IB/StaggeredStokesIBLevelRelaxationFACOperator.cpp
  src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
  src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
  src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
  src/navier_stokes/KrylovLinearSolverStaggeredStokesSolverInterface.cpp
  src/navier_stokes/StaggeredStokesBlockFactorizationPreconditioner.cpp
  src/navier_stokes/StaggeredStokesBlockPreconditioner.cpp
  src/navier_stokes/StaggeredStokesFACPreconditioner.cpp
  src/navier_stokes/StaggeredStokesFACPreconditionerStrategy.cpp
  src/navier_stokes/StaggeredStokesLevelRelaxationFACOperator.cpp
  src/navier_stokes/StaggeredStokesPETScLevelSolver.cpp
  src/navier_stokes/StaggeredStokesProjectionPreconditioner.cpp
  src/navier_stokes/StaggeredStokesSolver.cpp
  src/navier_stokes/VCStaggeredStokesProjectionPreconditioner.cpp
  tests/IBTK/vc_viscous_solver.cpp
  tests/unfinished-tests/Stokes-IB/test0/main.cpp
Labels: enhancement

#1802 Fixed upper convected derivative in cases of non divergence-free velocity fields.
  Makefile.in
  doc/news/changes/minor/20250424AaronBarrett
  ibtk/Makefile.in
  include/ibamr/CFUpperConvectiveOperator.h
  src/complex_fluids/CFUpperConvectiveOperator.cpp
  src/complex_fluids/fortran/upper_convective_op2d.f.m4
  src/complex_fluids/fortran/upper_convective_op3d.f.m4
  tests/CMakeLists.txt
  tests/complex_fluids/Makefile.am
  tests/complex_fluids/Makefile.in
  tests/complex_fluids/cf_ucd.cpp
  tests/complex_fluids/cf_ucd_2d.input
  tests/complex_fluids/cf_ucd_2d.output
  tests/complex_fluids/cf_ucd_3d.input
  tests/complex_fluids/cf_ucd_3d.output
Labels: Bug
